### ISSUE TITLE
Spot check: iOS Apps build (4) 

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/qa#1147]
# iOS App Spot Check

## What to test

- [x] Latest iOS "PhET Simulations" App:  version 1.5.0 build (4) - deployed via testflight
- [x] Latest iOS "PhET4Schools Access Program" app: version 1.5.1 build (4) - deployed via testflight

## Things to test

- [x] Remove any currently installed apps, install the latest app from TestFlight, then put your device in offline mode. 
 Open the app and verify that 1 phet-brand releases mentioned in https://github.com/phetsims/qa/issues/1114 are present and working as expected.
- [x] Verify that the "PhET Simulations" app is not prompting for an access code
- [x] Verify that the "PhET4Schools Access Program" app requires an access code (use `24AP888Z` to test)
- [x] Verify blank/empty collection view is fixed https://github.com/phetsims/phet-ios-app/issues/635
- [x] Verify crashes are fixed/significantly reduced https://github.com/phetsims/phet-ios-app/issues/634
- [x] Verify search behavior isn't buggy https://github.com/phetsims/phet-ios-app/issues/638

## Devices to test

- [x] iPad
- [x] iPhone

**Comment by oliver-phet** [comment]
Note: Steve incorporated a quick fix for the search behavior and collection view, but a more comprehensive fix would require a deep dive into the update process.

**Comment by oliver-phet** [comment]
> @oliver-phet based on [phetsims/phet-ios-app#641](https://github.com/phetsims/phet-ios-app/issues/641), it isn't clear how to test the first item in the list above. Can you clarify how you would like QA to test this?

All that is needed is to verify the app is properly updating to the latest version of a sim - so you can ignore checking that specific versions are included in the cache. Note: the build date may differ from what is available on the website (As mentioned in https://github.com/phetsims/phet-ios-app/issues/641#issuecomment-2369581154, the app only updates to a new `_all` file if the device language matches.)

**Comment by KatieWoe** [comment]
QA is done

**Comment by kathy-phet** [comment]
I'm going to close this issue.
