### ISSUE TITLE
RC test: Reactants, Products and Leftovers 1.2.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#162]
@ariel-phet, Reactants, Products and Leftovers 1.2.0-rc.1 is ready for RC testing.

**[Link to sim _en.html](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.1/phet/reactants-products-and-leftovers_en_phet.html)**
**[Link to sim _all.html](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.1/phet/reactants-products-and-leftovers_all_phet.html)**
**[Link to sim iframe](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.1/phet/reactants-products-and-leftovers_all_iframe_phet.html)**
**[Link to sim XHTML](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.1/phet/xhtml/reactants-products-and-leftovers_all_phet.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/18xLAwWnuotByjujL_yxQjaNpdYqDOZa192NFdjLfOQI/edit#gid=1867860721)**

**Issues to Verify**
(*all should be marked "status:fixed-pending-testing"*)  
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/reactants-products-and-leftovers/issues/51
- [x] Carefully test the XHTML like the iframe, to ensure that it still works appropriately

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test
- [x] Does AR need to be notified for any LOL updates?

If any new issues are found, please note them in https://github.com/phetsims/reactants-products-and-leftovers/issues and reference this issue.  

@ariel-phet please assign and prioritize

**Comment by KatieWoe** [comment]
QA is Done.  (As I have free time I will continue to try to find more examples of phetsims/reactants-products-and-leftovers#62)

**Comment by pixelzoom** [comment]
@KatieWoe The checklist in https://github.com/phetsims/QA/issues/162#issue-347532957 is not completed. Back to you.

**Comment by pixelzoom** [comment]
Issue to be regression tested in 1.2.0-rc.2 include:

- [ ] phetsims/reactants-products-and-leftovers#59
- [ ] phetsims/reactants-products-and-leftovers#60
- [ ] phetsims/reactants-products-and-leftovers#61

phetsims/vibe#35 will be ignored for the 1.2.0 release, to be addressed in a future maintenance release.

**Comment by pixelzoom** [comment]
RC testing continues in https://github.com/phetsims/QA/issues/169.  Closing.
