### ISSUE TITLE
RC test: Molarity 1.4.0-rc.2 RC test

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#166]
Previous RC test was https://github.com/phetsims/QA/issues/161.

This RC test is on hold until these PhET-iO issues are addressed:

- [x] phetsims/phet-io-wrappers#135
- [x] phetsims/phet-io-wrappers#136
- [x] phetsims/phet-io-wrappers#137
- [x] phetsims/phet-io-wrappers#138
- [x] phetsims/phet-io-wrappers#139

The extent of these changes will determine whether a full RC test is needed.

**Comment by pixelzoom** [comment]
@samreid Please verify that the above checklist is the complete list of PhET-iO issues that need to be addressed prior to this RC.

**Comment by samreid** [comment]
That's everything I'm aware of that was discovered during the RC.  I'll track addressing them in this parent issue: https://github.com/phetsims/phet-io-wrappers/issues/140

**Comment by samreid** [comment]
@kathy-phet requested to be notified when this simulation is published, so she can deliver it to clients.

**Comment by pixelzoom** [comment]
@samreid @zepumph Please notify me when I can proceed with https://github.com/phetsims/QA/issues/166.

**Comment by samreid** [comment]
Will do, thanks!

**Comment by pixelzoom** [comment]
@KatieWoe Molarity 1.4.0-rc.2 is ready for RC testing.

**[Link to sim _en.html](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.2/phet/molarity_en_phet.html)**
**[Link to sim _all.html](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.2/phet/molarity_all_phet.html)**
**[Link to sim iframe](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.2/phet/molarity_all_iframe_phet.html)**
**[Link to sim XHTML](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.2/phet/xhtml/molarity_all_phet.html)**
**[Link to phet-io standalone](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.2/phet-io/molarity_all_phet-io.html?phetioStandalone)**
**[Link to phet-io studio](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.2/phet-io/wrappers/studio/studio.html)**

This RC does not require a full test matrix.   Please test the PhET-iO issues enumerated above in https://github.com/phetsims/QA/issues/166#issue-349234431, and close them if no problems are found.

**Comment by pixelzoom** [comment]
Note to self... Since the instructions for deployment are incomplete, here's how I created this RC version.  Relevant repos and commits were identified by @samreid in https://github.com/phetsims/phet-io-wrappers/issues/140#issuecomment-412628956.

```
# Cherry pick changes to molarity
% cd molarity
% git checkout 1.4
% git checkout master -- js/molarity/view/PrecipitateNode.js
% git add js/molarity/view/PrecipitateNode.js
% git commit -m "..."
% git push

# Update dependencies.json to use master for phet-io and phet-io-wrapper
cd perennial
grunt checkout-target --repo=molarity --target=1.4
cd phet-io
git checkout master
cd phet-io-wrappers
git checkout master
cd molarity
grunt
cp build/phet/dependencies.json dependencies.json
git add dependencies.json
git commit -m “use master for phet-io and phet-io-wrappers”
git push

# Deploy the RC
grunt rc --branch=1.4 --brands=phet,phet-io
```

**Comment by KatieWoe** [comment]
Is there a link to the index wrapper?

**Comment by pixelzoom** [comment]
@samreid Can you answer @KatieWoe's question?  I have no idea what "the index wrapper" is.

**Comment by KatieWoe** [comment]
This issue: https://github.com/phetsims/phet-io-wrappers/issues/137 had a related problem that has been added in a comment to that issue.  Other than that, QA is done.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/phet-io-wrappers/issues/137#issuecomment-413031210 notes that the "related problem" is "expected behavior on safari".    @samreid @zepumph @KatieWoe is it safe to assume that all issues are therefore addressed, and I can proceed with publishing 1.4.0?

**Comment by pixelzoom** [comment]
Ah... I see @KatieWoe's Edit in https://github.com/phetsims/QA/issues/166#issuecomment-413015407 and @zepumph's "thumbs up".   So I'm going to publish 1.4.0.

**Comment by samreid** [comment]
Sounds great, thanks!

**Comment by pixelzoom** [comment]
1.4.0 is published for phet and phet-io brands.

At the end of `grunt production --repo=molarity --brands=phet,phet-io --branch=1.4`, I see:

> If this is a version that will be used with students, then make sure to remove the password protection.
See https://github.com/phetsims/phet-io/blob/master/doc/phet-io-security.md for details.
Make sure that the current level of instrumentation is represented here in the Instrumentation Status Spreadsheet:
https://docs.google.com/spreadsheets/d/1pU9izdNQkd9vr8TvLAfXe_v68yh-7potH-y712FBPr8/edit#gid=0
MAKE SURE TO UPDATE THE "Latest Published Version" COLUMN.
If you are delivering this to a partner, update partners.md (phet-io/doc/partners.md) to show this delivery.
Read the intro of the document to make sure that you format the entry correctly.

I'm really confused about the spreadsheet. Why is the "Latest Published Version" column empty, when this sim has clearly been published before?  How is the LOC column derived, it's way off?

I also don't know whether we're delivering to a partner, so not sure what to do about partners.md.

Can @samreid or @zepumph please handle these remaining tasks?

**Comment by pixelzoom** [comment]
I also have no idea how to verify that the phet-io branded version was properly deployed.

**Comment by samreid** [comment]
The simulation was published at https://phet-io.colorado.edu/sims/molarity/1.4.0/

**Comment by zepumph** [comment]
I updated the spreadsheet, saying that 1.4.0 is the latest published version for phet-io.
