### ISSUE TITLE
RC test: Reactants, Products and Leftovers 1.2.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#169]
Previous RC test was https://github.com/phetsims/QA/issues/162.

@KatieWoe, Reactants, Products and Leftovers 1.2.0-rc.2 is ready for RC testing.

**[Link to sim _en.html](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.2/phet/reactants-products-and-leftovers_en_phet.html)**
**[Link to sim _all.html](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.2/phet/reactants-products-and-leftovers_all_phet.html)**
**[Link to sim iframe](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.2/phet/reactants-products-and-leftovers_all_iframe_phet.html)**
**[Link to sim XHTML](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.2/phet/xhtml/reactants-products-and-leftovers_all_phet.html)**

This RC test does not require a test matrix.  You can spot check the issues listed below.

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] phetsims/reactants-products-and-leftovers#59
- [x] phetsims/reactants-products-and-leftovers#60
- [x] phetsims/reactants-products-and-leftovers#61

**Comment by pixelzoom** [comment]
Note to self... Steps used to create this RC:

```
# branch vegas and cherry pick fixes
cd perennial
grunt checkout-target --repo=reactants-products-and-leftovers --branch=1.2
cd vegas
git checkout -b reactants-products-and-leftovers-1.2
git checkout master -- js/FiniteStatusBar.js
git add js/FiniteStatusBar.js
git commit -m 'fix phetsims/reactants-products-and-leftovers#59'
git checkout master -- js/LevelSelectionButton.js
git commit -m 'fix phetsims/reactants-products-and-leftovers#61'
git push

# update dependencies.json
cd reactants-products-and-leftovers
grunt
cp build/phet/dependencies.json .
git add dependencies.json
git commit -m 'use vegas branch reactants-products-and-leftovers-1.2'
git push

# deploy the RC
grunt rc --brands=phet --branch=1.2
```

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thanks @KatieWoe!  I'll proceed with publishing 1.2.0.

**Comment by pixelzoom** [comment]
1.2.0 has been published.  Closing.
