### ISSUE TITLE
RC Test: States of Matter 1.1.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#185]
States of Matter 1.1.0-rc.1 is ready for release candidate (RC) testing.  This release is phet brand only with no a11y.  This release is motivated by a number of requests for changes to the sim, see the list of issues below for details.  Please document issues in https://github.com/phetsims/states-of-matter/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<h3>General RC Test</h3>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Issues to Verify</h3>
These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

- [x] [Thermometer resets tilted on states screen](https://github.com/phetsims/states-of-matter/issues/223)
- [x] [Neon and Argon Particles begin flashing and falling to the bottom](https://github.com/phetsims/states-of-matter/issues/222)
- [x] [Cooled solids drift to the side of the container](https://github.com/phetsims/states-of-matter/issues/220)
- [x] [Slight upward jump for neon and argon when cooled from solid state](https://github.com/phetsims/states-of-matter/issues/219)
- [x] [Query parameter to start sim using Celsius](https://github.com/phetsims/states-of-matter/issues/216)
- [x] [User feedback, multiple](https://github.com/phetsims/states-of-matter/issues/214) - This issue has a bunch of things in it, so it's going to require the tester to read it, understand it, and test everything that I describe as having been addressed.  Be prepared, it will take some time.
- [x] [Assertion failed: unhandled substance: ADJUSTABLE_ATOM](https://github.com/phetsims/states-of-matter/issues/213)
- [x] [User reported issue: shape of liquid](https://github.com/phetsims/states-of-matter/issues/212)
- [x] [incorporate support for Legends of Learning](https://github.com/phetsims/states-of-matter/issues/210)
- [x] [User reported issue: particles scatter outside of container](https://github.com/phetsims/states-of-matter-basics/issues/16) - this was reported against States of Matter Basics, but can be verified using plain States of Matter
- [x] ["Solid" drifts to the left on States Screen](https://github.com/phetsims/states-of-matter-basics/issues/15) - this was also reported against States of Matter Basics, but can be verified using plain States of Matter

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/xhtml/states-of-matter_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/15oDRy4E5kqXxhZVZSfU-EvZvm6eeZKMQAjcU_6B3ExU/edit#gid=121321640)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.

  </details>

<br>

<hr>

</details>

**Comment by phet-steele** [comment]
@KatieWoe @lmulhall-phet checkboxes cannot be marked when they are in/preceeded by markdown, for some reason. I had to take out the list of issues to verify from the collapsible section AND put it before the collapsible section (wasn't working putting it at the end of the issue). Please rethink the template or find a better solution in phetsims/QA/issues/19.

**Comment by phet-steele** [comment]
RE https://github.com/phetsims/QA/issues/185#issuecomment-420794350, see https://github.com/phetsims/QA/issues/19#issuecomment-420807899 and https://github.com/phetsims/QA/issues/19#issuecomment-420900480. We are good now, I hope.

**Comment by lmulhall-phet** [comment]
@jbphet, if we're planning on doing another RC, do you think we could get some query parameters that speed up the heating/cooling process?

**Comment by KatieWoe** [comment]
@jbphet QA is done

**Comment by jbphet** [comment]
Based on a discussion that occurred during the 9/20/2018 status meeting, we realized that the XHTML version had not been tested.  I updated the description above to include the XHTML link, and am assigning back to QA to verify (from the sound of it, it should be a quick verification).

**Comment by KatieWoe** [comment]
QA confirmed.

**Comment by JRomero0613** [comment]
XHTML confirmed on Mac 10.10.5, 10.11.6, and 10.12.6.

**Comment by KatieWoe** [comment]
Confirmed on Win 7, Win 8.1, and Chrome OS

**Comment by jbphet** [comment]
Thanks @KatieWoe and crew!  I'll address the issues individually, and we'll call this done.  Closing.
