### ISSUE TITLE
RC Test: John Travoltage 1.5.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#196]
@KatieWoe, @emily-phet - John Travoltage 1.5.0-rc.1 is ready for RC testing. Please document issues in https://github.com/phetsims/john-travoltage/issues and link to this issue.  The primary purpose of this release is adding sound to the sim, so that should be the primary focus of the testing.  The last release of this sim was on 8/15/2018, but the branch it was from (i.e. the 1.3 branch) was created in May of 2017, so the sim has picked up a lot of common code updates since its last publication.  The sonification work was pretty concentrated, and is unlikely to have messed up anything major, so I suspect that you can probably limit things like string testing to the major platforms.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test sound generation on all supported platforms
- Test all possible forms of input.
- Test all mouse/trackpad inputs.
- Test all touchscreen inputs.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>

The primary focus, as mentioned above, should be on testing sound generation.

One important note: By default, the sound generation is set to the "basic" level.  The "enhanced" level can be turned on through the PhET menu.  The only difference is that in "enhanced" mode, there is a popping sound produced as electrons enter and leave the body.  Both modes should be tested on every platform (which should be very quick).

On IE, sound should not occur at all, and the sound button should not be visible on the nav bar.  There is an issue in the list below about this, but I wanted to make it clear that this is the intended behavior.

Also, there is a new query parameter named 'sound'.  There is an issue on the list below about it.  The bottom line is that we need to make sure that it works as expected.

<h3>Issues to Verify</h3>

- [x] [Label for global mute sound button needs changing/adjusting](https://github.com/phetsims/john-travoltage/issues/300)
- [x] [Add support for a 'sound' query parameter](https://github.com/phetsims/tambo/issues/47)
- [x] [Gaps or glitches in loops on different platforms](https://github.com/phetsims/tambo/issues/35) - test this by listening closely to the sound that is produced continuously when there are charges in the body, and make sure that it has no obvious gaps or clicks.
- [ ] [Prevent appearance of sound control nav bar button on IE](https://github.com/phetsims/tambo/issues/32)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.1/phet/john-travoltage_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.1/phet/john-travoltage_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.1/phet/xhtml/john-travoltage_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1weqPMQfVBHX_IDtLTcu-EyrFamRaH7xtjFkdELS2Tfg/edit#gid=1004721749)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Focus and Special Instructions</h3>

Test keyboard nav and interaction.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.1/phet/john-travoltage_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.1/phet/john-travoltage_en_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1weqPMQfVBHX_IDtLTcu-EyrFamRaH7xtjFkdELS2Tfg/edit#gid=1004721749)**

<h3>Screen Readers</h3>

This sim supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to screen readers. If you simply need a refresher on screen readers, please consult the [QA Book](link), which should have all of the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [x] Windows 10 + Latest Firefox + Latest JAWS
- [x] Windows 10 + Latest Firefox + Latest NVDA
- [x] macOS + Safari + VoiceOver

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in [this Google Document](https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/). If you find a screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a screen reader.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
@jbphet QA is done.  Could not test the IE issue due to bug above.

**Comment by jbphet** [comment]
Thanks @KatieWoe.  I'll address the issues and roll a new RC.  Closing.
