### ISSUE TITLE
RC Spot Check: States of Matter 1.1.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#205]
@KatieWoe and @ariel-phet, States of Matter 1.1.0-rc.2 is ready for RC testing. Testing on 1.1.0-rc.1 was [completed](https://github.com/phetsims/QA/issues/185), several issues have been addressed, and this is the follow up test.  For the most part, a full test on all platforms is not necessary, just a verification of the issues and spot testing on key platforms.  See the list of issues below for guidance on what should be tested.

Please document any issues found in https://github.com/phetsims/states-of-matter/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

Versus the last RC, the only changes are related to the issues listed below, so that can be the focus of the testing.  Having said that, this is a very popular sim, so enough testing should be done to make sure that this particular release is stable enough to replace the currently published version.

<h3>Issues to Verify</h3>

- [x] [Neon and Argon on Interaction short when stringTest=long](https://github.com/phetsims/states-of-matter/issues/228)
- [x] [Why did the HearterCoolerNode get smaller?](https://github.com/phetsims/states-of-matter/issues/224)
- [x] [Thermometer resets tilted on states screen](https://github.com/phetsims/states-of-matter/issues/223)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and change their status to fixed-awaiting-deploy if resolved. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.2/phet/states-of-matter_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.2/phet/states-of-matter_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.2/phet/xhtml/states-of-matter_all_phet.html)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fstates-of-matter%2F1.1.0-rc.2%2Fphet%2Fstates-of-matter_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jbphet** [comment]
List looks good to me.

**Comment by ariel-phet** [comment]
Current top testing priority

**Comment by lmulhall-phet** [comment]
QA is done.

**Comment by KatieWoe** [comment]
Assigning @ariel-phet since @jbphet is gone right now.

**Comment by jbphet** [comment]
Thanks for the testing, I'll follow up on the issues.  Closing.
