### ISSUE TITLE
RC Spot Check: John Travoltage 1.5.0-rc.3

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#208]
@KatieWoe and @ariel-phet, John Travoltage 1.5.0-rc.3 is ready for RC testing. Testing on 1.5.0-rc.2 was [completed](https://github.com/phetsims/QA/issues/200), and some a11y related issues were addressed as a result.  Only small changes were made since the previous rounds of testing, so I think verification of the issues listed below coupled with a quick spot check on key platforms should be sufficient.

Please document any issues in https://github.com/phetsims/john-travoltage/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Two of the issues addressed by this RC are related to screen readers (but they are kind of the same issue), so some testing with screen readers will be necessary.
- One of the issues addressed by this RC was specific to Internet Explorer, so some testing on that platform will be necessary.
- The addition of sound was the primary purpose of the 1.5 release.  While nothing has changed with respect to sound for this RC, it's still good to pay close attention to it.

<h3>Issues to Verify</h3>

- [x] [Jaws performance and reading alerts](https://github.com/phetsims/john-travoltage/issues/310)
- [x] [JAWS and NVDA alerts read late](https://github.com/phetsims/john-travoltage/issues/315)
- [x] [Sim won't behave properly after keyboard nav in full screen IE](https://github.com/phetsims/john-travoltage/issues/317)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and change their status to fixed-awaiting-deploy if resolved. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.3/phet/john-travoltage_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.3/phet/john-travoltage_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.3/phet/xhtml/john-travoltage_all_phet.html)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fjohn-travoltage%2F1.5.0-rc.3%2Fphet%2Fjohn-travoltage_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Devices to Test On (@jbphet  let me know if you have any changes you want):
---
- [ ] Win 10 Chrome Full
- [ ] Win 10 Edge Full
- [ ] Win 10 Firefox Full
---
- [ ] Mac OS 10.14 Chrome Partial
- [ ] Mac OS 10.14 Safari Full
- [ ] Mac OS 10.14 Firefox Partial
---
- [ ] Win 8.1 IE Full
- [ ] Win 8.1 chrome Partial
- [ ] Win 7 IE Partial
---
- [ ] Mac OS 10.13 Firefox Partial
- [ ] Mac OS 10.13 Safari Partial
---
- [ ] Chrome OS Partial
---
- [ ] iOS 12 Full
- [ ] iOS 11 Partial

**Comment by KatieWoe** [comment]
QA is Done

**Comment by jbphet** [comment]
Thanks @KatieWoe and team - I will move forward with publication. Closing.
