### ISSUE TITLE
RC Spot Check: States of Matter 1.1.0-rc.3

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#212]
@KatieWoe and @ariel-phet, States of Matter 1.1.0-rc.3 is ready for RC testing. Testing on 1.1.0-rc.1 and 110-rc.2 has already been done, and was quite thorough, and this is the follow up test.  A full test on all platforms is not necessary, just verification of the resolved issues and spot testing on key platforms.  See the list of issues below for guidance on what should be tested.

Please document any issues found in https://github.com/phetsims/states-of-matter/issues and link to this issue.

Assigning @KatieWoe.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

Versus the last RC, the only changes are related to the issues listed below, so that can be the focus of the testing.  Having said that, this is a very popular sim, so enough testing should be done to make sure that this particular release is stable enough to replace the currently published version.

<h3>Issues to Verify</h3>

- [x] [NaN for temperature reading when molecules added to empty container](https://github.com/phetsims/states-of-matter/issues/234)
- [x] [Phase diagram doesn't change for water](https://github.com/phetsims/states-of-matter/issues/233)
- [x] [Maintenance Release to remove Full Screen button from iPad iOS 12](https://github.com/phetsims/joist/issues/525)

The SOM-specific issues should have the "status:fixed-pending-testing" label. Check these issues off and change their status to fixed-awaiting-deploy if resolved. Otherwise, post a comment in the issue saying that it wasn't fixed.  

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.3/phet/states-of-matter_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.3/phet/states-of-matter_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.3/phet/xhtml/states-of-matter_all_phet.html)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fstates-of-matter%2F1.1.0-rc.3%2Fphet%2Fstates-of-matter_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
@jbphet let me know if this list works for you.  Anything not marked full is a partial test.

- [ ] Win 10 chrome Full
- [ ] Win 10 firefox
- [ ] Win 10 edge Full
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox Full
- [ ] Mac 10.14 safari Full
---
- [ ] iOS 12 Full
---
- [ ] Chrome OS
---
- [ ] Win 7 IE
- [ ] Mac 10.11 safari

**Comment by KatieWoe** [comment]
@ariel-phet for priority

**Comment by KatieWoe** [comment]
Edge performance is poor.  Issue is present in published version.

**Comment by KatieWoe** [comment]
QA is done @jbphet

**Comment by jbphet** [comment]
Thanks QA team!  I'll take it from here, closing.
