### ISSUE TITLE
RC test: Coulomb's Law 1.0.0-rc.4

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#214]
@KatieWoe, @arouinfar, @jessegreenberg,  coulombs-law/1.0.0-rc.4 is ready for RC testing. Document issues in https://github.com/phetsims/coulombs-law/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Issues to Verify</h3>

- [x] [Keyboard nav focus gets lost in iFrame #74](https://github.com/phetsims/coulombs-law/issues/74)
- [x] [Navigation bar icons look bad in Firefox #75](https://github.com/phetsims/coulombs-law/issues/75)
- [x] [Keyboard Navigation Dialog #58](https://github.com/phetsims/coulombs-law/issues/58) 

NOTE: keyboard dialog issue has been closed, but I thought it'd be useful to confirm.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/xhtml/coulombs-law_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/17BEdTv1KM1Tq6kyi3fxo15znqRH6iw8pyc4axE47eeM/edit#gid=1380557997)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - ~~Test all forms of input with a screen reader (if applicable).~~

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html)**
- **[Test Matrix](link)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a screen reader.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe top testing priority for the moment

Mentioning @rea-laura @phet-steele @JRomero0613 @lmulhall-phet  since Katie is at a conference

**Comment by JRomero0613** [comment]
The test matrix link provided does not direct to the test matrix and instead directs to a blank github page. Could a new link be provided so testing progress can be updated?

**Comment by lmulhall-phet** [comment]
I’ll make a matrix in a second! Sorry about that, @jromero0613.

**Comment by lmulhall-phet** [comment]
Link should be working now.

**Comment by KatieWoe** [comment]
QA is done.

**Comment by KatieWoe** [comment]
Sorry, @mbarlow12, noticed one last thing.  Apparently the pointer areas for the reset button for touch should be larger.  https://github.com/phetsims/friction/issues/65

**Comment by mbarlow12** [comment]
Only issues remaining after above commits are:
https://github.com/phetsims/scenery/issues/890
and
https://github.com/phetsims/scenery/issues/883

**Comment by mbarlow12** [comment]
Closing. New RC issue at https://github.com/phetsims/QA/issues/221
