### ISSUE TITLE
RC test: Coulomb's Law 1.0.0-rc.5

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#221]
@KatieWoe, @arouinfar, @jessegreenberg, coulombs-law/1.0.0-rc.5 is ready for a final spot RC check. Document issues in https://github.com/phetsims/coulombs-law/issues and link to this issue.

The latest round of issues were pretty minor, so I think just briefly checking major browsers/platforms should be sufficient.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Complete the test matrix.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Issues to Verify</h3>

- [x] [Zero times ten to the first power](https://github.com/phetsims/coulombs-law/issues/77)
- [ ] [Pointer Areas on ruler a bit large](https://github.com/phetsims/coulombs-law/issues/80)
- [x] [Basic Actions Items in Keyboard Nav](https://github.com/phetsims/coulombs-law/issues/81)

Though it's closed, @KatieWoe mentioned in https://github.com/phetsims/QA/issues/214#issuecomment-436750700 about the ResetAll button pointer area.

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/xhtml/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Since this is a spot check, per @mbarlow12 there is not a test matrix.  Please do a full rc test on platforms marked full, and about half of the normal tests, including testing all issues, for platforms marked partial.  @mbarlow12 let me know if this list works for you.
---
- [ ] Win 10 chrome full
- [ ] Win 10 firefox partial
- [ ] Win 10 edge full
---
- [ ] Mac 10.14 chrome partial
- [ ] Mac 10.14 firefox full
- [ ] Mac 10.14 safari full
---
- [ ] iOS 12 full
- [ ] iOS 11 partial
---
- [ ] chrome os partial
---
- [ ] Win 7 IE full
- [ ] Win 7 chrome partial
- [ ] Mac 10.12 safari partial
- [ ] Mac 10.12 firefox partial

**Comment by mbarlow12** [comment]
@KatieWoe this looks excellent. Thank you.

**Comment by KatieWoe** [comment]
Here are the results of a memory test
Start: 27.4
1 min: 35.4
2 min: 36.5
3 min: 37.1
4 min: 37.3
5 min: 37.4
6 min: 37.7
7 min: 37.8
8 min: 38
9 min: 38.2
10 min: 38.3
20 min: 39
30 min: 39.4
40 min: 39.5
50 min: 39.6
60 min: 39.7

**Comment by ariel-phet** [comment]
Moving to high priority to be finished off

**Comment by KatieWoe** [comment]
Issue for keyboard nav that was encountered on Edge in the XHTML version but was unable to replicate.  The figure on the right in Macro Scale was unable to move to the left past a certain point.  I had been in full screen before, the charge of the figure in question was 0, and the point it stopped was a bit to the right of the the middle of the screen.  Dragging by mouse was not effected.  Unfortunately, I haven't been able to replicate. @jessegreenberg and @mbarlow12 I didn't make an issue since have so little information, but I'm documenting here.  Let me know if you want a separate issue made.

**Comment by KatieWoe** [comment]
QA is done

**Comment by mbarlow12** [comment]
New RC issue at https://github.com/phetsims/QA/issues/235.
