### ISSUE TITLE
RC test: Graphing Quadratics 1.0.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#233]
@KatieWoe, @ariel-phet, @amanda-phet, Graphing Quadratics 1.0.0-rc.2 is ready for RC testing. 

This RC is for `brand=phet` only (no phet-io, no a11y), and will _not_ be shared with a client.

Please document issues in https://github.com/phetsims/graphing-quadratics/issues and link to this issue.  

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.

<h3>Focus and Special Instructions</h3>

Read the [Terminology section of implementation-notes.md](https://github.com/phetsims/graphing-quadratics/blob/master/doc/implementation-notes.md#terminology), and try to use that terminology is issues.  You may also wish to read the model description in [model.md](https://github.com/phetsims/graphing-quadratics/blob/master/doc/model.md).

Sim-specific query parameters are in [GQQueryParameters](https://github.com/phetsims/graphing-quadratics/blob/master/js/common/GQQueryParameters.js), but none of them are intended for QA/testing.

<h3>Issues to Verify</h3>

Please verify issues that are related to the [1.0.0-rc.1 QA issue](https://github.com/phetsims/QA/issues/227):

- [x] [prevent overlap of vertex coordinates and 'NO REAL ROOTS'](https://github.com/phetsims/graphing-quadratics/issues/88)
- [x] [Improve drag behavior of "Point on Parabola"](https://github.com/phetsims/graphing-quadratics/issues/117)
- [x] [Coordinate labels get off-center with their associated point](https://github.com/phetsims/graphing-quadratics/issues/118)
- [x] [[iOS9] crashes at startup](https://github.com/phetsims/graphing-quadratics/issues/119)
- [x] [dev bounds issues](https://github.com/phetsims/graphing-quadratics/issues/121)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation]( https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.2/phet/graphing-quadratics_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.2/phet/graphing-quadratics_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.2/phet/xhtml/graphing-quadratics_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/178AxwmvOyQXFRqCYWnLGsbDiZFDsfLagE2T7cnJn8Dc/edit#gid=53614679)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by pixelzoom** [comment]
@KatieWoe @ariel-phet The issues that were fixed (identified in "Issues to Verify" above) were all very isolated changes, typically involving a couple of lines of code in a couple of files. So I'm confident that no new problems have crept in as the result of these changes, and I'd be comfortable just doing a "spot check" of those specific issues (vs a full test matrix on all platforms).  Of course it's your call on how to test this RC, but that's my 2 cents.

**Comment by KatieWoe** [comment]
I'm ok with that @pixelzoom.  Let me know how this list looks to you.
- [ ] Win 10 chrome Full
- [ ] Win 10 firefox
- [ ] Win 10 edge Full
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox Full
- [ ] Mac 10.14 safari Full
---
- [ ] iOS 12 Full
---
- [ ] Chrome OS
---
- [ ] Win 7 IE Full
- [ ] Win 7 chrome
- [ ] Mac 10.11 safari
- [ ] Mac 10.11 firefox

**Comment by pixelzoom** [comment]
You'll need to add iOS9 to the list, for testing phetsims/graphing-quadratics#119.

**Comment by KatieWoe** [comment]
Thanks for the reminder.

**Comment by KatieWoe** [comment]
QA is done.  The iOS 12 device is unavailable until Monday.  iOS 11 was tested instead.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe and test team!  I have a couple of issues to address, then I'll proceed with creating 1.0.0-rc.3.

**Comment by pixelzoom** [comment]
1.0.0-rc.3 has been created, closing.
