### ISSUE TITLE
RC test: Coulomb's Law 1.0.0-rc.6

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#235]
Round 6!!!

@KatieWoe, @arouinfar, @jessegreenberg, @ariel-phet  coulombs-law/1.0.0-rc.6 is ready for a final spot RC check. Document issues in https://github.com/phetsims/coulombs-law/issues and link to this issue.

The latest round of issues were pretty minor, so I think just briefly checking major browsers/platforms should be sufficient.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Complete the test matrix.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Issues to Verify</h3>

- [x] [Boxes overlab](https://github.com/phetsims/coulombs-law/issues/83)
- [x] [**Text goes off screen**](https://github.com/phetsims/coulombs-law/issues/84)
- [x] [Figure won't move past a point](https://github.com/phetsims/coulombs-law/issues/86)
- [x] [Update color of dashed lines](https://github.com/phetsims/coulombs-law/issues/87)
- [x] [**Dilate touch areas on charge NumberControls**](https://github.com/phetsims/coulombs-law/issues/89)
- [x] [Charges jump when keyboard nav is used](https://github.com/phetsims/coulombs-law/issues/90)
- [x] [Ruler pointer area gets left behind when ruler is moved](https://github.com/phetsims/coulombs-law/issues/91)

Note that [Legends of Learning page freeze](https://github.com/phetsims/joist/issues/540) hasn't been addressed, but we may publish this sim without a fix— @ariel-phet will make the call.

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.6/phet/coulombs-law_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.6/phet/coulombs-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.6/phet/xhtml/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**
- **[Legends of Learning Harness]()**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.6/phet/coulombs-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.6/phet/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
@mbarlow12 how does this list look for platforms?
- [ ] Win 10 chrome Full
- [ ] Win 10 firefox
- [ ] Win 10 edge Full
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox Full
- [ ] Mac 10.14 safari Full
---
- [ ] iOS 12 Full
- [ ] iOS  10
---
- [ ] Chrome OS
---
- [ ] Win 7 IE Full
- [ ] Win 7 chrome
- [ ] Mac 10.11 safari
- [ ] Mac 10.11 firefox

**Comment by ariel-phet** [comment]
@KatieWoe Graphing Quadratics and this sim are on similar priority level

**Comment by KatieWoe** [comment]
On iOS 10 the sim froze and crashed fairly quickly.  This also seemed to happen in graphing quadratics, but it was determined to be an issue with the device, which may be the case here.  I reset the device and will see if that improves the situation. @mbarlow12

**Comment by KatieWoe** [comment]
Reset device and it seemed better, but crash still occurred after 10 minutes.

**Comment by KatieWoe** [comment]
QA is done @mbarlow12

**Comment by mbarlow12** [comment]
New RC issue in https://github.com/phetsims/QA/issues/242

**Comment by KatieWoe** [comment]
Closing for new RC https://github.com/phetsims/QA/issues/243
