### ISSUE TITLE
RC Test: Resistance in a Wire 1.6.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#239]
@ariel-phet, @emily-phet, @terracoda, @KatieWoe - Resistance in a Wire 1.6.0-rc.2 is ready for RC testing. This release addresses a number of issues found during the testing of 1.6.0-rc.1.  There are enough changes that were made as the result of addressing issues that a fairly thorough retest is required.  There were some issues which could not be fully addressed, these are noted below.

Please document issues in https://github.com/phetsims/resistance-in-a-wire/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>

Special focus should be given to accessibility features, such as screen reader behavior, sonification, and keyboard navigation.

<h3>Issues to Verify</h3>

- [x] [Test for memory leaks prior to starting 1.6 release process](https://github.com/phetsims/resistance-in-a-wire/issues/184)
- [x] [Rho symbol does not translate](https://github.com/phetsims/resistance-in-a-wire/issues/187)
- [x] [Jaws reads out incorrect values in scene summary](https://github.com/phetsims/resistance-in-a-wire/issues/189)
- [x] [Sound disappears sometimes in Full-Screen Mode](https://github.com/phetsims/resistance-in-a-wire/issues/190)
- [x] [Reset All Pointer Area](https://github.com/phetsims/resistance-in-a-wire/issues/192)
- [ ] [VoiceOver reads out multiple resistance values after sliders stop being adjusted](https://github.com/phetsims/resistance-in-a-wire/issues/193)
- [x] [Clicking out of keyboard nav moves sliders Edge](https://github.com/phetsims/resistance-in-a-wire/issues/196)
- [x] [Static and significant performance issues](https://github.com/phetsims/resistance-in-a-wire/issues/198)
- [ ] [Sound Disappears when two tabs are open in landscape](https://github.com/phetsims/resistance-in-a-wire/issues/199)

Most of these issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. The issues that do **not** have this label should be updated with the status of the issue, i.e. how this particular release behaves with respect to the issue.  We will ultimately decide whether to go forward with the release with these issues not fully resolved.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.2/phet/resistance-in-a-wire_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.2/phet/resistance-in-a-wire_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.2/phet/xhtml/resistance-in-a-wire_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1qNs8hbWvo19YKgn1ds_Y1AuV8N8k9tneGWaRB9N4plE/edit#gid=2064347589)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fresistance-in-a-wire%2F1.6.0-rc.1%2Fphet%2Fresistance-in-a-wire_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Focus and Special Instructions</h3>

Sonification is brand new, so should be tested well.  Screen reader support was tested on the 1.5 release branch, but never actually released, so it should be tested reasonably well too. 

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.1/phet/resistance-in-a-wire_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.1/phet/resistance-in-a-wire_en_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1qNs8hbWvo19YKgn1ds_Y1AuV8N8k9tneGWaRB9N4plE/edit#gid=2064347589)**

<h3>Screen Readers</h3>

This sim supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to screen readers. If you simply need a refresher on screen readers, please consult the [QA Book](link), which should have all of the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [ ] Windows 10 + Latest Chrome + Latest JAWS
- [ ] Windows 10 + Latest Firefox + Latest NVDA
- [ ] macOS + Safari + VoiceOver

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in [this Google Document](https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/). If you find a screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a screen reader.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory test results
Start: 1.56 MB
1 min: 22.4 MB
2 min: 24.0 MB
3 min: 25.3 MB
4 min: 26.4 MB
5 min: 27.3 MB
6 min: 28.0 MB
7 min: 28.8 MB
8 min: 29.6 MB
9 min: 30.4 MB
10 min: 31.1 MB
20 min: 37.8 MB
30 min: 44.0 MB
60 min: 61.6 MB

**Comment by terracoda** [comment]
@KatieWoe, the memory test results seem to suggest that we have a problem, such as a memory leak. 
What's the desired upper limit of usage? RIAW is a simple simulation.

**Comment by KatieWoe** [comment]
@terracoda that's more a question for @jbphet.  I'm not sure what the upper level would be, but I do agree that it's concerning that it doesn't level off.

**Comment by jbphet** [comment]
@KatieWoe - the start value in your memory test above seems suspiciously low (1.56 MB).  Can you double check this?  I just did a test and found it initially at 17.0 MB on my system.

@terracoda - we don't have a hard number for the max memory usage, but we've seen cases where anything over 100 MB crashes sims.  I'll take a look at this and see if I can see why there is growth, but if a sim is under 100 MB after 60 minutes of fuzz testing (which is *far* more input events than we'd ever see from a user), it's not much of a concern.

**Comment by KatieWoe** [comment]
@jbphet I put the decimal in the wrong place.

**Comment by ariel-phet** [comment]
bumping to current top testing priority

**Comment by jbphet** [comment]
I redid some memory testing to compare to what was reported above, and though I see some slow memory leakage, none of the leaked components are sim-specific.  This makes me think that it is likely due to pool allocations in scenery.  Since the sim withstood 60 min of fuzz testing without exceeding 100 MB, and was less than 30 MB at 5 minutes, I don't think this is worth investing more time in.  Here is a screenshot of the comparison showing the difference after a few minutes of fuzz testing:

![image](https://user-images.githubusercontent.com/3082831/50497285-618f6080-09f3-11e9-9190-160886f50c21.png)

I'll address the other issue linked above separately.  Thanks for the testing @KatieWoe and team.  Closing.
