### ISSUE TITLE
Dev Test: Ohms Law 1.4.0-phetiodev.2

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#24]
@emily-phet 

This a test for the newly phet-io instrumented sim, as well as major refactoring and layout changes since the [1.4.0-phetiodev.1 dev test](https://github.com/phetsims/QA/issues/18).

http://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-phetiodev.2/wrappers/index/

Please check that these issues are solved:

- [x] Screen layout is scaled way too high phetsims/ohms-law#62
- [x] batterText typo phetsims/ohms-law#63
- [x] Fails to "Launch" from Instance Proxies phetsims/ohms-law#64
- [x] Instrument for PhET-iO phetsims/ohms-law#50

As well as other potentially suitable tests that QA wizards tend to do.

In an email @emily-phet told me:
> Ideally at least OL would be done by Tuesday July 25th (maybe RIAW, too?). 

This is to be used for sonification wrapper work.

@ariel-phet please assign and prioritize

**Comment by zepumph** [comment]
From https://github.com/phetsims/QA/issues/19, I think this should be the type of dev test that can be delivered to Georgia Tech since there is a potential deadline for next week. I think that makes the most sense since there have been many changes to this sim, and QA may find a lot. I don't want to put extra stain by sending it to RC as well if we are really trying to get it out by next week.

**Comment by phet-steele** [comment]
@zepumph, aside from the issues above, this version appears to be working.

**Comment by zepumph** [comment]
Thanks @phet-steele.
