### ISSUE TITLE
RC test: Coulomb's Law 1.0.0-rc.8

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#243]
After a minor big was introduced in RC 7, I released the updated version. Below is a copy from the [previous issue](https://github.com/phetsims/QA/issues/2420).

@KatieWoe, @arouinfar, @jessegreenberg, @ariel-phet  coulombs-law/1.0.0-rc.8 is ready for a final spot RC check. Document issues in https://github.com/phetsims/coulombs-law/issues and link to this issue.

There are a few issues discovered from the last RC that won't be addressed prior to this publication. They are noted below.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Complete the test matrix.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Issues to Verify</h3>

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

- [ ] [**Text goes off screen**](https://github.com/phetsims/coulombs-law/issues/84)
- [x] [**Dilate touch areas on charge NumberControls**](https://github.com/phetsims/coulombs-law/issues/89)
- [x] [**Forces are not equal and opposite**](https://github.com/phetsims/coulombs-law/issues/97)

iOS crashing is apparently no longer an issue, but we should still check to ensure it doesn't arise again.
- [ ] [Crash on iOS 10](https://github.com/phetsims/coulombs-law/issues/96)

The following issues won't be addressed prior to publication.
- [Legends of Learning page freeze](https://github.com/phetsims/joist/issues/540)
- [Moving one charge can move the other charge](https://github.com/phetsims/coulombs-law/issues/93)
  - inconsistently appears and is possibly a FF-specific issue
- [Jumpy distortion on Firefox while resizing window](https://github.com/phetsims/scenery/issues/905)
  - appears to be another FF bug
- [Keyboard Nav Issues](https://github.com/phetsims/coulombs-law/issues/94)
  - issues witnessed are actually desired/standard behavior

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.8/phet/coulombs-law_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.8/phet/coulombs-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.8/phet/xhtml/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**
- **[Legends of Learning Harness]()**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.8/phet/coulombs-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.8/phet/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome Full
- [ ] Win 10 firefox
- [ ] Win 10 edge Full
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox Full
- [ ] Mac 10.14 safari Full
---
- [ ] iOS 12 Full
- [ ] iOS  10
---
- [ ] Chrome OS
---
- [ ] Win 7 IE Full
- [ ] Win 7 chrome
- [ ] Mac 10.11 safari
- [ ] Mac 10.11 firefox

**Comment by KatieWoe** [comment]
Keyboard nav seems to behave a bit oddly if you start in after manipulating one of the charge sliders.  I'm in firefox, but chrome was being a bit odd too.  I don't think its broken, but you might want to take a look for yourself.  It takes two key presses to start in firefox, and it starts in an unexpected location. 
 But it doesn't do this if you were manipulating anything but those sliders.  Chrome does something similar, but it starts at the beginning after manipulating the sliders.  Not sure if this is issue worthy.  Let me know.

**Comment by KatieWoe** [comment]
I'll put it in an issue.
