### ISSUE TITLE
RC test: Coulomb's Law 1.0.0-rc.9

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#246]
Final spot check, hopefully.

@KatieWoe, @arouinfar, @jessegreenberg, @ariel-phet  coulombs-law/1.0.0-rc.9 is ready for a final spot RC check. Document issues in https://github.com/phetsims/coulombs-law/issues and link to this issue.

There are a few issues discovered from the last RC that won't be addressed prior to this publication. They are noted below.

Assigning @ariel-phet for prioritization & QA team (this will hopefully be a quick check).

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Complete the test matrix.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Issues to Verify</h3>

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

- [x] [**Text goes off screen**](https://github.com/phetsims/coulombs-law/issues/84)
- [x] [Force Values should display a magnitude](https://github.com/phetsims/coulombs-law/issues/101)
- [x] [[Atomic Scale] Use MathSymbols.TIMES in scale bar readout](https://github.com/phetsims/coulombs-law/issues/99)
- [x] [Keyboard nav issue when starting after charge slider](https://github.com/phetsims/coulombs-law/issues/100)

iOS crashing is apparently no longer an issue, but we should still check to ensure it doesn't arise again.
- [x] [Crash on iOS 10](https://github.com/phetsims/coulombs-law/issues/96)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.9/phet/coulombs-law_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.9/phet/coulombs-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.9/phet/xhtml/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**
- **[Legends of Learning Harness]()**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.9/phet/coulombs-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.9/phet/coulombs-law_all_phet.html)**
- **[Test Matrix](link)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by lmulhall-phet** [comment]
- [ ] Win10 Chrome
- [ ] Win10 FF
- [ ] Win10 Edge
- [ ] Mac 10.14 Chrome
- [ ] Mac 10.14 FF
- [ ] Mac 10.14 Safari
- [ ] iOS 12
- [ ] iOS 10
- [ ] Chrome OS
- [ ] Win 7 IE
- [ ] Win 7 Chrome
- [ ] Mac 10.11 Safari
- [ ] Mac 10.11 FF

**Comment by lmulhall-phet** [comment]
Looks good @mbarlow12!

**Comment by kathy-phet** [comment]
Thanks, @lmulhall-phet !
