### ISSUE TITLE
RC Test: Resistance in a Wire 1.6.0-rc.3

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#247]
@ariel-phet, @emily-phet, @terracoda, @KatieWoe - Resistance in a Wire 1.6.0-rc.3 is ready for RC testing. This release addresses the handful of issues found during the testing of 1.6.0-rc.1.  The issues are listed below, and in my opinion it will be enough to verify them and to spot check the sim on a few key platforms, since the changes for this release were minimal.

Please document issues in https://github.com/phetsims/resistance-in-a-wire/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>

Special focus should be given to accessibility features, such as screen reader behavior, sonification, and keyboard navigation.

<h3>Issues to Verify</h3>

- [ ] [VoiceOver reads out multiple resistance values after sliders stop being adjusted](https://github.com/phetsims/resistance-in-a-wire/issues/193)
- [ ] [Max width of keyboardNav dialog](https://github.com/phetsims/resistance-in-a-wire/issues/203)
- [ ] [Sound blurs when dragging starts off of thumb](https://github.com/phetsims/resistance-in-a-wire/issues/204)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. 

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.3/phet/resistance-in-a-wire_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.3/phet/resistance-in-a-wire_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.3/phet/xhtml/resistance-in-a-wire_all_phet.html)**
- **[Test Matrix (TDB)](xxx)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fresistance-in-a-wire%2F1.6.0-rc.3%2Fphet%2Fresistance-in-a-wire_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Focus and Special Instructions</h3>

Sonification is brand new, so should be tested well.  Screen reader support was tested on the 1.5 release branch, but never actually released, so it should be tested reasonably well too. 

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.1/phet/resistance-in-a-wire_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.1/phet/resistance-in-a-wire_en_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1qNs8hbWvo19YKgn1ds_Y1AuV8N8k9tneGWaRB9N4plE/edit#gid=2064347589)**

<h3>Screen Readers</h3>

This sim supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to screen readers. If you simply need a refresher on screen readers, please consult the [QA Book](link), which should have all of the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [ ] Windows 10 + Latest Chrome + Latest JAWS
- [ ] Windows 10 + Latest Firefox + Latest NVDA
- [ ] macOS + Safari + VoiceOver

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in [this Google Document](https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/). If you find a screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a screen reader.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
@ariel-phet for priority

**Comment by ariel-phet** [comment]
@KatieWoe top priority along with Friction

**Comment by KatieWoe** [comment]
QA is done
