### ISSUE TITLE
RC test: Graphing Lines 1.3.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#277]
@KatieWoe , @ariel-phet , @amanda-phet graphing-lines/1.3.0-rc.1 is ready for RC testing. This is a `brand=phet` release only (no PhET-iO, no a11y). 

Document issues in https://github.com/phetsims/graphing-lines/issues and link to this issue.

NOTE: For efficiency, this should be tested at the same time as Graphing Slope-Intercept 1.1.0, see #278.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.

<h3>Issues to Verify</h3>

- [x] [disable showAnswers in production versions](https://github.com/phetsims/graphing-lines/issues/67)
- [x] [prioritize active line when color-coding point tool](https://github.com/phetsims/graphing-lines/issues/89)
- [x] [use icons for "Hide lines" and "Hide grid"](https://github.com/phetsims/graphing-lines/issues/91)
- [x] [do not disable UI components when graph contents are hidden](https://github.com/phetsims/graphing-lines/issues/92)
- [x] [use standard font for math symbols](https://github.com/phetsims/graphing-lines/issues/94)
- [x] [equations are not simplified in Point-Slope scree](https://github.com/phetsims/graphing-lines/issues/97)
- [x] [Eliminate GamePhaseProperty](https://github.com/phetsims/graphing-lines/issues/109)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-rc.1/phet/graphing-lines_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-rc.1/phet/graphing-lines_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-rc.1/phet/xhtml/graphing-lines_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1J-Fb_6PLNqrygQgCjQj0tVtPovb3P0CBWPsrrz3d4Uw/edit#gid=1245567831)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory Test Results:
Start: 47.9
1 min: 60.4
2 min: 63.7
3 min: 64.6
4 min: 63.0
5 min: 64.0
6 min: 67.4
7 min: 64.1
8 min: 69.9
9 min: 66.3
10 min: 70.1

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thanks QA team! We'll need another RC, and I'll keep this issue open until I've created the corresponding issue.

**Comment by pixelzoom** [comment]
1.3.0-rc.2 has been published, see https://github.com/phetsims/QA/issues/283.
