### ISSUE TITLE
RC test: Graphing Lines 1.3.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#283]
@KatieWoe , @ariel-phet , @amanda-phet graphing-lines/1.3.0-rc.2 is ready for RC testing. This is a `brand=phet` release only (no PhET-iO, no a11y). 

Document issues in https://github.com/phetsims/graphing-lines/issues and link to this issue.

NOTE: For efficiency, this should be tested at the same time as Graphing Slope-Intercept 1.1.0-rc.2, see #284.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.

<h3>Issues to Verify</h3>

These issues must be tested for both Graphing Lines (#283) and Graphing Slope-Intercept (#284). They are all platform independent; if they work on one platform, they will work on all platforms.  So a full test matrix is unnecessary for this RC.  Spot checking on a couple of platforms is sufficient.

Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

- [x] [New best given for bad time and imperfect score](https://github.com/phetsims/graphing-lines/issues/111)
- [x] [Color in point tool turns black when problem is solved](https://github.com/phetsims/graphing-lines/issues/112)
- [x] [update icons for game levels](https://github.com/phetsims/graphing-lines/issues/113)
- [x] [Slope writing is inconsistent size ](https://github.com/phetsims/graphing-lines/issues/114)
- [x] [Green line layered over black point](https://github.com/phetsims/graphing-lines/issues/115)
- [ ] [Short max widths for game answers](https://github.com/phetsims/graphing-lines/issues/117)
- [ ] [Pink shadow stays behind when manipulator is moved](https://github.com/phetsims/graphing-lines/issues/119)
- [ ] [Active line label overlaps...](https://github.com/phetsims/graphing-lines/issues/120)
- [x] [Layering saved line under/over green lines](https://github.com/phetsims/graphing-lines/issues/121)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-rc.2/phet/graphing-lines_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-rc.2/phet/graphing-lines_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/graphing-lines/1.3.0-rc.2/phet/xhtml/graphing-lines_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1J-Fb_6PLNqrygQgCjQj0tVtPovb3P0CBWPsrrz3d4Uw/edit#gid=34592960)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe current top priority

**Comment by pixelzoom** [comment]
I forgot to cherry-pick fixes for phet-sims/graphing-lines#119 and  phet-sims/graphing-lines#120 into the 1.3 branch.  And @KatieWoe found another corner case with #117, which I've addressed.  But we will need a quick 1.3.0-rc.3.

**Comment by KatieWoe** [comment]
This is going to be continued in RC3.

**Comment by pixelzoom** [comment]
1.3.0-rc.3 has been published in https://github.com/phetsims/QA/issues/286.
