### ISSUE TITLE
RC test: Masses and Springs Basics 1.0.0-rc.3

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#296]
@ariel-phet , @arouinfar , Masses-and-Springs-Basics/1.0.0-rc.3 is ready for RC testing. Document issues in https://github.com/phetsims/Masses-and-Springs-Basics/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version

<h3>Issues to Verify</h3>

- [x] [GravityAccordionBox requires model](https://github.com/phetsims/masses-and-springs-basics/issues/64)
         -Please toggle through gravity settings to ensure sim isn't crashing.
- [x] [Gravity maxWidth is too small](https://github.com/phetsims/masses-and-springs-basics/issues/63)
- [x] [[Lab Screen] Movable Line position doesn't reset on ResetAll](https://github.com/phetsims/masses-and-springs-basics/issues/61)
- [x] [Pointer Area Overlap of mass adjuster](https://github.com/phetsims/masses-and-springs-basics/issues/60)
- [x] [Short Strings are centered](https://github.com/phetsims/masses-and-springs-basics/issues/59)
- [x] [Period Trace stops after it is complete when stepping through animation](https://github.com/phetsims/masses-and-springs-basics/issues/58)
- [x] [[Stretch Screen] ruler returns home when window dimensions change](https://github.com/phetsims/masses-and-springs-basics/issues/57)
- [x] [Add Credits](https://github.com/phetsims/masses-and-springs-basics/issues/31)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.3/phet/masses-and-springs-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.3/phet/masses-and-springs-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.3/phet/xhtml/masses-and-springs-basics_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/10S3RzdeJ0O3W98OIMsfGLtRtxF-gLpTarxm0JTXyd34/edit#gid=910158522)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jonathanolson** [comment]
This release branch had patches related to https://github.com/phetsims/chipper/issues/720 and https://github.com/phetsims/brand/issues/34 applied since the last RC. This sim should have another RC done, if only to test the brand-related changes briefly.

**Comment by KatieWoe** [comment]
QA is done

**Comment by Denz1994** [comment]
Once brands-related changes are completed from https://github.com/phetsims/QA/issues/296#issuecomment-474568946, a new issue will be created in QA and that should be the last item to test for MASB before a production version. The changes ensure that older versions of sims are compatible with phetmarks.

**Comment by Denz1994** [comment]
@jonathanolson This sim had changes related to phetsims/brand#34 already included in the latest [RC](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.3/phet/masses-and-springs-basics_all_phet.html). See this [commit](https://github.com/phetsims/masses-and-springs-basics/commit/3092125768400bf4424ab53a7414ebe996920ae7).

Siding with your comment [here](https://github.com/phetsims/QA/issues/298#issuecomment-474568490), we shouldn't need QA to verify.

**Comment by Denz1994** [comment]
https://github.com/phetsims/masses-and-springs-basics/issues/31 was the last issue to verify. RC testing has concluded. Closing.
