### ISSUE TITLE
RC Test: States of Matter Basics 1.1.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#297]
@KatieWoe, @ariel-phet, and @kathy-phet - states-of-matter-basics/1.1.0-rc.2 is ready for RC testing. There was a glitch with the initial RC deployment from the 1.1 release branch, so despite the version ID, this is the first RC for the 1.1 release branch.  This deployment is being done as part of the update of all sims in the States of Matter suite, so a fair amount of this code was verified during the test cycle for States of Matter 1.1.0.  States of Matter Basics is a subset of States of Matter, so the focus of testing should probably be on making sure that nothing appears to have gone wrong in the release process and the behavior matches that of States of Matter.

Please document issues in https://github.com/phetsims/states-of-masster-basics/issues and link to this issue.  Please be sure to check the states-of-matter repo for issues before logging new ones so that we don't end up with duplicates.

Assigning @KatieWoe for prioritization since @ariel-phet is away.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>

Much of the code that comprises this sim was tested during the recent 1.1 release of the States of Matter simulation, so the focus should be to verify that the behavior matches that of States of Matter.  Also see the issues listed below.

<h3>Issues to Verify</h3>

Specifically for SOMB, please verify:

- [ ] [incorporate support for Legends of Learning](https://github.com/phetsims/states-of-matter-basics/issues/19)

Below are some issues that were fixed for SOM 1.1.  Most if not all of the linked issues are closed, but please verify them on this deployment.  If something fails, please open a new
issue and link it to the old one.

- [x] [Query parameter to start sim using Celsius](https://github.com/phetsims/states-of-matter/issues/216)
- [x] [User feedback, multiple](https://github.com/phetsims/states-of-matter/issues/214) - This issue has a bunch of things in it, so it's going to require the tester to read it, understand it, and test everything that I describe as having been addressed.  Be prepared, it will take some time.
- [x] [User reported issue: shape of liquid](https://github.com/phetsims/states-of-matter/issues/212)
- [x] ["Solid" drifts to the left on States Screen](https://github.com/phetsims/states-of-matter-basics/issues/15) - this was also reported against States of Matter Basics, but can be verified using plain States of Matter

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.1.0-rc.2/phet/states-of-matter-basics_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.1.0-rc.2/phet/states-of-matter-basics_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.1.0-rc.2/phet/xhtml/states-of-matter-basics_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1-bBeW6JcfLnAsxM4-EIeNVLn0rBcI8J1ph15_rvtT5g/edit#gid=599910889)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fstates-of-matter-basics%2F1.1.0-rc.2%2Fphet%2Fstates-of-matter-basics_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Given Priority 2 High.  Assigning to @ariel-phet to confirm when available.

**Comment by KatieWoe** [comment]
Memory Test Results:
Start: 21.2
1 min: 27.2
2 min: 29.4
3 min: 30.2
4 min: 30.5
5 min: 30.7
6 min: 31.2
7 min: 31.2
8 min: 31.3
9 min: 31.5
10 min: 31.6

**Comment by jonathanolson** [comment]
This release branch had patches related to https://github.com/phetsims/chipper/issues/720 applied since the last RC. Since this just adds a phetmarks dependency, I believe another RC wouldn't be needed since it should not significantly affect the sim (as long as it builds).

**Comment by KatieWoe** [comment]
QA is done.

**Comment by jbphet** [comment]
Thanks, I'll address the issues and go from there.  Closing.
