### ISSUE TITLE
RC test: Molecule Shapes: Basics 1.2.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#302]
@ariel-phet, @kathy-phet, @amanda-phet molecule-shapes-basics/1.2.0-rc.2 is ready for RC testing. April 1st deadline, see https://github.com/phetsims/special-ops/issues/132. Document issues in https://github.com/phetsims/molecule-shapes/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version

<h3>Issues to Verify</h3>

- [x] [Molecule in screen selection and boded atoms in model screen disappears](https://github.com/phetsims/molecule-shapes/issues/161)
- [x] [Color of Br is incorrect](https://github.com/phetsims/molecule-shapes/issues/159)
- [x] [Molecules can change other molecule's orientation](https://github.com/phetsims/molecule-shapes/issues/157)
- [x] [Win 10 Firefox Model Screen blank](https://github.com/phetsims/molecule-shapes/issues/156)
- [x] [Projector Mode max width short](https://github.com/phetsims/molecule-shapes/issues/155)
- [x] [Red X appears on bond atoms not present upon load](https://github.com/phetsims/molecule-shapes/issues/154)
- [x] [Low graphics warning](https://github.com/phetsims/molecule-shapes/issues/152)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.2/phet/molecule-shapes-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.2/phet/molecule-shapes-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.2/phet/xhtml/molecule-shapes-basics_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1unvmW2TY_gUQy2pA6vlU641qKR_DNgKFEiSOu4iSZ9M/edit#gid=772637139)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Per @kathy-phet this will be much closer to a spot check due to time constraints.

**Comment by KatieWoe** [comment]
I'm going to call this for now so that @jonathanolson has a chance to fix anything and get it confirmed.  String tests, iframe, xhtml, and LoL only tested on one platform.  All other platforms tested for usability and screenshots.  See Testing Matrix for specific tests done.

**Comment by jonathanolson** [comment]
Thanks! The issues should be fixed in https://github.com/phetsims/QA/issues/305.
