### ISSUE TITLE
Dev Test: Capacitor-Lab-Basics 1.7.0-dev.7

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#306]
@arouinfar , @ariel-phet , capacitor-lab-basics/1.7.0-dev.7 is ready for dev testing. Document issues in https://github.com/phetsims/capacitor-lab-basics/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

- [x] [Inconsistent Screen Icons](https://github.com/phetsims/capacitor-lab-basics/issues/246)
- _Check screen icons look good on tested platforms_
- [x] [User suggestion: timer and play pause](https://github.com/phetsims/capacitor-lab-basics/issues/234)
- _Check the behavior of the timer along with play/pause button_
- [ ] [**Firefox/Edge Performance Issues**](https://github.com/phetsims/capacitor-lab-basics/issues/230)
- _Note performance concerns if nessecary_
- [ ] [[iPad]**Can drag two items at the same time**](https://github.com/phetsims/capacitor-lab-basics/issues/214)
- _Check if this is still present_

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[capacitor-lab-basics](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-dev.7/phet/capacitor-lab-basics_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe putting this one at medium priority for the moment. But we would like to finish this sim off in the near'ish future as it has some enhancements we have been waiting to deploy.

**Comment by KatieWoe** [comment]
QA is done

**Comment by Denz1994** [comment]
All issues have been addressed or closed. Closing this issue. Thanks, QA.
