### ISSUE TITLE
RC Test: Isotopes and Atomic Mass 1.1.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#310]
@KatieWoe, @ariel-phet, and @arouinfar - Isotopes and Atomic Mass 1.1.0-rc.2 is ready for RC testing. This is the second RC on this branch, and addresses the issues found during the first RC.  Please document issues in https://github.com/phetsims/isotopes-and-atomic-mass/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>

The focus should be on the issues listed below, and particularly on the "Nature's Mix" behavior on the 2nd screen, since some significant modifications were made to decrease memory usage.

<h3>Issues to Verify</h3>

- [x] [Trace string has no max width](https://github.com/phetsims/isotopes-and-atomic-mass/issues/90)
- [x] [Slight pointer area overlap on Isotopes screen](https://github.com/phetsims/isotopes-and-atomic-mass/issues/89)
- [x] [Fluorine 18 and 19 should have different amu](https://github.com/phetsims/isotopes-and-atomic-mass/issues/88)
- [x] [Memory Test jumps around](https://github.com/phetsims/isotopes-and-atomic-mass/issues/86)
- [ ] [User suggestion: tritium (trace) abundance](https://github.com/phetsims/isotopes-and-atomic-mass/issues/85)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.2/phet/isotopes-and-atomic-mass_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.2/phet/isotopes-and-atomic-mass_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.2/phet/xhtml/isotopes-and-atomic-mass_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/16thsphzzvddLjJoeku-ZqrGo8vT4eTLpD8PPkDqNmyY/edit#gid=1423311662)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fisotopes-and-atomic-mass%2F1.1.0-rc.2%2Fphet%2Fisotopes-and-atomic-mass_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory test results:
Start: 26.5
1: 48.7
2: 60.4
3: 60.5
4: 61.3
5: 64.3
6: 40.8
7: 60.5
8: 62.6
9: 64.4
10: 63.9

**Comment by ariel-phet** [comment]
@KatieWoe currently high priority, as there is not too much else in the queue currently

**Comment by mattpen** [comment]
This branch was patched as part of the batch maintenance release in phetsims/chipper#746.  This should just have added a .gz file to the build artifacts.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
Thanks, I will address the logged issues individually (actually, I already have), so closing this one.
