### ISSUE TITLE
QA TEST: iOS TestFlight 1.3 Build 38

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#344]
Please check the following issues which are ready for QA in this version.

- [x] [Bug: Collection View Layout is wrong on iPhone X landscape](https://github.com/phetsims/phet-ios-app/issues/500)
- [x] [Convert Filter from Delegation to Notification](https://github.com/phetsims/phet-ios-app/issues/497)
- [x] [Convert Heart and Chevron assets/elements to Templates](https://github.com/phetsims/phet-ios-app/issues/492)
- [x] [Use CGImage and Downsampling ](https://github.com/phetsims/phet-ios-app/issues/490)
- [x] [Pressing the 'Info' button in List View crashes the app](https://github.com/phetsims/phet-ios-app/issues/488)
- [x] [Improve Update System: Localization](https://github.com/phetsims/phet-ios-app/issues/487)
- [x] [White flash does not stop](https://github.com/phetsims/phet-ios-app/issues/484)
- [x] [Convert Root View to UINavigationController](https://github.com/phetsims/phet-ios-app/issues/482)
- [x] [Improve Play View Layout adjustments](https://github.com/phetsims/phet-ios-app/issues/478)
- [x] [Table View Based Details](https://github.com/phetsims/phet-ios-app/issues/477)
- [x] [Table View Based About and Settings](https://github.com/phetsims/phet-ios-app/issues/476)
- [x] [Table View Based Filtering](https://github.com/phetsims/phet-ios-app/issues/475)
- [ ] [**Localize Category Labels**](https://github.com/phetsims/phet-ios-app/issues/473)
- [x] [REST API 2.0: Compressed Sims](https://github.com/phetsims/phet-ios-app/issues/467)
- [x] [REST API 2.0: `localizedSimulations`](https://github.com/phetsims/phet-ios-app/issues/466)
- [x] [Replace custom UIButton with FavouriteButton in Play View](https://github.com/phetsims/phet-ios-app/issues/462)
- [x] [UI Changes](https://github.com/phetsims/phet-ios-app/issues/460)
- [x] [Corners of info dialogue aren't rounded after exiting sim](https://github.com/phetsims/phet-ios-app/issues/455)
- [x] [Able to drag sim around](https://github.com/phetsims/phet-ios-app/issues/412)
- [x] [Sim appears twice](https://github.com/phetsims/phet-ios-app/issues/406)
- [x] [Inconsistent collection view scroll position](https://github.com/phetsims/phet-ios-app/issues/344)

Chris Huxtable mentioned:
I would also note there is a known bug. The app will randomly crash when pressing the back button from the sim player.

**Comment by KatieWoe** [comment]
@ariel-phet for priority

**Comment by oliver-phet** [comment]
@KatieWoe We will also want to test some translation submissions/edits - we can sync up about this.

**Comment by KatieWoe** [comment]
I had the app crash and close once when switching from list to table collection view in the manner described in the original issue.  Happened a few times in the manner described as well a few times.  does this warrant its own issue, or is it the same issue?
>I would also note there is a known bug. The app will randomly crash when pressing the back button from the sim player.

**Comment by KatieWoe** [comment]
From Slack:
>Chris Huxtable [3:33 PM]
>Interesting. I will have a look into it.
>it may be fixed in the new test flight. I modified some of the setup code.

**Comment by KatieWoe** [comment]
Other than that, I think QA is done for this test flight version.

**Comment by mattpen** [comment]
@KatieWoe  said 

> QA is done for this test flight version

closing, the next version will be published soon
