### ISSUE TITLE
iOS App: TestFlight 1.3(39)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#348]
Issues to test:

- [x] [phetsims/phet-ios-app#497](Convert Filter from Delegation to Notification)
- [x] [phetsims/phet-ios-app#492](Convert Heart and Chevron assets/elements to Templates)
- [ ] [phetsims/phet-ios-app#487](**Improve Update System: Localization**)
- [x] [phetsims/phet-ios-app#475](Table View Based Filtering)
- [ ] [phetsims/phet-ios-app#473](**Localize Category Labels**)
- [x] [phetsims/phet-ios-app#344](Inconsistent collection view scroll position)

**Comment by mattpen** [comment]
@KatieWoe build 39 should be available in TestFlight now or within the hour.

**Comment by KatieWoe** [comment]
@ariel-phet should this be the same priority?

**Comment by KatieWoe** [comment]
- [x] https://github.com/phetsims/phet-ios-app/issues/506
- [x] https://github.com/phetsims/phet-ios-app/issues/505
- [ ] https://github.com/phetsims/phet-ios-app/issues/504
- [ ] https://github.com/phetsims/phet-ios-app/issues/503
- [ ] https://github.com/phetsims/phet-ios-app/issues/502

These were given the label later

**Comment by KatieWoe** [comment]
QA is done with (39).  Issues either added, altered due to continued issues, left due to other issues preventing testing, or closed.

**Comment by mattpen** [comment]
> QA is done with (39).
