### ISSUE TITLE
RC Test: Capacitor-Lab-Basics 1.7.0-rc.3

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#349]
@ariel-phet, @arouinfar, Capacitor-Lab-Basics/1.7.0-rc.3 is ready for RC testing.  Document issues in https://github.com/phetsims/capacitor-lab-basics/issues and link to this issue. This is only a PhET brand spot check.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Don't forget to make sure the sim works with Legends of Learning.
- When making an issue, check to see if it was in a previously published version

<h3>Focus and Special Instructions</h3>

This is an RC-Spot check to test against previously opened issues from the RC.2 test [issue](https://github.com/phetsims/QA/issues/321).

<h3>Issues to Verify</h3>

- [x] [Inconsistent tool box size when strings are long](https://github.com/phetsims/capacitor-lab-basics/issues/269)
- [x] [Longer strings near capacitance, plate charge, and energy bars need more space](https://github.com/phetsims/capacitor-lab-basics/issues/268)
- [x] [Short strings are centered](https://github.com/phetsims/capacitor-lab-basics/issues/266)
- [x] [Charge in top plate changes inappropriately ](https://github.com/phetsims/capacitor-lab-basics/issues/256)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is "status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.3/phet/capacitor-lab-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.3/phet/capacitor-lab-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.3/phet/xhtml/capacitor-lab-basics_all.xhtml)**
- **[**Test Matrix**](brokenLink)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome (with and without Jaws)
- [ ] Win 10 firefox (with and without NVDA)
- [ ] Win 10 edge
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox
- [ ] Mac 10.14 safari (with and without VO)
---
- [ ] Win 7 IE
- [ ] Mac 10.11 safari
---
- [ ] ChromeOS
- [ ] iOS 12 (with and without VO)
---
@Denz1994  to approve test devices

**Comment by KatieWoe** [comment]
QA is done.  https://github.com/phetsims/capacitor-lab-basics/issues/256.  Part of it (or part of the fix) seems to depend on platform.

**Comment by chrisklus** [comment]
Patched issue https://github.com/phetsims/phet-ios-app/issues/484 on this release branch.

**Comment by Denz1994** [comment]
This test cycle has been completed by QA. Related issues still need work but this issue can be closed. A new RC test cycle should be done for a spot check.
