### ISSUE TITLE
iOS App: TestFlight 1.3(40)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#363]
Issues to test:

- [x] Bug: Safe Margins not used on Table View phetsims/phet-ios-app#514
- [x] Possible to have multiple categories selected phetsims/phet-ios-app#513
- [ ] Search is case-sensitive phetsims/phet-ios-app#511
- [ ] Alphabetize sim list order, ignoring capitalization phetsims/phet-ios-app#510
- [x] Gray hearts when "Show only Favorites" is on phetsims/phet-ios-app#509
- [ ] App freezes when you try to update a sim phetsims/phet-ios-app#508
- [x] Some, but not all, aspects grayed out when filter menu open phetsims/phet-ios-app#505
- [x] Bug: Pressing back button in sim sometimes causes crash phetsims/phet-ios-app#502
- [x] Improve Update System: Localization phetsims/phet-ios-app#487
- [ ] Localize Category Labels phetsims/phet-ios-app#473

Please be aware of the following known bugs:

- https://github.com/phetsims/phet-ios-app/issues/507
- https://github.com/phetsims/phet-ios-app/issues/499

Assigning to @ariel-phet for priority.

**Comment by oliver-phet** [comment]
@KatieWoe Here's the logic steps I'd like to test:

1. Open the app
2. It checks for updates in terms of new sims and any minor version changes
3. If a new sim or minor version change, it downloads a new .all file
4. Since in (3) it is downloading the latest .allfile, for those sims, it should also be getting all the latest translations (even though updating due to a bug fix or such)
5. For any sims not being updated in (2), the app sees if the individual translated version has changed (this should be pretty rare, only if a translation has been updated). If a translation has been updated, a new .all file would be downloaded.
6. If a user changes preferred locale, the app would run through (5) checking for new translations

**Comment by KatieWoe** [comment]
Moving down due to https://github.com/phetsims/QA/issues/366

**Comment by KatieWoe** [comment]
Testing is done.  Unchecked boxes are either unsolved, or can't yet be tested.

**Comment by mattpen** [comment]
Build 40 has been expired. Please continue testing with build 42 #377
