### ISSUE TITLE
iOS App: TestFlight 1.3(42)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#377]
QA, please test the latest TestFlight build of the iOS app, including the following issue:

- [ ] **phetsims/phet-ios-app#521 iOS 13 Refinements**
- [ ] **phetsims/phet-ios-app#520 Remove Unnecessary Toolbars in iOS 13**
- [x] phetsims/phet-ios-app#518 Clearing Filters Does Not Clear Favorites
- [x] phetsims/phet-ios-app#513 Possible to have multiple categories selected
- [x] phetsims/phet-ios-app#511 Search is case-sensitive
- [x] phetsims/phet-ios-app#510 Alphabetize sim list order, ignoring capitalization
- [x] phetsims/phet-ios-app#509 Gray hearts when "Show only Favorites" is on
- [ ] phetsims/phet-ios-app#508 **App freezes when you try to update a sim**
- [ ] phetsims/phet-ios-app#507 **Sims are not updating when app opens**
- [x] phetsims/phet-ios-app#505 Some, but not all, aspects grayed out when filter menu open
- [x] phetsims/phet-ios-app#502 Bug: Pressing back button in sim sometimes causes crash
- [ ] **phetsims/phet-ios-app#473 Localize Category Labels**

Please be aware that the following issues are not fixed in this release:

- Ability to test sims in the app before sims are published https://github.com/phetsims/phet-ios-app/issues/519
- Bug: Collection/List View cell disappears below bottom Toolbar https://github.com/phetsims/phet-ios-app/issues/499 

Assigning @ariel-phet for priority.

**Comment by KatieWoe** [comment]
Issues have been checked.  QA is done for now.  May still do checks for anything new if there is time.

**Comment by chris-huxtable** [comment]
I am going to close the issues which are fixed.

**Comment by mattpen** [comment]
This build has been expired.
