### ISSUE TITLE
RC Test: Atomic Interactions 1.1.0-rc.4

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/QA#385]
@KatieWoe, @arouinfar, atomic-interactions/1.1.0-rc.4 is ready for RC testing. [List deadlines and whether this will be shared with a client.] Document issues in https://github.com/phetsims/atomic-interactions/issues and link to this issue. This is the rc.4 because this is my first RC and I had some issues getting started.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- If there is a console available, check for errors and include them in the Problem Description.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested, list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [x] [Force Arrows remain when atom changes](https://github.com/phetsims/atomic-interactions/issues/76)
- [x] [Grid is in front of atoms and line](https://github.com/phetsims/atomic-interactions/issues/75)
- [x] [Pinned and Moving strings very small](https://github.com/phetsims/atomic-interactions/issues/74)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is "status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/atomic-interactions/1.1.0-rc.4/phet/atomic-interactions_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/atomic-interactions/1.1.0-rc.4/phet/atomic-interactions_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/atomic-interactions/1.1.0-rc.4/phet/xhtml/atomic-interactions_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1KffV-UyjeB7GyCcdDooE5Nh02k3QUTlo9MVHT3E89G8/edit#gid=1135799571)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe currently last in priority with the current list of RC tests, will move up priority once some other things clear

**Comment by KatieWoe** [comment]
QA is done
