### ISSUE TITLE
iOS App: v1.3(44)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#395]
Please test versions 1.3(44) and 1.3(1044).  The latter is the "debug" version of the app, which has the test solution described in https://github.com/phetsims/phet-ios-app/issues/519.

Please test the following issues in the production version:

- [x] Sim info require scrolling and changed look phetsims/phet-ios-app#528
- [x] Kerning issue in sim description? phetsims/phet-ios-app#526
- [x] Sim titles are default phetsims/phet-ios-app#524
- [ ] **No sims are preloaded** phetsims/phet-ios-app#523
- [ ] iOS 13 Refinements phetsims/phet-ios-app#521
- [ ] Remove Unnecessary Toolbars in iOS 13 phetsims/phet-ios-app#520
- [ ] _App freezes when you try to update a sim_ phetsims/phet-ios-app#508
- [ ] **Sims are not updating when app opens** phetsims/phet-ios-app#507
- [ ] **Localize Category Labels** https://github.com/phetsims/phet-ios-app/issues/473

**Comment by ariel-phet** [comment]
Current top testing priority

**Comment by chris-huxtable** [comment]
Fixed in v1.3(45)
- No sims are preloaded
- Sims are not updating when app opens

**Comment by mattpen** [comment]
Continue testing in #398
