### ISSUE TITLE
iOS App: v1.3(45)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#398]
Please test versions 1.3(45) and 1.3(1045). The latter is the "debug" version of the app, which has the test solution described in phetsims/phet-ios-app#519.

Please test the following issues:

- [x] phetsims/phet-ios-app#523 No sims are preloaded
- [x] phetsims/phet-ios-app#521 iOS 13 Refinements
- [x] phetsims/phet-ios-app#520 Remove Unnecessary Toolbars in iOS 13
- [x] phetsims/phet-ios-app#508 App freezes when you try to update a sim
- [x] phetsims/phet-ios-app#507 Sims are not updating when app opens

**Comment by mattpen** [comment]
Copying priority from #395, @ariel-phet please adjust if necessary.

**Comment by KatieWoe** [comment]
Version is now (46).  Do you still want testing @mattpen?

**Comment by mattpen** [comment]
build 45 has been removed from testflight.

> PS. Listed issues are all checked. Can still do basic checks and testing if desired.

Unclear to me if there are additional issues to check.

**Comment by KatieWoe** [comment]
ie. looking for new issues.
Closing since 46 is up
