### ISSUE TITLE
Website: Test Navigation and Front Page

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#404]
QA, please complete an RC-like test for the website navigation and front page at https://ox-dev.colorado.edu/.  Please test a few other pages in addition to the front page to make sure the navigation is compatible across the site.  Please test in 1-2 other locales as well, including an RTL locale (ar_SA).  Confirm that everything is working across supported os'es, browsers, and browsing methods (mouse, touch, keyboard nav, screen readers, etc.)

Confirm that the following issues are resolved:

- [x] phetsims/website#852 Grey box over small menu seems a bit misshapen
- [x] phetsims/website#848 Unable to X out of sign in dialog with Jaws
- [x] phetsims/website#846 2 headings for one sentence Screen Reader
- [x] phetsims/website#844 Navbar too short on iPhone 5/SE
- [x] phetsims/website#824 Other languages can lead to Navbar going over its bounds
- [x] phetsims/website#823 RTL Accessible Simulations leads to crash and puts user in english
- [x] phetsims/website#811 Skipping to main content doesn't last when tabbing

@ariel-phet, please assign a priority

**Comment by ariel-phet** [comment]
@KatieWoe app comes first, but we definitely would like to get the website new look out by the end of August ideally, so this is a high priority

**Comment by mattpen** [comment]
@KatieWoe - can you post an update on the progress/status of this issue?

**Comment by KatieWoe** [comment]
Issues have been checked.  A few new issues have been submitted for confirmation.  Testing has slowed a bit since the given issues have been checked, but testing for new issues is still happening.  Can be called to an end when you feel comfortable though.  Limited screen reader testing has been done though.

**Comment by KatieWoe** [comment]
I think testing can be called for the most part.  I'd like to keep testing as we have time, but I think we have the big things for now.

**Comment by amanda-phet** [comment]
When you make an issue found while doing this QA task, can you add the "Front page" milestone to the issue?
