### ISSUE TITLE
iOS App: RC1 - version 1.3 build 47

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#408]
QA, please test the following issues in the latest build of the app (47).

- [x] phetsims/phet-ios-app#535 Strings seem translated for no reason
- [x] phetsims/phet-ios-app#534 Filter menu points to iPad bar
- [x] phetsims/phet-ios-app#533 Empty Favorite Dialog
- [x] phetsims/phet-ios-app#531 Press view button to go to top of page
- [x] phetsims/phet-ios-app#508 Sim crashes for PhET Menu items targeting new window
- [x] phetsims/phet-ios-app#487 Improve Update System: Localization
- [x] phetsims/phet-ios-app#470 Investigate making the touch area on the Filter icon larger?
- [x] phetsims/phet-ios-app#450 App Localization

**Comment by lmulhall-phet** [comment]
QA is done. Next version is on Test Flight.
