### ISSUE TITLE
RC test: Gas Properties 1.0.1-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#415]
@KatieWoe , @arouinfar, gas-properties/1.0.1-rc.1 is ready for RC testing. 

This release does not include PhET-iO or a11y.

Document issues in https://github.com/phetsims/gas-properties/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- If there is a console available, check for errors and include them in the Problem Description.

<h3>Issues to Verify</h3>

There issues can be spot checked on a few platforms. There is no need for a full test matrix.

- [x] [revisit performance on Win10 + Chrome](https://github.com/phetsims/gas-properties/issues/146)
- [x] [Fire/ice layering is inconsistent](https://github.com/phetsims/gas-properties/issues/164)
- [x] [Testing for popup maintenance release](https://github.com/phetsims/gas-properties/issues/166)
- [x] [Minor performance improvements to container rendering](https://github.com/phetsims/gas-properties/issues/167)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is "status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/gas-properties/1.0.1-rc.1/phet/gas-properties_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/gas-properties/1.0.1-rc.1/phet/gas-properties_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/gas-properties/1.0.1-rc.1/phet/xhtml/gas-properties_all.xhtml)**
- **Test Matrix (N/A)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
moving down to medium priority for now

**Comment by jonathanolson** [comment]
It looks like this change went live because the maintenance "check branch status" routine was only looking to make sure the last change made WAS deployed, and so it didn't flag the branch when the last change was deployed to an RC version (for testing). We'll want to notify the maintenance release developer if there is a sim out in RC testing (or on an RC version for the latest deploy), change committed above. This shouldn't happen again due to this.

@ariel-phet and @KatieWoe since these (untested?) changes are now live (just in gas-properties, not the other related simulations), should we increase priority?

**Comment by pixelzoom** [comment]
Adding to what @jonathanolson said in the previous comment....

This is all related to the batch patch applied for phetsims/phet-core#64 (iOS 13 Full Screen enabled).

Gas Properties 1.0.1 is now live with the patch, plus all of the changes that are being regression tested by this QA issue.  I doubt that any of the issues related to this RC will cause problems, but what's now live on the website has not been through the QA process. 

Diffusion and Gas Laws 1.0.2 are now live with the patch, and _none_ of the changes being regression tested by this QA issue.  Their dependencies will need to be updated to point to gas-properties HEAD, and they will need to be republish.

There were also a couple more RC versions published for Gas Properties (1.0.1-rc.2 and 1.0.1-rc.3) that will be fun to explain in the future.

**Comment by KatieWoe** [comment]
Sanity test passed on Win 10 chrome and iOS 12 safari.  I would check iPad OS but that device was packed up for NCTM

**Comment by pixelzoom** [comment]
@ariel-phet what are we going to do here? Gas Properties 1.0.1 is live and did not complete QA testing.

**Comment by pixelzoom** [comment]
9/26/19 status meeting:

* @ariel-phet said it's likely to be a long time before this issue pops to the top of the QA queue. So he is fine with just closing this issue (and the related RC issues, #416 and #147), just assuming that everything is OK.
* @kathy-phet is OK with that, if @KatieWoe is OK with it.  She also noted that #417 (Diffusion) appears to be done, and the others only have 1 platform remaining (Mac 10.11 Safari).

@KatieWoe how do you want to proceed?

**Comment by KatieWoe** [comment]
I'm fine with that @pixelzoom

**Comment by pixelzoom** [comment]
Thanks @KatieWoe, I will close the RC test issues.

Btw, I misspoke above:
> Diffusion and Gas Laws 1.0.2 are now live with the patch, and none of the changes being regression tested by this QA issue. Their dependencies will need to be updated to point to gas-properties HEAD, and they will need to be republished.

Both of those sims do in fact have the gas-properties changes. Their 1.0 branches were updated to use gas-properties HEAD in https://github.com/phetsims/gases-intro/commit/d4c0949eece92e13fec87533ff07c0f37827773f and https://github.com/phetsims/diffusion/commit/58f2506dc77f7e951288758be2e668c4e665628e respectively.

So there's nothing the needs to be published, and closing the issues is sufficient.

Closing this issue.
