### ISSUE TITLE
iOS App: TestFlight build 48

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#421]
QA, please test all the issues in this milestone for this build:

https://github.com/phetsims/phet-ios-app/milestone/7

**Comment by KatieWoe** [comment]
- [ ] [Localize Updates](https://github.com/phetsims/phet-ios-app/issues/487)
- [ ] [Filter in middle of iPhone](https://github.com/phetsims/phet-ios-app/issues/538)
- [ ] [Filter menu pointing](https://github.com/phetsims/phet-ios-app/issues/534)
- [ ] [Return to top of page](https://github.com/phetsims/phet-ios-app/issues/531)
- [ ] [About view on iPad](https://github.com/phetsims/phet-ios-app/issues/537)
- [ ] [Update cache](https://github.com/phetsims/phet-ios-app/issues/536)
- [ ] [Localize Check](https://github.com/phetsims/phet-ios-app/issues/450)

**Comment by KatieWoe** [comment]
https://github.com/phetsims/QA/issues/430 is out.  Closing
