### ISSUE TITLE
RC Test: Projectile Motion 1.0.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#44]
@phet-steele @andrea-phet @arouinfar Projectile Motion 1.0.0-rc.2 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-rc.2/projectile-motion_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-rc.2/projectile-motion_en-iframe.html)**

A full test matrix is not needed for this RC test. Spot testing on a couple of platforms is sufficient.

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] phetsims/projectile-motion#143
- [x] phetsims/projectile-motion#144
- [x] phetsims/projectile-motion#145
- [x] phetsims/projectile-motion#146
- [x] phetsims/scenery-phet#332

If any new issues are found, please note them in https://github.com/phetsims/projectile-motion/issues and reference this issue.

**Comment by phet-steele** [comment]
![greenlight](https://user-images.githubusercontent.com/5863899/29640442-3eb364a8-881c-11e7-9d34-e4159c05f460.png)

**Comment by pixelzoom** [comment]
@andrea-phet please proceed with publishing 1.0.0, following steps in [sim_deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md).  After doing `grunt deploy-production`, notify @arouinfar so she can complete the steps necessary to make the sim visible on the PhET website.

**Comment by andrea-phet** [comment]
Published!

https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_en.html
