### ISSUE TITLE
RC test: Vector Addition 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#445]
@KatieWoe, @arouinfar, vector-addition/1.0.0-rc.1 is ready for RC testing. 

This release does not include PhET-iO or a11y.

Document issues in https://github.com/phetsims/vector-addition/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- If there is a console available, check for errors and include them in the Problem Description.

<h3>Issues to Verify</h3>

There are no specific issues to verify; all known issues have been addressed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/vector-addition_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-rc.1/phet/xhtml/vector-addition_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1wADLeKDPZJPovp4TH1MIH6AYznCTF9wH1BOS2ZhE-e0/edit#gid=2022675417)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
This testing should definitely be done before #446, and then #446 should generally be able to just be a spot check (as mentioned in its issue instructions)

**Comment by KatieWoe** [comment]
Memory Test results:
![memoryresults](https://user-images.githubusercontent.com/41024075/67499544-86b62500-f63e-11e9-9f5f-0457fa4927e8.png)

**Comment by pixelzoom** [comment]
@KatieWoe Just out of curiosity, what's the time interval between snapshots?

**Comment by KatieWoe** [comment]
1 minute.
Snapshot one is at the very start, snapshot two is one minute in, etc.

**Comment by ariel-phet** [comment]
Moving to current top priority

**Comment by KatieWoe** [comment]
QA is done here.  Hoping to finish equations sim tomorrow.

**Comment by pixelzoom** [comment]
Thank you @KatieWoe and QA team!

**Comment by pixelzoom** [comment]
Issues to be verified, to be copy-pasted into next QA RC issue.

- [ ] [Toolbox arrow icons should have rectangular or more expanded pointer areas](https://github.com/phetsims/vector-addition/issues/250)
- [ ] [0 vector has larger pointer area](https://github.com/phetsims/vector-addition/issues/252)
- [ ] [Upside-down f vector when d vector and e vector cancel](https://github.com/phetsims/vector-addition/issues/260)
- [ ] [Assertion failed: Not handling arcs with start/end angles that show differences in-between browser handling](https://github.com/phetsims/vector-addition/issues/261)
- [ ] [labels overlap for vector <-x,0>](https://github.com/phetsims/vector-addition/issues/264)
- [ ] [incorrect (solid) leader lines when sum vector is made visible](https://github.com/phetsims/vector-addition/issues/265)
- [ ] [missing leader line when sum vector component is zero](https://github.com/phetsims/vector-addition/issues/266)
- [ ] [grabbing the origin manipulator clears the selected vector](https://github.com/phetsims/vector-addition/issues/268)

**Comment by pixelzoom** [comment]
The next RC has been published and is being tracked in https://github.com/phetsims/QA/issues/451.

Closing.
