### ISSUE TITLE
RC test: Vector Addition: Equations 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#446]
@KatieWoe, @arouinfar, vector-addition-equations/1.0.0-rc.1 is ready for RC testing. 

This release does not include PhET-iO or a11y.

This sim consists of the _Equations_ screen from Vector Addition. So please document issues in https://github.com/phetsims/vector-addition/issues (not vector-addition-equations) and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- If there is a console available, check for errors and include them in the Problem Description.

<h3>Focus and Special Instructions</h3>

_Vector Addition: Equations_ consists of the _Equations_ screen from the _Vector Addition_ sim, with no changes.  So this sim does not require a full test matrix. Thorough testing of the _Equations_ screen can be done in https://github.com/phetsims/QA/issues/#445, and this sim can be spot tested on a few platforms.

<h3>Issues to Verify</h3>

There are no specific issues to verify; all known issues have been addressed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/vector-addition-equations/1.0.0-rc.1/phet/vector-addition-equations_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/vector-addition-equations/1.0.0-rc.1/phet/vector-addition-equations_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/vector-addition-equations/1.0.0-rc.1/phet/xhtml/vector-addition-equations_all.xhtml)**
- **[Test Matrix](link)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
---
- [ ] Mac 10.15 chrome
- [ ] Mac 10.15 safari
---
- [ ] Win 7 IE
- [ ] Mac 10.12 safari
---
- [ ] ChromeOS
- [ ] iPadOS 13

**Comment by KatieWoe** [comment]
Memory Test Results:
![memoryresults2](https://user-images.githubusercontent.com/41024075/67500685-4d7eb480-f640-11e9-9162-a66dc9bd20f2.png)

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thank you @KatieWoe and QA team.

**Comment by pixelzoom** [comment]
Issues to be verified, to be copy-pasted into the next QA RC issue.

- [ ] [0 vector has larger pointer area](https://github.com/phetsims/vector-addition/issues/252)
- [ ] [Upside-down f vector when d vector and e vector cancel](https://github.com/phetsims/vector-addition/issues/260)
- [ ] [Assertion failed: Not handling arcs with start/end angles that show differences in-between browser handling](https://github.com/phetsims/vector-addition/issues/261)
- [ ] [labels overlap for vector <-x,0>](https://github.com/phetsims/vector-addition/issues/264)
- [ ] [incorrect (solid) leader lines when sum vector is made visible](https://github.com/phetsims/vector-addition/issues/265)
- [ ] [missing leader line when sum vector component is zero](https://github.com/phetsims/vector-addition/issues/266)
- [ ] [grabbing the origin manipulator clears the selected vector](https://github.com/phetsims/vector-addition/issues/268)

**Comment by pixelzoom** [comment]
The next RC has been published and is being tracked in #452.

Closing.
