### ISSUE TITLE
Sanity check testing for ES6 modules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#482]
Under https://phet-dev.colorado.edu/modules-testing/, I've manually "deployed" three simulations: build-a-molecule, john-travoltage and molarity.

Under `/phet/` should be the phet-brand links, and under `/phet-io/` should be the password-protected parts for phet-io testing. It *seems* like phet-io is operating normally.

If things seem very broken, feel free to contact @jonathanolson or @samreid before continuing.

Notes from https://github.com/phetsims/chipper/issues/867 about what we want tested:

### Stage 1: Basic test on all platforms, all 3 sims:

1. Does the sim run and behave normally?
2. Fuzz the sim for 30 seconds.

### Stage 2: Just 2 sims on a few platforms:

1. Do the strings display naturally?
2. Does English work
3. Does Spanish work? 
4. Do simplified Chinese characters (`zh_cn`) work?
5. Check phet-brand, phet-io-brand, and adapted-from-phet including credits and licensing.
6. Does a11y view run and seem OK?
7. Do the sims work in an iframe?
8. Do the sims work in XHTML?
9. Do the PhET-iO wrappers work?
10. Do these sims look good in the debug version of the app?
11. Make sure the sound works.
12. Test some query parameters, e.g. `?screens=2,1`.

For 1-4, use the "all" file and locale specific files.

@jbphet has created a side issue for making sure Rosetta works on a built ES6 sim. See https://github.com/phetsims/chipper/issues/883.

**Comment by ariel-phet** [comment]
@KatieWoe next top priroity once #480 is finished off.

If you have questions, feel free to ping @jonathanolson

**Comment by KatieWoe** [comment]
- [ ] iPad 10.12 Safari
     - [ ] Basic Test
     - [ ] Locale Tests
- [ ] iPad 10.13 Safari
     - [ ] Basic Test
     - [ ] String Tests
     - [ ] a11y View
     - [ ] App Test
- [ ] Mac 10.10 Safari
     - [ ] Basic Test
     - [ ] Brand Tests
- [ ] Mac 10.11 Safari
     - [ ] Basic Test
     - [ ] String Tests
- [ ] Mac 10.11 Chrome
     - [ ] Basic Test
     - [ ] iframe Test
- [ ] Mac 10.12 Safari
     - [ ] Basic Test
     - [ ] Locale Tests
- [ ] Mac 10.12 Chrome
     - [ ] Basic Test
     - [ ] Sound Test
- [ ] Mac 10.13 Safari
     - [ ] Basic Test
     - [ ] Sound Test
- [ ] Mac 10.13 Chrome
     - [ ] Basic Test
     - [ ] iframe Test
- [ ] Mac 10.14 Safari
     - [ ] Basic Test
     - [ ] XHTML Test
- [ ] Mac 10.14 Chrome
     - [ ] Basic Test
     - [ ] Query Parameter Test
- [ ] Mac 10.15 Safari
     - [ ] Basic Test
     - [ ] Brand Tests
     - [ ] Wrapper Tests
- [ ] Mac 10.15 Chrome
     - [ ] Basic Test
     - [ ] a11y View
     - [ ] Query Parameter Test
- [ ] Win 10 IE
     - [ ] Basic Test
     - [ ] Locale Tests
     - [ ] iframe Test
- [ ] Win 10 Edge
     - [ ] Basic Test
     - [ ] String Tests
     - [ ] XHTML Test
- [ ] Win 10 Firefox
     - [ ] Basic Test
     - [ ] Locale Tests
     - [ ] Wrapper Tests
     - [ ] Sound Test
- [ ] Win 10 Chrome
     - [ ] Basic Test
     - [ ] a11y View
     - [ ] Wrapper Tests
     - [ ] Query Parameter Test
- [ ] ChromeOS
     - [ ] Basic Test
     - [ ] Brand Tests
     - [ ] XHTML Test
     - [ ] Query Parameter Test

**Comment by KatieWoe** [comment]
@jonathanolson @samreid Let me know if there any changes you want to the above test checklist.

**Comment by jonathanolson** [comment]
Looks good to me!

**Comment by jonathanolson** [comment]
Also, I think my biggest worry would be how it works on Win10 IE, is it possible to test that next?

**Comment by KatieWoe** [comment]
I can do that. What aspects? @jonathanolson

**Comment by KatieWoe** [comment]
Per @samreid doing phet-io testing on Molarity

**Comment by KatieWoe** [comment]
Noted elsewhere, but recording here. String test query parameters do not seem to be working. Non-locale query parameters should still work.

**Comment by jonathanolson** [comment]
IE11 and stringTest fixes are included in https://phet-dev.colorado.edu/modules-testing2. I'll be working on other items, but can we get those tests done under that?

**Comment by KatieWoe** [comment]
Dragging sliders in Molarity in IE is a bit more laggy than in published, but not really bad enough to be issue worthy.

**Comment by lmulhall-phet** [comment]
The debug version of BAM doesn't open in macOS 10.10.5 + Safari 10.1.2. You get stuck at the loading page with no progress in the loading bar. This is the error in the console:

![issue](https://user-images.githubusercontent.com/31285590/75299037-44ba0d00-57f1-11ea-8fd2-71c97b9c7f89.png)

**Comment by lmulhall-phet** [comment]
Blue floor and blue wall? Is this a thing that we know about?

![1](https://user-images.githubusercontent.com/31285590/75301894-60291600-57f9-11ea-9cbd-3abd8ce568f1.png)

I saw this on macOS 10.11.6 + Safari 11.1.2.

**Comment by jonathanolson** [comment]
Were dev tools open in Safari or something?

**Comment by lmulhall-phet** [comment]
@jonathanolson, no devtools open, but I may have had them open earlier.

**Comment by lmulhall-phet** [comment]
Pending @KatieWoe's approval, QA is done.

**Comment by KatieWoe** [comment]
I think https://github.com/phetsims/QA/issues/482#issuecomment-591180838 should probably have an issue. I'll make one and then we'll finish up.

**Comment by KatieWoe** [comment]
QA is done

**Comment by KatieWoe** [comment]
Assigning @ariel-phet since this is important for Thursday.

**Comment by ariel-phet** [comment]
@samreid @jonathanolson since QA is complete, would be good for both of you to review the found issues. Nothing here looks like show stoppers for the migration to me.

**Comment by zepumph** [comment]
@samreid, @chrisklus, and @zepumph looked over all open issues this morning, and non seemed related to or blocking es6 module migration. We feel good to close, but wanted to ping @jonathanolson to see if there is anything else for this issue.

**Comment by pixelzoom** [comment]
@jonathanolson @ariel-phet can this be closed?

**Comment by jonathanolson** [comment]
Yes, thank you!
