### ISSUE TITLE
Android App: Dev test 1.1-dev.2

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#496]
QA, please conduct another dev test of the android app.
The internal test track version can be installed from this link: https://play.google.com/apps/internaltest/4697762600441754675.

Most of the issues should be fixed from last time.  Please check the following:

- [x] [Different background color behind sim icons type:bug](https://github.com/phetsims/phet-android-app/issues/101)
- [ ] [Search bar doesn't deactivate type:bug](https://github.com/phetsims/phet-android-app/issues/100)
- [ ] [Possible to have a gap between sim icons type:bug](https://github.com/phetsims/phet-android-app/issues/99)
- [x] [Some sims don't open type:bug](https://github.com/phetsims/phet-android-app/issues/97)
- [x] [App keeps crashing type:bug](https://github.com/phetsims/phet-android-app/issues/96)
- [x] [Cursor never changes to a hand status:ready-for-qa type:bug](https://github.com/phetsims/phet-android-app/issues/55)

This issue is not yet fixed: https://github.com/phetsims/phet-android-app/issues/98.

Additionally, there is a known issue where the filter dialog cannot be dismissed.

@ariel-phet - What is the priority of this test?

**Comment by ariel-phet** [comment]
@KatieWoe this would be good to address after "decaf" sim testing

**Comment by ariel-phet** [comment]
@KatieWoe #498 is higher priority, but it would be good to identify 1 or 2 bugs before May 5

**Comment by ariel-phet** [comment]
@KatieWoe reducing priority since multiple bugs have been identified
