### ISSUE TITLE
Android App: Dev test 3 (1.1.26)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#512]
QA, please conduct another dev test of the android app.
The internal test track version can be installed from this link: https://play.google.com/apps/internaltest/4697762600441754675.

NOTE: Please delete the existing "PhET" app before installing this one.  It is OK if the previous production app ("PhET Simulations") is still installed, but previous dev versions of this app can cause problems if they remain.

Please check the following:

- [x] phetsims/phet-android-app#106 Reset Favorites and Update Simulations do nothing
- [x] phetsims/phet-android-app#105 Info Box Sometimes Has Blank Sim Icons
- [x] phetsims/phet-android-app#103 Phet Menu icon is not right alligned
- [x] phetsims/phet-android-app#102 Placeholder image is too tall
- [x] phetsims/phet-android-app#100 Search bar doesn't deactivate
- [x] phetsims/phet-android-app#99  Possible to have a gap between sim icons
- [x] phetsims/phet-android-app#98 Update PhET Info Dialog
- [x] phetsims/phet-android-app#56 Favorite heart is too large on phones

@ariel-phet - What is the priority of this test?

**Comment by ariel-phet** [comment]
Current top testing priority. @ariel-phet will try to help a bit on 7/7/2020

**Comment by ariel-phet** [comment]
@KatieWoe that looks good for this round, we should move to other testing priorities now. Leaving assigned to myself to check one or two more things on my phone.
