### ISSUE TITLE
RC test: pH Scale: Basics 1.4.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#515]
@arouinfar phet-scale-basics/1.4.0-rc.1 is ready for RC testing. 

This RC test should be done at the same time as https://github.com/phetsims/QA/issues/514 (pH Scale 1.4.0-rc.1).

Document issues in https://github.com/phetsims/ph-scale/issues (NOT in ph-scale-basics) and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Issues to Verify</h3>

These changes and fixes should be verified:

- [x] [order solutes alphabetically in combo box](https://github.com/phetsims/ph-scale/issues/101)
- [x] [setting maxWidth for listboxParent causes scale/position problem](https://github.com/phetsims/ph-scale/issues/93)

These issues have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/ph-scale-basics/1.4.0-rc.1/phet/ph-scale-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/ph-scale-basics/1.4.0-rc.1/phet/ph-scale-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/ph-scale-basics/1.4.0-rc.1/phet/xhtml/ph-scale-basics_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1QP3_4PEghNvkaEF8hkGaojGnpCrnWeDEJl4wYJ072KE/edit#gid=967424061)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- N/A For an update or maintenance release please check the backwards compatibility of the playback wrapper.
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Please at least load all wrappers except studio in the wrapper suite with internet explorer. 

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/ph-scale-basics/1.4.0-rc.1/phet-io/)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1LekmGeqrcPQwqcpS_RBXaIEzp8KteEXAfSJw7U2fMuI/edit#gid=1671051367)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by pixelzoom** [comment]
@ariel-phet @KatieWoe @arouinfar The client has specific PhET-iO requirements for this sim, which should be verified by QA. I'm still unclear on how those requirements are to be communicated to QA for verification, so there's no information about this in the above issue template.  You'll need to discuss how to proceed.

**Comment by arouinfar** [comment]
I've uploaded temporary pdf's to the phet-io-client-guides repo: https://github.com/phetsims/phet-io-client-guides/tree/master/ph-scale. The original documentation did not separate ph-scale and ph-scale-basics. 

In the future, these will be md files that exist before a dev/rc/production version gets built and they will be linked to from the Wrapper Index Page.

@KatieWoe, the client-specific customization requests and the corresponding phetioIDs can be found in [client-requests.pdf](https://github.com/phetsims/phet-io-client-guides/blob/master/ph-scale/client-requests.pdf). The [phet-io-guide.pdf](https://github.com/phetsims/phet-io-client-guides/blob/master/ph-scale/phet-io-guide.pdf) includes information about simulation-specific query parameters that might be useful for testing.

**Comment by ariel-phet** [comment]
@KatieWoe top priority (#513 comes first, but if it makes sense to do testing of this sim while on a specific platform along with MAL, testing priority can be considered concurrent).

**Comment by pixelzoom** [comment]
@kathy-phet said in 7/16/2020 that the milestone for publishing 1.4.0 and delivering to the client is 9/1/2020.

**Comment by KatieWoe** [comment]
Phet-io Memory Test
![memtest2](https://user-images.githubusercontent.com/41024075/89223550-34723f00-d594-11ea-8d83-ad5796ba0d28.png)

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thanks @KatieWoe and QA team.

Unfortunately, there were a lot of problems found with this RC -- mostly PhET-iO and common code.  So this is going to require another RC test cycle.  I'll leave this issue open until I've created the next RC and its associated QA issue.

**Comment by pixelzoom** [comment]
Here's what I need to copy to the next RC issue:

**Issues to Verify** (brand=phet)

Sim-specific:
- [ ] [update credits for 1.4.0 release](https://github.com/phetsims/ph-scale/issues/155)
- [ ] [Switching to empty beaker disables water faucet](https://github.com/phetsims/ph-scale/issues/170)
- [ ] [rename ?autoFill to ?autofill](https://github.com/phetsims/ph-scale/issues/179)

Common Code:
- [ ] [About dialog is scaled incorrectly](https://github.com/phetsims/ph-scale/issues/168)
- [ ] [Faucet knobs don't have indicated pointer areas](https://github.com/phetsims/ph-scale/issues/180)

**Issues to Verify** (brand=phet-io)

- [ ] [empty client guides published with this sim](https://github.com/phetsims/ph-scale/issues/167)
- [ ] [Studio search feature is broken](https://github.com/phetsims/ph-scale/issues/172)
- [ ] [empty Solute list box causes the sim to crash](https://github.com/phetsims/ph-scale/issues/177)
- [ ] [autofill still occurs with invisible dropper](https://github.com/phetsims/ph-scale/issues/178)
- [ ] [rename ?autoFill to ?autofill](https://github.com/phetsims/ph-scale/issues/179)
- [ ] [Tandem.REQUIRED is no longer checked](https://github.com/phetsims/ph-scale/issues/183)
- [ ] [Mirror wrapper may be unsynced during a slow load](https://github.com/phetsims/ph-scale/issues/188)
- [ ] [Old search remains when reopening studio tab from history](https://github.com/phetsims/ph-scale/issues/191)

**Comment by pixelzoom** [comment]
1.4.0-rc.2 has been published, tracking in https://github.com/phetsims/QA/issues/535.
