### ISSUE TITLE
Android App: Dev test 4 (1.1-dev.4) 

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#518]
QA, please conduct another dev test of the android app.
The internal test track version can be installed from this link: https://play.google.com/apps/internaltest/4697762600441754675.

NOTE: Please delete the existing "PhET" app before installing this one. It is OK if the previous production app ("PhET Simulations") is still installed, but previous dev versions of this app can cause problems if they remain.

Please check the following:

- [x] phetsims/phet-android-app#131 Exit bar overlaps search bar
- [x] phetsims/phet-android-app#128 Dark colored version of website within app
- [x] phetsims/phet-android-app#126 Orientation change not triggering column reflow for sim layout
- [x] phetsims/phet-android-app#125 Sim titles not properly wrapping in list view
- [x] phetsims/phet-android-app#123 Layout issues and lack of scrolling on info pages
- [x] phetsims/phet-android-app#120 Cursor does not change when it should
- [x] phetsims/phet-android-app#119 Clicking on bottom bar can enter sims
- [x] phetsims/phet-android-app#117 Empty filter list says simulations are loading
- [x] phetsims/phet-android-app#116 Can's see phet button/view change button if list is too short
- [x] phetsims/phet-android-app#115 Unable to scroll to bottom of list view with filters
- [x] phetsims/phet-android-app#114 Continue button too far down
- [x] phetsims/phet-android-app#113 In-sim favorite button isn't active for favorite sims
- [x] phetsims/phet-android-app#112 Hard to hit info button
- [x] phetsims/phet-android-app#111 Info cut off for sim info if tablet is in portrait mode
- [x] phetsims/phet-android-app#106 Reset Favorites and Update Simulations do nothing
- [x] phetsims/phet-android-app#100 Search bar doesn't deactivate
- [x] phetsims/phet-android-app#97 Some sims don't open

Additionally, please test the app in the spanish locale.  All strings should literally be "xxxx", except for sim titles and descriptions (which should be in spanish if they are translated on phet.colorado.edu). The is for phetsims/phet-android-app#109

<hr>

There are a few issues from last time that aren't fixed yet, including keyboard navigation issues and a couple that have open questions.

@ariel-phet - What is the priority of this test?

**Comment by ariel-phet** [comment]
This is fairly high priority.  I will plan to help out with some testing, @phet-steele will likely be able to also contribute.

**Comment by ariel-phet** [comment]
@mattpen dev test appears complete.
