### ISSUE TITLE
RC Spot Check: Molecules and Light 1.5.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#520]
@KatieWoe, @ariel-phet, @emily-phet, @terracoda @Matthew-Moore240 molecules-and-light/1.5.0-rc.3 is ready for an RC spot check. Please document issues in https://github.com/phetsims/molecules-and-light issues and link to this issue.

This build comes right after rc.2 in #513. Only a few issues needed to be addressed and changes for each were minimal. A full RC is not necessary, but a spot check for each issues and overall test to make sure that things generally look OK would be helpful.

<h3>Simulation Links</h3>

- **[iFrame](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-rc.3/phet/molecules-and-light_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-rc.3/phet/xhtml/molecules-and-light_all.xhtml)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**
- **[a11y View](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-rc.3/phet/molecules-and-light_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-rc.3/phet/molecules-and-light_all_phet.html)**

<h3>Issues to Verify</h3>

- [x] [Xhtml file does not support zoom](https://github.com/phetsims/molecules-and-light/issues/363)
- [x] [Verify that movement during arrow keys and mouse wheel look good](https://github.com/phetsims/molecules-and-light/issues/361)
- [x] [Alt+k and Alt+l work when dialog is open or not using keyboard nav](https://github.com/phetsims/molecules-and-light/issues/359)
- [x] [Zoom commands on radio buttons](https://github.com/phetsims/molecules-and-light/issues/358)

Finally, please make sure that global hotkeys and hotkeys for zoom commands work as expected on a number of different platforms as that was the common area for each of the above issues. Otherwise, the sim was unchanged.

Assigning to @ariel-phet to provide priority for this issue.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome w/ Jaws
- [ ] Win 10 firefox w/ NVDA
- [ ] Win 10 edge
---
- [ ] macOS 10.15 Chrome
- [ ] macOS 10.15 Safari w/ VoiceOver
---
- [ ] Win 10 IE
- [ ] Mac 10.12 Safari
---
- [ ] ChromeOS
- [ ] iPadOS 13 w/ VO

**Comment by KatieWoe** [comment]
@jessegreenberg are these platforms ok?

**Comment by jessegreenberg** [comment]
Can we change Win 10 IE to Win 10 Edge? Otherwise this looks great.

**Comment by jessegreenberg** [comment]
I reviewed the list of blocks-publication issues as of today and https://github.com/phetsims/query-string-machine/issues/42 is the only one that would potentially impact this release.

@kathy-phet @ariel-phet can you please comment on whether that issue should block the release of this sim? Should the `?screens` query parameter have a graceful warning if the value is invalid for *single* screen sims?

**Comment by jessegreenberg** [comment]
Over slack @kathy-phet said
>I don't think anything about the ?screens parameter should block MAL publication.

**Comment by ariel-phet** [comment]
Concurrent top priority with #514 and #515 (particularly since a spot check)

@jessegreenberg might want to consider cherrypicking the fix in:  https://github.com/phetsims/joist/issues/645

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/joist/issues/645 I decided not to cherry-pick changes for that issue because MAL is a single screen sim and does not display the home screen.

**Comment by KatieWoe** [comment]
QA is done.

**Comment by jessegreenberg** [comment]
OK thank you @KatieWoe and team - we are ready for deploy-production and this issue can be closed.
