### ISSUE TITLE
RC test: States of Matter 1.2.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#525]
@KatieWoe , @ariel-phet, @arouinfar, and @kathy-phet - states-of-matter/1.2.0-rc.1 is ready for RC testing.  This includes both phet and phet-io brand and intended to be shared with a client in mid-August.  Document issues in https://github.com/phetsims/states-of-matter/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

Since the phet-io version is being shared with a client who intends to integrate it into a learning environment, the phet-io version should be thoroughly tested.  Also, lots of under-the-hood changes have occurred, so the phet version should get a fair amount of scrutiny too.

<h3>Issues to Verify</h3>

- [x] [Usability on small screens review](https://github.com/phetsims/states-of-matter/issues/243)
- [x] [Particles disappear if pumped above lid](https://github.com/phetsims/states-of-matter/issues/256)
- [x] [Interaction Screen, interaction strength does not change arrows while paused](https://github.com/phetsims/states-of-matter/issues/274)
- [x] [Can't pump particles/too many particles in container](https://github.com/phetsims/states-of-matter/issues/276)
- [x] [Atom on interaction screen no longer line up with atom on the graph](https://github.com/phetsims/states-of-matter/issues/277)
- [x] [Pump stops working when no molecules escape after lid returned](https://github.com/phetsims/states-of-matter/issues/292)
- [x] [Interaction scene pause button doesn't reset](https://github.com/phetsims/states-of-matter/issues/300)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet/states-of-matter_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet/states-of-matter_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet/xhtml/states-of-matter_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/15oDRy4E5kqXxhZVZSfU-EvZvm6eeZKMQAjcU_6B3ExU/edit#gid=333550685)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fstates-of-matter%2F1.2.0-rc.1%2Fphet%2Fstates-of-matter_en_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- For an update or maintenance release please check the backwards compatibility of the playback wrapper.
[Here's the link to the previous wrapper.](link)
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [x] [Studio non-neon movable atoms have non-zero velocity when still](https://github.com/phetsims/states-of-matter/issues/282)
- [ ] [In state wrapper, in launched sim, the lid height isn't recognized](https://github.com/phetsims/states-of-matter/issues/285)
- [ ] [Studio Molecules do not have same start positions when launched/reset](https://github.com/phetsims/states-of-matter/issues/287)
- [x] [State Pressure reads 0 and has no units](https://github.com/phetsims/states-of-matter/issues/297)
- [x] [Should temperature change when lid is blown off](https://github.com/phetsims/states-of-matter/issues/308)
- [ ] [Temperature updates don't work initially when launched from Studio](https://github.com/phetsims/states-of-matter/issues/311)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet-io/)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1Q_CeCwmU7-sHukAs5S6KX6QIym9ECxTl3My8NYzhmuU/edit#gid=731578196)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
Given the aim of getting this sim to the client by mid-August this must be top priority in testing

**Comment by KatieWoe** [comment]
Memory test for normal sim:
![normalmemtest](https://user-images.githubusercontent.com/41024075/89342848-99936680-d660-11ea-8483-002119e17b78.png)
Memory test for phet-io sim:
![phetiomemtest](https://user-images.githubusercontent.com/41024075/89342937-baf45280-d660-11ea-946f-12b64535484b.png)

**Comment by KatieWoe** [comment]
I wanted to note that, while the memory tests are fine, I did notice that a few devices were running a bit harder/fans were running more than I usually see.

**Comment by jbphet** [comment]
@KatieWoe said:

> I wanted to note that, while the memory tests are fine, I did notice that a few devices were running a bit harder/fans were running more than I usually see.

Is there a way that this can be quantified?  I'd suggest running a test where the published version is run in an incognito Chrome window and the CPU usage measured using Windows task manager, then the same test is performed with the RC version.  If the differences are measurable and significant, we can then decide if this warrants additional investigation.

**Comment by KatieWoe** [comment]
Metacog recording test done for Win 10 Chrome and IPadOS 13 Safari.
Safari on iPad seemed to have jumps/small lags when making the recording. I'll leave it to @jbphet and @zepumph to decide if this needs to be addressed.

**Comment by jbphet** [comment]
@KatieWoe said:

> Safari on iPad seemed to have jumps/small lags when making the [Metacog] recording. I'll leave it to @jbphet and @zepumph to decide if this needs to be addressed.

I have absolutely no idea if this matters.  @zepumph - what say you?

**Comment by kathy-phet** [comment]
> @KatieWoe said:
> 
> Safari on iPad seemed to have jumps/small lags when making the [Metacog] recording. I'll leave it to @jbphet and @zepumph to decide if this needs to be addressed.
> 
> I have absolutely no idea if this matters. @zepumph - what say you?

I would say to make an issue for this to track it, but to say "deferred", not RC blocking. We should investigate in situations where we know logging will occur, which is not the case at the moment.

**Comment by KatieWoe** [comment]
Something odd I noticed, but was unable to reproduce:
I was testing the "preview html" feature on studio. I made the html file on the first screen (I thought), and when I loaded up the file, it opened on the second screen. I don't know if this was a bug, I copied something wrong, or I had a forgetful moment and really did make the file on the second screen. I haven't been able to reproduce. Leaving here for documentation.

**Comment by KatieWoe** [comment]
State wrapper seems a bit laggy on old Mac 10.12 device.

**Comment by zepumph** [comment]
>State wrapper seems a bit laggy on old Mac 10.12 device.

I think this may fall into the same category as described in https://github.com/phetsims/states-of-matter/issues/326#issuecomment-673676112. If these performance issues are blocking, we can potentially cherry-pick some improvements into the branch when those issue are marked as complete. But it seems like @kathy-phet may not think of them as blocking.

**Comment by KatieWoe** [comment]
QA is done.

**Comment by jbphet** [comment]
Thanks @KatieWoe and team.  I'll close this and will roll a new RC shortly, since all blocking issues have been addressed.
