### ISSUE TITLE
Android App: Dev Test 5 (1.1.28)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#545]
QA, please conduct another dev test of the android app.
The internal test track version can be installed from this link: https://play.google.com/apps/internaltest/4697762600441754675.

NOTE: Please delete the existing "PhET" app before installing this one. It is OK if the previous production app ("PhET Simulations") is still installed, but previous dev versions of this app can cause problems if they remain.

Please check the following:

- [ ] phetsims/phet-android-app#137 Sometimes a blank screen is seen in the grid view when first opening the app
- [x] phetsims/phet-android-app#135 Favorites heart button response triggered by scrolling
- [x] phetsims/phet-android-app#130 Keyboard nav focus on arrow overlaps oddly with favorite heart
- [x] phetsims/phet-android-app#129 Tab behavior inconsistent
- [ ] phetsims/phet-android-app#123 Layout issues and lack of scrolling on info pages
- [x] phetsims/phet-android-app#120 Cursor does not change when it should
- [x] phetsims/phet-android-app#115 Unable to scroll to bottom of list view with filters
- [x] phetsims/phet-android-app#100 Search bar doesn't deactivate

Additionally, please test the app in the spanish locale. All strings should literally be "xxxx", except for sim titles and descriptions (which should be in spanish if they are translated on phet.colorado.edu). This is for phetsims/phet-android-app#109 - It wasn't clear to me if this was confirmed as successful in https://github.com/phetsims/QA/issues/518

@ariel-phet - What is the priority of this test?

**Comment by ariel-phet** [comment]
@mattpen this is a high priority test to move the app forward, but will mainly be handled by @phet-steele and myself

**Comment by ariel-phet** [comment]
I did the Spanish test, all looks correct. I think we are solid for this dev test. Looking forward to trying out the fixes!

**Comment by mattpen** [comment]
Thanks @ariel-phet and @phet-steele
