### ISSUE TITLE
Android App: Dev Test 6 (1.1.30)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#547]
QA, please conduct another dev test of the android app.
The internal test track version can be installed from this link: https://play.google.com/apps/internaltest/4697762600441754675.

NOTE: Please delete the existing "PhET" app before installing this one. It is OK if the previous production app ("PhET Simulations") is still installed, but previous dev versions of this app can cause problems if they remain.

Please confirm if the following issues are fixed.

- [x] phetsims/phet-android-app#140 Favorite filter AB switch's state is not saved when dragging the button
- [ ] phetsims/phet-android-app#139 Collection view scroll distance resets upon favoriting/unfavoriting
- [x] phetsims/phet-android-app#137 Sometimes a blank screen is seen in the grid view when first opening the app
- [x] phetsims/phet-android-app#136 "Favorites have been reset" message should be more prominent
- [x] phetsims/phet-android-app#130 Keyboard nav focus on arrow overlaps oddly with favorite heart
- [x] phetsims/phet-android-app#129 Tab behavior inconsistent
- [x] phetsims/phet-android-app#123 Layout issues and lack of scrolling on info pages

@ariel-phet - Please assign priority.

**Comment by mattpen** [comment]
Whoops, forgot to publish, please stand by

**Comment by mattpen** [comment]
OK, this test has been published, please proceed.

**Comment by ariel-phet** [comment]
This round of dev testing is complete @mattpen, looking forward to the next one!
