### ISSUE TITLE
RC Spot Check: Build-A-Molecule 1.0.0-rc.3

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#550]
@ariel-phet , @arouinfar, build-a-moelcule/1.0.0-rc.3 is ready for RC testing. This is not to be shared with a client as we are approaching publication. Document issues in https://github.com/phetsims/build-a-molecule/issues and link to this
issue.

This is a spot check of some minor cosmetic changes and performance on iPadOS 13.7. This sim just came out of an RC test cycle with only minor code changes, so we are just wrapping up the test cycle by verifying a few issues. 

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

As noted in https://github.com/phetsims/QA/issues/538#issuecomment-691341921, it was suggested by @ariel-phet to test for crashing behavior on iPadOS 13.7 without any query parameters. An issue should be opened if the sim crashes on iPadOS 13.7 when no query parameters are used. The remaining issues can be verified below.

<h3>Issues to Verify</h3>

- [ ] [iPad reset all button overlaps collection box](https://github.com/phetsims/build-a-molecule/issues/210)
- [x] [Appropriate close button touch area](https://github.com/phetsims/QA/issues/538#issuecomment-691344260) (issue not opened)
- [x] [Graphic failure when using LoL harness](https://github.com/phetsims/build-a-molecule/issues/203)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.3/phet/build-a-molecule_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.3/phet/build-a-molecule_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.3/phet/xhtml/build-a-molecule_all.xhtml)**
- **[Test Matrix](broken link)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Devices/Platforms to spot check:

- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Mac 10.15 Safari
- [ ] iPadOS 14
- [ ] ChromeOS

@Denz1994 is this list alright?

**Comment by Denz1994** [comment]
This list looks good to me. I would just make sure to test iPadOS 14 without query parameters as described above.

> As noted in #538 (comment), it was suggested by @ariel-phet to test for crashing behavior on iPadOS 13.7 without any query parameters. An issue should be opened if the sim crashes on iPadOS 13.7 when no query parameters are used.

**Comment by Denz1994** [comment]
As per request by @ariel-phet, a new spot check should be issued for this sim because of the release of iOS 14. There was a patch that was done in https://github.com/phetsims/build-a-molecule/issues/211 that should be verified. @ariel-phet mentioned he will take a look first and then reassign to QA. Closing this one.
