### ISSUE TITLE
Android App: Dev Test 7 (1.1.33)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#552]
QA, please conduct another dev test of the android app.
The internal test track version can be installed from this link: https://play.google.com/apps/internaltest/4697762600441754675.

NOTE: Please delete the existing "PhET" app before installing this one. It is OK if the previous production app ("PhET Simulations") is still installed, but previous dev versions of this app can cause problems if they remain.

Please confirm if the following issues are fixed.

- [ ] phetsims/phet-android-app#143 Add Content Descriptions to all interactive elements and images (English)
- [x] phetsims/phet-android-app#142 Minor layout issues still present on a few descriptions
- [x] phetsims/phet-android-app#141 Double clicking opens multiple sims
- [x] phetsims/phet-android-app#130 Keyboard nav focus on arrow overlaps oddly with favorite heart
- [x] phetsims/phet-android-app#129 Tab behavior inconsistent
- [x] phetsims/phet-android-app#122 Sim titles and descriptions not responding to locale change on the device

@ariel-phet - Please assign priority.

**Comment by mattpen** [comment]
New version coming in momentarily, please hold

**Comment by mattpen** [comment]
OK, the test can proceed.

**Comment by KatieWoe** [comment]
I'm not seeing Natural Selection show up for me. Is it not being downloaded for anyone else?

**Comment by KatieWoe** [comment]
It did download after I uninstalled, rebooted, and reinstalled.

**Comment by ariel-phet** [comment]
@mattpen this round of testing is complete

**Comment by KatieWoe** [comment]
Removing Priority tag if this test is done

**Comment by mattpen** [comment]
Complete.
