### ISSUE TITLE
RC test: Energy Forms and Changes 1.4.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#556]
@KatieWoe, @arouinfar, @ariel-phet, @kathy-phet, energy-forms-and-changes/1.4.0-rc.2 is ready for RC testing. The phet-io version of this release will be shared with a client. The publication due date is October 1st. This is the 2nd release from the 1.4 release branch, but the code changes since the previous release were quite significant, so a full retest is needed.  There are also several fixed issues that should be checked (these are listed in two of the sections below).  Please document issues in https://github.com/phetsims/energy-forms-and-changes/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.2 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Issues to Verify</h3>

- [x] [Water temp has delayed reset on second screen](https://github.com/phetsims/energy-forms-and-changes/issues/343)
- [x] [Water energy chunks boil far too early when biker runs out of food](https://github.com/phetsims/energy-forms-and-changes/issues/346)
- [x] [Energy chunks don't appear in falling water if faucet is off](https://github.com/phetsims/energy-forms-and-changes/issues/347)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.0-rc.2/phet/energy-forms-and-changes_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.0-rc.2/phet/energy-forms-and-changes_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.0-rc.2/phet/xhtml/energy-forms-and-changes_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/19WAm2BOsEg1f8XCLo-PT8eQsGgb3uR9Npt6obPrMiA4/edit#gid=1313829856)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- For an update or maintenance release please check the backwards compatibility of the playback wrapper.
[Here's the link to the previous wrapper.](link)
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.
- Conduct a memory test on the stand alone sim wrapper.

<h3>Focus and Special Instructions</h3>

Please pay close attention to loading/setting state (hitting "launch" in Studio), especially on the second screen. Because of some implementation decisions, the loaded state may not match perfectly for all cases, but please bring any behavior that is unexpected to my attention. I think @KatieWoe is getting pretty familiar with what to expect for state on this sim, but feel free to Slack me any time with questions, or make an issue. Thanks!

<h3>Issues to Verify</h3>

- [x] [Tea kettle energy chunk preloading](https://github.com/phetsims/energy-forms-and-changes/issues/336)
- [x] [Second screen state](https://github.com/phetsims/energy-forms-and-changes/issues/306)
- [x] [Feed Me button is pressed when launched](https://github.com/phetsims/energy-forms-and-changes/issues/335)
- [x] [Hiding Buttons on Second Screen Hides Connected Element as Well](https://github.com/phetsims/energy-forms-and-changes/issues/348)
- [x] [screen 1 blocks and beakers emitted chunks don't work in state](https://github.com/phetsims/energy-forms-and-changes/issues/361)
- [x] [Studio launch doesn't restore EnergyChunk state like the state wrapper](https://github.com/phetsims/energy-forms-and-changes/issues/362)
- [x] [Memory leak in the view when setting state](https://github.com/phetsims/energy-forms-and-changes/issues/368)
- [x] [Water from faucet can have gaps and other odd-looking behavior](https://github.com/phetsims/energy-forms-and-changes/issues/369)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.0-rc.2/phet-io/)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/17FYYm5Halt8VVi4vMIsjGsrtELD317S5f0zNUdWqt-A/edit#gid=1474718953)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jbphet** [comment]
One other thing to check:

- [ ] verify that https://github.com/phetsims/natural-selection/issues/243 does not occur for energy chunks

**Comment by KatieWoe** [comment]
Energy chunks seem to show up fine after a quick test. I'll keep an eye out as testing goes on, but it looks like it doesn't impact this sim there.

**Comment by KatieWoe** [comment]
Memory test for PhET brand:
![Screen Shot 2020-09-25 at 4 31 58 PM](https://user-images.githubusercontent.com/41024075/94323130-d63d5900-ff51-11ea-882b-015ea618e87a.png)
Memory test for PhET-iO brand:
![Screen Shot 2020-09-25 at 5 08 39 PM](https://user-images.githubusercontent.com/41024075/94323145-e7866580-ff51-11ea-83e9-e1076a72b65a.png)
Looks like there might be a memory leak, but relatively slow. @jbphet let me know if you want an issue for it.

**Comment by jbphet** [comment]
@KatieWoe - yes, please log an issue for this.  We should have a separate investigation for it, and a record thereof.

**Comment by KatieWoe** [comment]
Colorized seemed to be very slow on Mac 10.15 Chrome

**Comment by KatieWoe** [comment]
Calling an end to QA for this round.

**Comment by jbphet** [comment]
Thanks QA team.  We will disposition and address the issues listed above individually.  Closing this one.
