### ISSUE TITLE
RC test: Natural Selection 1.2.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#557]
@amanda-phet, @kathy-phet, @ariel-phet, @oliver-phet, @KatieWoe natural-selection/1.2.0-rc.2 is ready for RC testing.  

This RC is for the deliverable described in https://github.com/phetsims/natural-selection/issues/208.  Deadlines are:
* testing of this RC should be completed by Monday 9/28/2020
* delivery of an RC version to the client by Thursday 10/1/2020

Document issues in https://github.com/phetsims/natural-selection/issues and link to this issue.

This RC test is a spot check for the issues listed in "Issues to Verify".  Also please spot check on these platforms:

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.
</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- **N/A** For an update or maintenance release please check the backwards compatibility of the playback wrapper.
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.
- Conduct a memory test on the stand alone sim wrapper (rc.1).
- Test one platform combination with `?phetioDebug` on the Studio and State wrapper.

<h3>Issues to Verify</h3>

- [x] [Reset All in launched sim creates "Add a Mate" button when it shouldn't ](https://github.com/phetsims/natural-selection/issues/235)
- [x] [populationPanel.visibleProperty mistakenly not featured](https://github.com/phetsims/natural-selection/issues/236)
- [x] [Launched Sim on iPadOS 14.0 takes up more than full screen](https://github.com/phetsims/natural-selection/issues/237)
- [x] [Typo in client-requests.md](https://github.com/phetsims/natural-selection/issues/241)
- [x] [Bunnies may not show up when sim is launched while paused (Safari 14.0)](https://github.com/phetsims/natural-selection/issues/243)

**The above issues need to be verified on 1 platform. See the last comment in each issue for specific instructions. Please indicate (in the issue) which platform and test device was used to verify.**

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/natural-selection/1.2.0-rc.2/phet-io/)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1N8A9D6N_su5OD4hVJ7MUEb_kg0SFeJDCxUGVy3XS5kI/edit#gid=329790950)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done with spot check

**Comment by pixelzoom** [comment]
Thanks @KatieWoe and QA team!

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/natural-selection/issues/208#issuecomment-699641109:
> @kathy-phet 1.2 RC testing has been completed, and 1.2.0-rc.2 is acceptable for delivery to the client. The link is: https://phet-dev.colorado.edu/html/natural-selection/1.2.0-rc.2/phet-io/

Closing.
