### ISSUE TITLE
Android App: RC Test (1.1.36)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#558]
QA, please conduct another dev test of the android app.
The internal test track version can be installed from this link: https://play.google.com/apps/internaltest/4697762600441754675.

NOTE: Please delete the existing "PhET" app before installing this one. It is OK if the previous production app ("PhET Simulations") is still installed, but previous dev versions of this app can cause problems if they remain.

Please confirm if the following issues are fixed.

- [x] https://github.com/phetsims/phet-android-app/issues/143 Add Content Descriptions to all interactive elements and images (English)
- [x] https://github.com/phetsims/phet-android-app/issues/129 Tab behavior inconsistent
- [ ] https://github.com/phetsims/phet-android-app/issues/109 Localize App Strings
- [x] https://github.com/phetsims/phet-android-app/issues/152 Test update system for localized sims 

Additionally, please do a robust test of the update system.  Verify that new sims, updates to existing sims, and translations are all received in the app within about 24 hours.

@ariel-phet - please assign priority

**Comment by ariel-phet** [comment]
I have not tested all locales extensively, but Spanish was showing up for me perfectly in terms of localized app strings (as one data point).

**Comment by mattpen** [comment]
Is this round of testing finished?  It looks like the only thing left to test for the build to be ready for production is the zh_CN strings and possible the Basque(eu) locale.  

QA, can you please provide an update? Are you still testing the app?

**Comment by KatieWoe** [comment]
@phet-steele has been focusing here. He would have a better estimate than me at the moment so I'll pass this question to him.

**Comment by phet-steele** [comment]
@mattpen I was hoping someone could figure out how to test Basque (my ways have failed), but otherwise yes I think this round of testing is complete.

**Comment by mattpen** [comment]
@phet-steele - I was able to test it on my device by selecting "Euskara" in the languages.  Do you have this option?

**Comment by phet-steele** [comment]
@mattpen what I see when I go to "Add languages" is "Basque - euskara". That's my only option, so I select it. There is no "Euskara" on its own. After that, the next step would be to click on the kebab menu for Basque and select: "Show system text in this language", but that checkbox is not selectable on my device.

**Comment by mattpen** [comment]
I tested the app in Euskara on my device and it worked fine (lots of other apps didn't!).  Let's consider this test complete.

**Comment by KatieWoe** [comment]
Removing priority tag as this test id done.

**Comment by KatieWoe** [comment]
Can this be closed?
