### ISSUE TITLE
Dev test: Collision Lab 1.1.0-dev.10

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#562]
@ariel-phet, @arouinfar, collision-lab/1.1.0-dev.10 is ready for dev testing. Document issues in https://github.com/phetsims/collision-lab/issues and link to this
issue. I'll deploy a dev version once I'm informed that QA is ready!

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

- [x] [Tunneling ball in 1D collisions](https://github.com/phetsims/collision-lab/issues/122)
- [x] [Input calculator does not clear when switched or reset](https://github.com/phetsims/collision-lab/issues/165)
- [x] [Collision can push ball out of reflecting border](https://github.com/phetsims/collision-lab/issues/171)

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.10/phet/collision-lab_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jonathanolson** [comment]
Published https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.10/phet/collision-lab_all_phet.html for this, should be ready for testing.

**Comment by DevonQui** [comment]
I just tested issue #176 on Explore 1D as well and I was able to produce about 109 million joules. In addition, the balls began slipping past each other because of the high speeds. The problem only happens with elastic collisions and a reflecting border and, as a result, I was unable to reproduce the bug in the Inelastic and Intro sections.

**Comment by KatieWoe** [comment]
QA is done
