### ISSUE TITLE
RC Spot Check: Build-A-Molecule 1.0.0-rc.4

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#563]
@ariel-phet , @arouinfar, build-a-molecule/1.0.0-rc.4 is ready for RC testing. This test is following an incomplete spot-check due to the release of iOS14. Document issues in https://github.com/phetsims/build-a-molecule/issues and link to this
issue. Assigning to @ariel-phet for prioritization.

This is a spot check to verify a few issues and special attention should be given to iOS 14.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

Please pay attention to testing on iOS 14. This is a new release so issues like https://github.com/phetsims/build-a-molecule/issues/211 may arise.

<h3>Issues to Verify</h3>

- [x] [iPadOS 14 Molecules in 3D view don't show up](https://github.com/phetsims/build-a-molecule/issues/211): @ariel-phet mentioned that he would initially take a look at this one.

- [x] [Completing a level while viewing a previous level will not allow you to proceed](https://github.com/phetsims/build-a-molecule/issues/212)
- [x] [iPad reset all button overlaps answer box](https://github.com/phetsims/build-a-molecule/issues/210)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.4/phet/build-a-molecule_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.4/phet/build-a-molecule_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.4/phet/xhtml/build-a-molecule_all.xhtml)**
- **[Test Matrix](broken link)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe since this is a spot check and we really want to get this sim published, lets aim to finish off the test by end of business this Friday (I feel like testing should be pretty quick to verify the current issues).

**Comment by KatieWoe** [comment]
Platforms to test on:
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Mac 10.15 Safari
- [ ] iOS 14 Safari
- [ ] ChromeOS

**Comment by KatieWoe** [comment]
QA is done

**Comment by Denz1994** [comment]
Thanks a bunch, QA for the quick turnaround on the last two tests. @ariel-phet will verify https://github.com/phetsims/build-a-molecule/issues/212 and then we can close this one after verification.

**Comment by phet-steele** [comment]
> verify [phetsims/build-a-molecule#212](https://github.com/phetsims/build-a-molecule/issues/212) and then we can close this one after verification.

That issue has been verified, so I'm closing.
