### ISSUE TITLE
RC Test: Capacitor-Lab-Basics 1.7.0-rc.5

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#565]
@ariel-phet , @arouinfar , Capacitor-Lab-Basics/1.7.0-rc.5 is ready for RC testing. We are picking up from RC shas from mid 2019 so we would like to do a full RC test and verify some issues. This sim has gone through a few RC cycles already, but please pay attention to any platform-dependent testing since our supported platforms have changed since the last cycle. 

There was also a maintenance release done targeting support for iOS13 devices, so the related issue below will need attention dedicated to that specific platform.

Document issues in https://github.com/phetsims/capacitor-lab-basics/issues and link to this issue.

Assigning to @ariel-phet for prioritization. I'd also ask that @ariel-phet determine if this sim requires an RC-lite or full RC test.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Issues to Verify</h3>

- [x] [Maintenance patches applied to branch 1.7](https://github.com/phetsims/capacitor-lab-basics/issues/271)
     - There were two patches made to sims (fullscreen and highlight behavior) that are documented in this issue. Both should be verified.
- [x] [Voltmeter is behind the pause/speed panel](https://github.com/phetsims/capacitor-lab-basics/issues/270)
     - Confirm z-ordering is correct
- [x] [Short strings are centered](https://github.com/phetsims/capacitor-lab-basics/issues/266)
     - Short strings shouldn't look funky. Specifically within the panels.
- [x] [Charge in top plate changes inappropriately](https://github.com/phetsims/capacitor-lab-basics/issues/256)
     - There are two comments with steps that should be verified. [First](https://github.com/phetsims/capacitor-lab-basics/issues/256#issue-432705885) sequence and the [second](https://github.com/phetsims/capacitor-lab-basics/issues/256#issuecomment-495709373) sequence of steps.

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.5/phet/capacitor-lab-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.5/phet/capacitor-lab-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.5/phet/xhtml/capacitor-lab-basics_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1E_HoXYhttDYPm5HT01e54N6S9m9T1XqUk-w2kIKfngI/edit#gid=129703379)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
Moving to current top priority as it would be good to finish off this test before some other high priority tests enter the pipeline

**Comment by KatieWoe** [comment]
QA is done

**Comment by Denz1994** [comment]
Closing this issue due to https://github.com/phetsims/QA/issues/588. Thanks, QA for the hard work.
