### ISSUE TITLE
RC-Lite test: Gravity and Orbits 1.2.0-rc.2 with PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#567]
@ariel-phet, @arouinfar, @kathy-phet, @KatieWoe, gravity-and-orbits/1.2.0-rc.2 is ready for RC-lite testing.  This is for a client, and is one of their top priority projects.  Document issues in https://github.com/phetsims/gravity-and-orbits/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

This is an RC-lite test for the PhET-iO version, which will be delivered to the client once testing has passed.  Prior 
testing was completed in https://github.com/phetsims/QA/issues/519

<h3>Issues to Verify</h3>

- [x] [Possible for time readout to overlap control pannel](https://github.com/phetsims/gravity-and-orbits/issues/359)
- [ ] [Long strings leave artifacts behind on To Scale Screen](https://github.com/phetsims/gravity-and-orbits/issues/358)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

Links will be provided once the version has been built.  There are still some blocks-publication or blocks-sim-publication
issues that need to be addressed first.

- **[Simulation](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-rc.2/phet/gravity-and-orbits_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-rc.2/phet/gravity-and-orbits_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-rc.2/phet/xhtml/gravity-and-orbits_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1U61MmzaK2YR1MvtvBo1vYZ4zkEpwNroxhbtdhOgNEPs/edit#gid=2139714459)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- For an update or maintenance release please check the backwards compatibility of the playback wrapper.
[Here's the link to the previous wrapper.](link)
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.
- Conduct a memory test on the stand alone sim wrapper (rc.1).
- Test one platform combination with `?phetioDebug` on the Studio and State wrapper.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [ ] [Measuring Tape does not move in State wrapper](https://github.com/phetsims/gravity-and-orbits/issues/362)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-rc.2/phet-io)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1MiLr45_vxmzBlu88343uG3OV-_Pb7qRBAMRTIZKVPhE/edit#gid=1192527716)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by samreid** [comment]
I published 1.2.0-rc.2 and added the URLs.  I also moved it to "Active Tests".  Reassigning to @KatieWoe so she is aware this is ready, and also assigning @ariel-phet in case any changes to priority/label/assignment are necessary.

**Comment by KatieWoe** [comment]
Should the accessibility section be removed? I don't think it has any of the listed features.

**Comment by samreid** [comment]
Thanks, I removed the accessibility section.

**Comment by KatieWoe** [comment]
Not sure if this is actually a bug, so let me know if you want an issue made @samreid. Some of the changes mentioned in https://github.com/phetsims/QA/issues/572 are here. Specifically the orientation of the clear button. I also noticed that the color when the buttons aren't available is different now. Is this intended?
![Screen Shot 2020-11-03 at 3 13 38 PM](https://user-images.githubusercontent.com/41024075/98046982-69d33680-1de8-11eb-943d-6d5e37f97c8f.png)

**Comment by samreid** [comment]
> Specifically the orientation of the clear button. I also noticed that the color when the buttons aren't available is different now. 

Can you clarify what you mean by the "orientation"?  

@pixelzoom or @zepumph or @jonathanolson can you please comment on the status of grayscale for disabled buttons?

**Comment by zepumph** [comment]
>@pixelzoom or @zepumph or @jonathanolson can you please comment on the status of grayscale for disabled buttons?



Tracked in https://github.com/phetsims/sun/issues/658, I'm sorta out of the conversation, and I don't know if this blocks GAO publication. @ariel-phet, what steps need to be taken to make sure that GAO can be published? Currently it uses the "opacity" strategy from master/recent work in sun. Do we need to wait on a greyscale implementation, or talk to designers?

**Comment by pixelzoom** [comment]
@jonathanolson is working on filtering features (including grayscale) for scenery with high priority in https://github.com/phetsims/scenery/issues/707#issuecomment-717604465.  You'll have to ask @jonathanolson or @ariel-phet about when the scenery grayscale feature is expected to be added to sun buttons.

**Comment by KatieWoe** [comment]
@samreid 
> Can you clarify what you mean by the "orientation"?

It used to be centered under it's label. Now it is right justified.

**Comment by arouinfar** [comment]
@KatieWoe the alignment of the Clear button was an intention change, see https://github.com/phetsims/gravity-and-orbits/issues/359#issuecomment-697054951.

**Comment by samreid** [comment]
@jonathanolson indicated he is nearly ready to commit "grayscale" disabled support to master for https://github.com/phetsims/scenery/issues/707#issuecomment-717604465, should I invalidate this test and create a new one once that is ready?

**Comment by samreid** [comment]
@arouinfar recommends to pause RC testing on this version until @ariel-phet or @kathy-phet comments on whether we want grayscale in the upcoming release.  Also, @jonathanolson can you comment on how modular/straightforward the changes are?  Will they invalidate testing and require significant re-testing?

**Comment by samreid** [comment]
After discussion with @arouinfar, @ariel-phet recommended halting this RC testing until we have the grayscale enabled components.  I'll deprioritize and move it to another column in the project.
