### ISSUE TITLE
Dev Test: Faraday's Law 1.4.0-dev.65

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#568]
@KatieWoe and @emily-phet - faradays-law/1.4.0-dev.65 is ready for dev testing. This test is being done in an effort to find major issues prior to starting the RC process.  Since the last major release of this simulation, sound, keyboard navigation, zoom & pan, and keyboard help have been added, and the ability to hide and show the voltmeter has been added (the voltmeter is now initially invisible).  Description has _not_ been finalized, so screen readers should not be tested.  

https://github.com/phetsims/faradays-law/issues

Please look for any major issues that should be addressed prior to republication.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

- [x] [Implement sound design](https://github.com/phetsims/faradays-law/issues/161)

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_en_phet.html
)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) Dev Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature testing doesn't negatively affect the sim in any way.
- Load the a11y view and make sure that interacting with all elements in the simulation updates the appropriate
descriptions in the PDOM.

<h3>Focus and Special Instructions</h3>

Test keyboard nav.

<h3>Issues to Verify</h3>

- [x] [Add keyboard help dialog](https://github.com/phetsims/faradays-law/issues/176)
- [x] [Add alternative input to this sim](https://github.com/phetsims/faradays-law/issues/174)

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_all_phet.html)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
Thanks QA team.  I'll address the individual issues separately.  Closing.
