### ISSUE TITLE
RC Test: Faraday's Law 1.4.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#581]
@KatieWoe, @emily-phet, and @arouinfar - faradays-law/1.4.0-rc.1 is ready for RC testing. To meet deadlines for a grant, we would like to be able to publish this simulation before the end of this year.  Document issues in https://github.com/phetsims/faradays-law/issues and link to this issue.

This release adds sound, keyboard navigation, pinch-and-zoom, and some initial description to the simulation.  It is the first RC with these features, so it should be thoroughly tested on all supported platforms.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

The primary focus should be on the new features, i.e. sound, keyboard nav, pinch-and-zoom, and basic description.  However, a lot of other portions of the sim have been changed since the last publication, so a thorough test of all features is warranted.

<h3>Issues to Verify</h3>

- [x] [Add alternative input to this sim](https://github.com/phetsims/faradays-law/issues/174)
- [x] [Magnet can go through coils when dragged quickly](https://github.com/phetsims/faradays-law/issues/195)
- [x] [1, 2, and 3 buttons don't change magnet direction if magnet caught on object](https://github.com/phetsims/faradays-law/issues/196)
- [x] [Magnet jumps to the side of wire coil when sim is slow](https://github.com/phetsims/faradays-law/issues/200)
- [x] [Can't drag magnet with mouse immediately after grabbing or dragging with keyboard](https://github.com/phetsims/faradays-law/issues/201)
- [x] [Auto-slide doesn't stop if magnet grabbed while moving](https://github.com/phetsims/faradays-law/issues/203)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.1/phet/faradays-law_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.1/phet/faradays-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.1/phet/xhtml/faradays-law_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1IURADK9kRbOACfz5k5f3biYMmFqw-BLsAHiz7fW8gr0/edit#gid=1482074334https://docs.google.com/spreadsheets/d/1IURADK9kRbOACfz5k5f3biYMmFqw-BLsAHiz7fW8gr0/edit#gid=1482074334)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Ffaradays-law%2F1.4.0-rc.1%2Fphet%2Ffaradays-law_en_phet.html)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Focus and Special Instructions</h3>

This release is primarily focused on accessibility-related features, so these should get special attention.  Keyboard navigation and sound are the highest priorities.  The implementation of description is limited, so it should be tested to make sure that it isn't broken or incorrect, but not for its coverage of the topic area.

<h3>Issues to Verify</h3>

See it "Issues to Verify" section in the main section above.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.1/phet/faradays-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.1/phet/faradays-law_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1IURADK9kRbOACfz5k5f3biYMmFqw-BLsAHiz7fW8gr0/edit#gid=1482074334)**

<h3>Screen Readers</h3>

This sim supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have
all of the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the
a11y view before opening the simulation. Once you've done that, open the simulation and make sure alerts and
descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [ ] Windows 10 + Latest Chrome + Latest JAWS
- [ ] Windows 10 + Latest Firefox + Latest NVDA
- [ ] macOS + Safari + VoiceOver
- [ ] iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory test looks good:
<img width="418" alt="memtest" src="https://user-images.githubusercontent.com/41024075/101203239-9f598280-3627-11eb-8e63-5d32c4b22f3c.png">

**Comment by jessegreenberg** [comment]
@KatieWoe, I don't think we need to be testing description for this release. Description wasn't prepared in this version and I don't think we will be listing this as a sim that supports interactive descriptions on the website. So I don't think any further testing should be done with screen readers.

@emily-phet @terracoda or @jbphet can you confirm that this is the case?

**Comment by KatieWoe** [comment]
QA is done
