### ISSUE TITLE
RC Spot Check: Faraday's Law 1.4.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#585]
@KatieWoe, @emily-phet, and @arouinfar - faradays-law/1.4.0-rc.2 is ready for RC testing.  This is the 2nd RC for the 1.4 release branch, and only a few issues were found with the first RC, so a "spot check" RC test that focuses on verifying the identified issues should be sufficient.

To meet deadlines for a grant, we would like to be able to publish this simulation before the end of this year.

Document issues in https://github.com/phetsims/faradays-law/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

The primary focus should be on the new features, i.e. sound, keyboard nav, pinch-and-zoom, and basic description.  However, a lot of other portions of the sim have been changed since the last publication, so a thorough test of all features is warranted.

<h3>Issues to Verify</h3>

- [x] [1, 2, and 3 buttons don't change magnet direction if magnet caught on object](https://github.com/phetsims/faradays-law/issues/196)
- [x] [Screen Reader reads out "dot dot" during scene description of magnet location](https://github.com/phetsims/faradays-law/issues/209)
- [x] [Magnet can go through the "borders" in all parts of sim](https://github.com/phetsims/faradays-law/issues/205)
- [x] [Updating sim credits](https://github.com/phetsims/faradays-law/issues/189)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.2/phet/faradays-law_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.2/phet/faradays-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.2/phet/xhtml/faradays-law_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1IURADK9kRbOACfz5k5f3biYMmFqw-BLsAHiz7fW8gr0/edit#gid=1482074334https://docs.google.com/spreadsheets/d/1IURADK9kRbOACfz5k5f3biYMmFqw-BLsAHiz7fW8gr0/edit#gid=1482074334)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Ffaradays-law%2F1.4.0-rc.2%2Fphet%2Ffaradays-law_en_phet.html)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).

<h3>Focus and Special Instructions</h3>

This release is primarily focused on accessibility-related features, so these should get special attention.  Keyboard navigation and sound are the highest priorities.  The implementation of description is limited, so it should be tested to make sure that it isn't broken or incorrect, but not for its coverage of the topic area.

<h3>Issues to Verify</h3>

See it "Issues to Verify" section in the main section above.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.2/phet/faradays-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.2/phet/faradays-law_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1IURADK9kRbOACfz5k5f3biYMmFqw-BLsAHiz7fW8gr0/edit#gid=1482074334)**

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Mac 11 Safari
- [ ] iPadOS 14
- [ ] ChromeOS

@jbphet is this an alright list?

**Comment by jbphet** [comment]
> @jbphet is this an alright list?

Sure.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
Thanks QA team - I'll address the individual issues reported and will close this one.
