### ISSUE TITLE
RC Test: Capacitor-Lab-Basics 1.7.0-rc.8

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#588]
@ariel-phet , @arouinfar , Capacitor-Lab-Basics/1.7.0-rc.8 is ready for RC a spot check. Document issues in https://github.com/phetsims/capacitor-lab-basics/issues and link to this
issue. This RC should fit into the active test queue when possible. There are several issues to verify being that this sim has gone through several RC tests already. The version number doesn't match the number of RC tests due to some intermediate RC builds that didn't get tested.

I'd advise treating this test as a spot check to verify the outstanding issues listed below.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

Please pay close attention to the top plate charge on the second screen, specifically as detailed in this [issue](https://github.com/phetsims/capacitor-lab-basics/issues/256#issuecomment-710621089). 

<h3>Issues to Verify</h3>

- [x] [Maybe have Pause and Step Forward buttons as well as plate size and distance arrows visible through light?](https://github.com/phetsims/capacitor-lab-basics/issues/276)
- [x] [Light possibly too bright?](https://github.com/phetsims/capacitor-lab-basics/issues/275)
- [x] [Charge in top plate changes inappropriately](https://github.com/phetsims/capacitor-lab-basics/issues/256)
- [x] [Current options should be disabled when current is not shown](https://github.com/phetsims/capacitor-lab-basics/issues/278)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.8/phet/capacitor-lab-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.8/phet/capacitor-lab-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.8/phet/xhtml/capacitor-lab-basics_all.xhtml)**
- **[Test Matrix](broken link)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Spot check platforms:
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] MacOS 11 Safari
- [ ] iPadOS 14 Safari
- [ ] ChromeOS

**Comment by kathy-phet** [comment]
Changing this to top priority to get @Denz1994 issues to comment on or resolve before he leaves. Please prioritize this test.

**Comment by arouinfar** [comment]
@KatieWoe it sounds like the numbers are shifting slightly which is to be expecting because we aren't using a monospaced font. If that's the case, no need for an issue. If the numbers are bouncing out of bounds or doing something really buggy looking, please open an issue.

**Comment by KatieWoe** [comment]
@arouinfar not out of bounds. It was sometimes more than I expected, but it was hard to replicate. Like I said, I don't really think it needs an issue.

**Comment by KatieWoe** [comment]
QA is done

**Comment by arouinfar** [comment]
There are five issues in the repo that need attention before the upcoming release, and most are trivial. I've commented in the issues, but to summarize:

* https://github.com/phetsims/capacitor-lab-basics/issues/281 is a bug that should be addressed and is the only issue that might be tricky.
* https://github.com/phetsims/capacitor-lab-basics/issues/280 and https://github.com/phetsims/capacitor-lab-basics/issues/276 relate to minor z-ordering issues. 
* https://github.com/phetsims/capacitor-lab-basics/issues/277 can be deferred or closed as wontfix.
* https://github.com/phetsims/capacitor-lab-basics/issues/276 is a trivial constant change.

**Comment by jonathanolson** [comment]
Thanks! I've got them on my radar, will be working on it!
