### ISSUE TITLE
Dev test: Collision Lab 1.1.0-dev.13

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#594]
@ariel-phet, @arouinfar, collision-lab/1.1.0-dev.13 is ready for dev testing. Document issues in https://github.com/phetsims/collision-lab/issues and link to this
issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

- [x] [Tunneling ball in 1D collisions](https://github.com/phetsims/collision-lab/issues/122)
- [x] [User reported issue: collide ball outside of reflecting border](https://github.com/phetsims/collision-lab/issues/150)
- [x] [Input calculator does not clear when switched or reset](https://github.com/phetsims/collision-lab/issues/165)
- [x] [Collision can push ball out of reflecting border](https://github.com/phetsims/collision-lab/issues/171)
- [x] [Balls can overlap when adding additional ball](https://github.com/phetsims/collision-lab/issues/179)
- [x] [Layering on balls/velocity arrow is not reset](https://github.com/phetsims/collision-lab/issues/180)
- [x] [Buffering between toolbox and reset all button](https://github.com/phetsims/collision-lab/issues/181)
- [x] [Balls may still have velocity if they read 0](https://github.com/phetsims/collision-lab/issues/182)
- [x] [Unable to step back inelastic collisions looks buggy](https://github.com/phetsims/collision-lab/issues/183)

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.13/phet/collision-lab_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe since this sim has been through several dev tests, the main focus should be on verifying the issues noted above and then doing some checking that no new bugs have been introduced related to those fixes. However, I do not think this dev test needs to be as extensive as an "initial" test of the sim as we would like to move this towards publication. So after verifying issues, an hour or two test per platform should be more than sufficient.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thank you!
