### ISSUE TITLE
RC Test: Number Line: Operations 1.0.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#600]
@amanda-phet, @KatieWoe, and @kathy-phet - number-line-operations/1.0.0-rc.1 is ready for RC testing. This is the first
RC for this sim, though two dev tests have already been done, so a thorough test on all supported platforms is necessary.
Please log issues in https://github.com/phetsims/number-line-operations/issues.

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
    - Test all mouse/trackpad inputs.
    - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
  for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
  spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
  there is a problem.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [x] [Operation off scale message and text box behave oddly with long strings](https://github.com/phetsims/number-line-operations/issues/87)
- [x] [Alignment of ring and value looks off (Net Worth screen)](https://github.com/phetsims/number-line-operations/issues/86)
- [x] [Screenshots take longer on last two screens](https://github.com/phetsims/number-line-operations/issues/78)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-rc.1/phet/number-line-operations_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-rc.1/phet/number-line-operations_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-rc.1/phet/xhtml/number-line-operations_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1sEywoj1JDF-cY8P0lxqt9KpmjMszJ2-261Y0lhqkasM/edit#gid=82774060)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fnumber-line-operations%2F1.0.0-rc.1%2Fphet%2Fnumber-line-operations_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory test looks ok:
<img width="392" alt="memtest" src="https://user-images.githubusercontent.com/41024075/106201696-0f8f0b00-6176-11eb-9c24-4988826ba016.png">

**Comment by KatieWoe** [comment]
Some screenshots look a bit fuzzy, but I'm not sure it's issue worthy. Let me know if you think it is @jbphet 
![Number Line_ Operations screenshot](https://user-images.githubusercontent.com/41024075/106327702-d4efa600-623b-11eb-9e92-3dd9c3270576.png)

**Comment by jbphet** [comment]
@KatieWoe - It doesn't look particularly fuzzy to me.  Are you referring to the bag just under the number line, the screenshot in general, or something else?

**Comment by KatieWoe** [comment]
The bag, and the chips in the icon image

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
Thanks team.  I'll close this and follow up on the individual issues.
