### ISSUE TITLE
RC Test: Collision Lab 1.1.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#607]
@kathy-phet, @arouinfar, collision-lab/1.1.0-rc.2 is ready for RC testing. Document issues in https://github.com/phetsims/collision-lab/issues and link to this
issue.

This includes some changes to some of the internal physics handling, so extra testing around that interaction would be helpful.

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Issues to Verify</h3>

- [x] [Small orbs can be hard to grab](https://github.com/phetsims/collision-lab/issues/192)
- [x] [Not all of accordion panel is clickable](https://github.com/phetsims/collision-lab/issues/195)
- [x] [Blue reset button slightly incorrect location when long strings used](https://github.com/phetsims/collision-lab/issues/197)
- [x] [Path continues after leaving play area](https://github.com/phetsims/collision-lab/issues/198)
- [ ] [Path experiences glitchy behavior when ball is moved and other ball has left screen](https://github.com/phetsims/collision-lab/issues/200)
- [x] [Dragging or altering balls sometimes pauses sim](https://github.com/phetsims/collision-lab/issues/201)
- [x] [Freezing behavior when stepping back with inelastic behavior.](https://github.com/phetsims/collision-lab/issues/203)
- [x] [Multitouch dragging objects during reset can lead to unintended positions](https://github.com/phetsims/collision-lab/issues/204)
- [ ] [Rewinding doesn't handle initial collision for touching balls](https://github.com/phetsims/collision-lab/issues/205)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/collision-lab/1.1.0-rc.2/phet/collision-lab_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/collision-lab/1.1.0-rc.2/phet/collision-lab_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/collision-lab/1.1.0-rc.2/phet/xhtml/collision-lab_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1uF3dGaD5OcF4Raqf7Z65WCi3buyoSAIB1RLCblaL7Ck/edit#gid=1263030635)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jessegreenberg** [comment]
@jonathanolson @KatieWoe colision-lab 1.1 scenery SHAs received https://github.com/phetsims/scenery/commit/4d8219d1096d4dd46e928044f4b97ec56b281c98 for https://github.com/phetsims/phet-android-app/issues/155.

If possible, please check that this sim works in the PhET Android app as part of this test.

**Comment by KatieWoe** [comment]
@jessegreenberg the method of testing unpublished sims likely wont be set until Tuesday. I will hopefully be able to do this check after this.

**Comment by KatieWoe** [comment]
QA is done aside from https://github.com/phetsims/QA/issues/607#issuecomment-777983020

**Comment by jonathanolson** [comment]
Thanks!
