### ISSUE TITLE
Circuit Construction Kit: DC & DC-Virtual Lab 1.2.2-rc.2 Release Candidate with Resistance/Resistivity improvements

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#633]
In https://github.com/phetsims/circuit-construction-kit-common/issues/687 we made improvements for the resistance and resistivity, to solve the issues listed in the milestone: https://github.com/phetsims/circuit-construction-kit-common/milestone/3

There was a recent RC for DC, and a subsequent re-release, so it has fairly recent SHAs.  We just need a spot check for the issues and a sanity test that nothing unexpected was disturbed.

There was a problem in RC.1, but RC2 is ready to go:
https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.2-rc.2/phet/circuit-construction-kit-dc_en_phet.html
https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.2-rc.2/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html

- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/676 Battery resistance should not go to zero
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/245 Light Bulb stays lit during short circuit
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/685 When the battery resistance is set to "Tiny", then there should be no resistance readout on the battery
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/683 Change Battery Resistance Slider lower limit to "Tiny"
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/688 Wire Resistance: Lots should match published version

@arouinfar can you please test these or give guidance on how QA team should test them? Particularly the first two.

QA should also please note which platform(s) and how long was taken for sanity testing.  I think 1-2 platforms and minimal time for that is fine.

**Comment by kathy-phet** [comment]
https://github.com/phetsims/circuit-construction-kit-common/issues/688

**Comment by samreid** [comment]
On hold until the https://github.com/phetsims/circuit-construction-kit-common/issues/688 is addressed

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome (Time = )
- [ ] Win 10 Firefox (Time = )
- [ ] MacOS Chrome (Time = )
- [ ] MacOS Safari (Time = )
- [ ] iPadOS (Time = )
- [ ] ChromeOS (Time = )

**Comment by kathy-phet** [comment]
@KatieWoe - 
Not expecting any of these changes to be device-or-browser specific. So perhaps fewer device/browser combinations? 

Testing should be about 10 minutes of general sanity checking, and then another 15 minutes or so of building crazy circuits and making sure things look good. The change is mostly improving the modeling of the current and electrons.

**Comment by KatieWoe** [comment]
Since this is a spot check, not all these will be tested. But since we don't know who will be testing on what, I list all of them and the tester fills out the one they did with the time they did.

**Comment by KatieWoe** [comment]
QA is done
