### ISSUE TITLE
RC Test: Balloons and Static Electricity 1.5.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#706]
@emily-phet, @kathy-phet, and @arouinfar: balloons-and-static-electricity/1.5.0-rc.1 is ready for RC testing.  This
release includes a number of new features, such as sound, pan & zoom, and the preferences menu.  This is the first RC
for this release, so it should be thoroughly tested on all supported platforms.  Please document issues in 
https://github.com/phetsims/balloons-and-static-electricity/issues and link to this issue.

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
  for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
  spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
  there is a problem.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.1/phet/balloons-and-static-electricity_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.1/phet/balloons-and-static-electricity_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.1/phet/xhtml/balloons-and-static-electricity_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/153iOnhpi5IHdqFp3JBC9QDOmToPjhf4idY9YXQkqtac/edit#gid=2086384044)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the accessibility-related feature that is being tested doesn't negatively affect the sim in any way. Here is a list of features to supported in this test: 
  - Alternative Input
  - Interactive Description (though there are a number of known issues already logged, so don't duplicate them)
  - Sound and Sonification
  - Pan and Zoom
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Focus and Special Instructions</h3>

The focus should be on the newly added features of sound, pan & zoom, and the preferences menu.  Note that while the
accessible description has been improved, there are a number of known issues on this.  Please make sure not to duplicate
any of the issues that are already logged for this sim that are marked as deferred.

<h3>Issues to Verify</h3>

- [x] [When balloon is moved very slowly over sweater, negative charges are not picked up](https://github.com/phetsims/balloons-and-static-electricity/issues/526)
- [x] [Crackling sound heard when balloon moves on iPad](https://github.com/phetsims/balloons-and-static-electricity/issues/527)
- [x] [Noise Bug when Toggling Between One and Two Balloons](https://github.com/phetsims/balloons-and-static-electricity/issues/530)
- [x] [Jaws can't pick up balloon](https://github.com/phetsims/balloons-and-static-electricity/issues/532)
- [x] [Implement sound design](https://github.com/phetsims/balloons-and-static-electricity/issues/479)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.1/phet/balloons-and-static-electricity_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.1/phet/balloons-and-static-electricity_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/153iOnhpi5IHdqFp3JBC9QDOmToPjhf4idY9YXQkqtac/edit#gid=2086384044)**

<h3>Screen Readers</h3>

This sim supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have
all of the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the
a11y view before opening the simulation. Once you've done that, open the simulation and make sure alerts and
descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [x] Windows 10 + Latest Chrome + Latest JAWS
- [x] Windows 10 + Latest Firefox + Latest NVDA
- [x] macOS + Safari + VoiceOver
- [x] iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<h3>Final Requests</h3>

- [x] If this sim is not in [this list](https://phet.colorado.edu/en/accessibility/prototypes) or up to date there, make an
  issue in [website](https://github.com/phetsims/website) to ask if PhET research page links need updating. Please assign
  to @terracoda and @emily-phet.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by Nancy-Salpepi** [comment]
Memory Leak Test Results:
<img width="634" alt="Screen Shot 2021-09-13 at 12 14 15 PM" src="https://user-images.githubusercontent.com/87318828/133119947-9d4c6657-ca68-4a63-ac0a-b1a587122a26.png">

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
Thanks team.  I'll follow up on the individual issues, closing this one.
