### ISSUE TITLE
RC.2 Circuit Construction Kit: AC and AC: Virtual Lab

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#752]
@KatieWoe @arouinfar @ariel-phet @kathy-phet circuit-construction-kit-ac/1.0.0-rc.2 and circuit-construction-kit-ac-virtual-lab/1.0.0-rc.2 are ready for RC testing.  This has been a high priority sim.  Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this issue.

This is a mostly a spot check after the first RC.  None of the code changes seem platform specific.  So just testing on 1-2 desktop browsers, and on a slower performing machine to make sure there was no performance regression sounds good.

In addition to the spot check, https://github.com/phetsims/circuit-construction-kit-common/issues/800 needs to be tested more thoroughly (on 1-2 platforms).  The algorithm for determining the current sense (and therefore current sign) has been rewritten.

For that issue, @kathy-phet said:

> When you are testing, know that expected behavior is ...
> if a stand alone circuit has no current in it at all (either by breaking the path or opening a switch), it will always choose positive for the current when reconnected if DC, or match the sense of an existing AC source if AC.

In addition to spot checking the repaired issues, please spend 1-2 hours making sure there were no other regressions or 
unrelated bugs introduced.

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>

<h3>Focus and Special Instructions</h3>

<h3>Issues to Verify</h3>

- [x] [Flipping battery briefly leads to wrong sign for in line ammeter (and sometimes other ammeters)](https://github.com/phetsims/circuit-construction-kit-common/issues/793)
- [x] [Chart tool icon labels should disappear when "Labels" is unchecked](https://github.com/phetsims/circuit-construction-kit-common/issues/794)
- [x] [Cursor hand over region with no chart tool icon](https://github.com/phetsims/circuit-construction-kit-common/issues/795)
- [ ] [Should meter tool labels disappear when all tools are in the play area?](https://github.com/phetsims/circuit-construction-kit-common/issues/796)
- [x] [Treat Switch text the same as other free-floating text](https://github.com/phetsims/circuit-construction-kit-common/issues/799)
- [ ] [Current sign doesn't reset to positive when multiple circuits are on same screen](https://github.com/phetsims/circuit-construction-kit-common/issues/800)
- [x] [Current value doesn't update when wire resistivity is changed in pause mode](https://github.com/phetsims/circuit-construction-kit-common/issues/803)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

Deployed: 
- **[AC](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-rc.2/phet/circuit-construction-kit-ac_all_phet.html)**
- **[AC Virtual Lab](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-rc.2/phet/circuit-construction-kit-ac-virtual-lab_all_phet.html)**

- [x] Tester = NS, Platform = macOS12 + safari15 , Time = 3
- [x] Tester = E2, Platform = Win10 Chrome 96.0.4664.93, Time = 3
- [x] Tester = KW, Platform = Win 11 Chrome, Time = .75

I do not believe the XHTML, iframe, etc. need to be double-checked in this version.  If it is procedure or policy to do so, please do so.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done
