### ISSUE TITLE
RC Test: Density 1.0.0-rc.3

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#759]
@arouinfar, @kathy-phet, @DianaTavares, density/1.0.0-rc.3 is ready for RC testing. Document issues in https://github.com/phetsims/density/issues and link to this
issue.

This is a spot check. Details about what's likely to break is in the Focus and Special Instructions.

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version.
- Try to include version numbers for browsers.
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if there is a problem.

<h3>Focus and Special Instructions</h3>

1. Interruption (with reset-all) of drags was changed. Ideally test to see that dragging things and reset-all (multiple times) works nicely.
2. Memory performance was changed.
3. Layout changes were made for phet-io AND in the sim. Try triggering a lot of instantaneous layout changes (minimizing and maximizing, from a square-ish aspect ratio to very wide or tall), see if it's buggy.
4. Phet-io changes for https://github.com/phetsims/density-buoyancy-common/issues/68 should be played with a good amount

<h3>Issues to Verify</h3>

- [x] [The scale may disappear when pressing "Preview Sim" in studio.](https://github.com/phetsims/density-buoyancy-common/issues/67)
- [x] [Customized block colors are not restored in studio "Preview Sim"](https://github.com/phetsims/density-buoyancy-common/issues/68)
- [x] [Block position changes when switching to full screen mode](https://github.com/phetsims/density/issues/117)
- [x] [CT value failed isValidValue](https://github.com/phetsims/density/issues/122)
- [x] [Block position doesn't reset with multitouch](https://github.com/phetsims/density/issues/127)
- [x] [Include ?autoselectSupported in phet-io-guide.md](https://github.com/phetsims/density/issues/128)
- [x] [Memory Leak](https://github.com/phetsims/density/issues/130)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/density/1.0.0-rc.3/phet/density_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/density/1.0.0-rc.3/phet/density_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/density/1.0.0-rc.3/phet/xhtml/density_all.xhtml)**

- [x] Tester = NS , Platform = MacOS 12.0.1 + chrome/safari , Time = 1.5
- [x] Tester = KW, Platform = Win 11 Chrome, Time = 2
- [x] Tester = E2, Platform = Win10 Firefox, Time = 2

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make sure the simulation loads without crashing or throwing errors.
- For an update or maintenance release please check the backwards compatibility of the playback wrapper.
[Here's the link to the previous wrapper.](link)
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.
- Conduct a memory test on the stand alone sim wrapper (rc.1).
- Test one platform combination with `?phetioDebug` on the Studio and State wrapper.
- If Pan/Zoom is supported, make sure that it works when set with PhET-iO State.
- If filled in by issue creator, please test the diff wrapper against {{URL_TO_OLD_VERSION_ROOT}}.
- Test that the sim works offline:
  * Go to https://phet-dev.colorado.edu/html/density/1.0.0-rc.3/phet-io/density-phet-io-1.0.0-rc.3.zip
  * download it
  * unzip it to a spot locally
  * Open `index.html` by double clicking it on your desktop or in a finder-view.
  * It should look like the standalone version of the sim in PhET-iO brand.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/density/1.0.0-rc.3/phet-io/)**

- [x] Tester = NS , Platform = MacOS12 + safari, Time = 2
- [x] Tester = KW, Platform = Win 11, Time = 1.5
- [ ] Tester = , Platform = , Time = 

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
PhET-Brand Memory Test:
<img width="350" alt="phetbrandmem" src="https://user-images.githubusercontent.com/41024075/148604107-5288368f-cc62-4459-a8b2-26658f387b21.png">
PhET-iO-Brand Memory Test:
<img width="349" alt="iomem" src="https://user-images.githubusercontent.com/41024075/148604133-f345c78d-90f3-4648-b72e-dde1995d94a9.png">

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thanks!
