### ISSUE TITLE
Rosetta 2.0 Test — Round 2

### ISSUE THREAD

**Issue by liammulh** [phetsims/qa#878]
This test is ready.

The first round of testing was completed in https://github.com/phetsims/qa/issues/869. As with the previous test, we will test in phases.

link: https://ox-dev.colorado.edu/translate

## Phase 1: Test New Features

Be aware that the publish button is not meant to be working during this phase.

- [x] I will configure Rosetta to *not* perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be master.
- [ ] QA will:
  - [x] ensure the translation "report" i.e. the stats for each sim in a
    given locale load properly
  - [x] spot-check a handful of the stats to ensure they are accurate
    - To do this, QA will have to look at the translated string file in
      Babel. If they really want to be thorough, they can count the
      total number of strings in the published sim. If they want to do
      this, they should ask me for a copy of the strings file for the
      published sim.
  - [x] ensure the translation reports are cached
  - [x] ensure the tables are sortable
    - [x] ensure the sorting is correct 
  - [x] ensure the translation "form" shows errors when placeholders
    don't match
  - [x] ensure the save, publish, and test buttons are disabled when
    there are form errors
  - [x] ensure the copy button copies the English string over

### Issues to Verify

Please let me know if you have any questions about how to verify these
issues.

- [x] https://github.com/phetsims/rosetta/issues/331
- [x] https://github.com/phetsims/rosetta/issues/332
- [x] https://github.com/phetsims/rosetta/issues/334
- [x] https://github.com/phetsims/rosetta/issues/340
- [x] https://github.com/phetsims/rosetta/issues/342
  - To verify this, please use the live translation utility (be careful
    not to submit anything while using it) and look for sims that have
    shared strings. (There will be a header in the translation utility that
    says something like "These are shared strings".) Verify that Rosetta 2.0
    also has these shared strings. Off the top of my head, Atomic
    Interactions, Concentration, Geometric Optics: Basics, and I think some
    of CCK sims have shared strings. I think there are others as well.
- [x] https://github.com/phetsims/rosetta/issues/347
  - To verify this, click the little info icon next to the string stats
    for each sim. Sims with shared strings should have stats for shared
    strings.
- [x] https://github.com/phetsims/rosetta/issues/348
- [x] https://github.com/phetsims/rosetta/issues/350
- [x] https://github.com/phetsims/rosetta/issues/355

## Phase 2: Test Old Features

Be aware that during this phase, the publish button should work, and it will commit strings to the test branch of Babel.

- [x] I will configure Rosetta to perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be tests.
- [ ] QA will:
   ❎  ensure they can publish a translation and see the results on
    Babel
  - [ ] ensure the simulation you published has a "(pending update)"
    badge next to it
    - this should go away after `VALID_METADATA_DURATION`
      (set to 30 minutes as of this writing) or 10 minutes, whichever is
      lesser

  ❎ ensure the save button saves their translation
  - [ ] ensure that once they've published a translation, and then
    wait about ten minutes, they see the strings from Babel, not strings
    they saved
    - To test this, save a translation, modify the saved translation,
      publish it, and then wait ten minutes. When you come back, you
      should see the strings that are in Babel in the form rather than your
      saved strings. (The saved translation should be deleted from the
      database when you publish.)

### Issues to Verify

- [ ] https://github.com/phetsims/rosetta/issues/344
- [ ] https://github.com/phetsims/rosetta/issues/345
  - This was actually a bug that was preventing the sim from being
    published properly. That bug should be fixed now, and you should be
    able to "publish" (i.e. save strings to phetsims/babel) now, and you
    should be able to see the pending update "badge".
- [ ] https://github.com/phetsims/rosetta/issues/351
  - To test, publish a sim, then go back to the sim list. You should see a note that says "(pending update)", and that note should go away after 30 minutes.

### Phase 3 Part A

- [ ] I will configure Rosetta to show its "Down for Maintenance" page.
- QA will:
  - [ ] ensure they see a message about the translation utility being
  down for maintenance
  - [ ] ensure they can't access /translate/{locale}
  - [ ] ensure they can't access /translate/{locale}/{sim-name}
  - [ ] ensure they can't access /translate/admin

### Phase 3 Part B

- [ ] I will configure Rosetta to be enabled.
- [ ] I will configure Rosetta to *not* perform string commits.
- [ ] I will configure Rosetta to *not* send build requests.
- [ ] I will configure Rosetta to have it's Babel branch be master.
- QA will:
  - [ ] ensure that someone who isn't a trusted translator or a team
    member can't access the translation utility
  - [ ] ensure that team members who aren't trusted translators can
    access the translation utility
  - [ ] ensure that trusted translators who aren't team members can
    access the translation utility

**Comment by liammulh** [comment]
@KatieWoe, @Nancy-Salpepi, @stemilymill, this test is now ready.

**Comment by kathy-phet** [comment]
@solaolateju @DianaTavares - As our user audience, do you have time tomorrow to spend a bit of time helping to test Rosetta during this new Phase 1 test?

**Comment by DianaTavares** [comment]
I test the Rosetta, and it works very well! 

- [x] ensure the translation "report" i.e. the stats for each sim in a given locale load properly
- [x] given locale load properly
It takes around 10s to load the statics of a local the firs time, but a second time it loads superfast. 

- [x]  spot-check a handful of the stats to ensure they are accurate
I love the info button in close to the percentage!! I checked this one and it is correct.
![image](https://user-images.githubusercontent.com/26031501/211890160-914f3fce-c7f2-43da-a6a0-2c4f8b544557.png)

- [x]  ensure the translation reports are cached
- [x]  ensure the tables are sortable
- [x]  ensure the sorting is correct
- [x]  ensure the translation "form" shows errors when placeholders don't match
- [x]  ensure the save, publish, and test buttons are disabled when there are form errors
It is super cool the error message of curly brace, but I feel it aggressive that I just start to write the translation and the error in red is there the hole time. I suggest that the error appears when user move to another text and the translation is incorrect. 
![image](https://user-images.githubusercontent.com/26031501/211888752-b013c16f-9f21-4ec7-9dd0-4197cecec1f9.png)

The description of the error displayed when I pressed the red button is very clear!

I liked that the old translation utility, this curly brace stuff were in blue. It was easier to identify them and to explain new translators that those strings were special. 

What about the `<b>` and `<br>`? Not all translators know the meaning of them. This is from MSS:
![image](https://user-images.githubusercontent.com/26031501/211892572-fa1382e6-84bb-4afd-80be-83aedff5bd36.png)

- [x]  ensure the copy button copies the English string over.

It looks strange that is not coherency in the position of this button in the Common String and sim-specific tables.  
![image](https://user-images.githubusercontent.com/26031501/211891445-f2478851-bbc9-4ce2-91b9-e367eb2eca23.png)

Extra:

- The test button takes some seconds to open the sim, and I'm still having the animation of "loading" all the time the sim is open. But looks that again that is just computer-specific. 

![image](https://user-images.githubusercontent.com/26031501/211892040-96e18549-c64b-4ffe-abe5-d82f4db2f71d.png)

- For super long texts, like the example of MSS, I have to translate if outside PhET, and later paste it in that little space because there is supper hard to review. I wonder if it is possible to have text entrance (the rectangles where I insert the text) adjustable to always display all the text introduced. 

![image](https://user-images.githubusercontent.com/26031501/211892900-736dfd1c-48dd-4e51-949e-42fcae0673e1.png)


That are all my comments. It looks wonderful! Good job @liammulh

**Comment by solaolateju** [comment]
This is shaping up really well. Please find my thought and comments below. 

**Comments**
- Sorting the lists work well.
- The tooltips for stats are neat and very useful.
- Note for poorly formatted dynamic strings (curly braces) work well.
- 

**Feedback**
Presentation
- The width of the columns are not the same, making alignment inconsistent. Consider increasing the size of the textbox for the translated string and setting a max-width for the sting key and English stings.
- The default size of the translated sim string is small and a single line. Making it a **text area** when in focus would make the text easier to read and edit.
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/18397749/211924302-b1dbbbf0-106e-48a6-a050-ef25fda7f1e0.png">

- Aligning the Sim-Specific Strings columns with the Common Strings columns will improve the looks. The same suggestion applies for sims published and sims not yet published lists.
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/18397749/211924107-b5f514cd-a8f8-415b-8653-1d0eaeab1e59.png">

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/18397749/211923970-15eb8e23-f918-49e5-a39e-b0c19fd43674.png">


Functionality
- No feedback. Works as expected for phase 1 requirements.

**Comment by liammulh** [comment]
> I love the info button in close to the percentage!! I checked this one and it is correct.

Thanks, @DianaTavares!

> It is super cool the error message of curly brace, but I feel it aggressive that I just start to write the translation and the error in red is there the hole time. I suggest that the error appears when user move to another text and the translation is incorrect.

Okay, I made https://github.com/phetsims/rosetta/issues/353.

> I liked that the old translation utility, this curly brace stuff were in blue. It was easier to identify them and to explain new translators that those strings were special. 

Okay, I made https://github.com/phetsims/rosetta/issues/354.

> What about the `<b>` and `<br>`? Not all translators know the meaning of them. This is from MSS:
![image](https://user-images.githubusercontent.com/26031501/211892572-fa1382e6-84bb-4afd-80be-83aedff5bd36.png)

Before we publish 2.0, there will be a user guide that the translators can read to understand more about rich text elements like `<b>`, `<br>`, `<sup>`, etc.

> It looks strange that is not coherency in the position of this button in the Common String and sim-specific tables.  
![image](https://user-images.githubusercontent.com/26031501/211891445-f2478851-bbc9-4ce2-91b9-e367eb2eca23.png)

That's because the tables resize themselves based on their content. They are two separate tables instead of one table. It's possible to make them the same, but I don't think it's necessary for the release of 2.0.

> The test button takes some seconds to open the sim, and I'm still having the animation of "loading" all the time the sim is open. But looks that again that is just computer-specific.

That loading issue is strange! I made https://github.com/phetsims/rosetta/issues/355.

> For super long texts, like the example of MSS, I have to translate if outside PhET, and later paste it in that little space because there is supper hard to review. I wonder if it is possible to have text entrance (the rectangles where I insert the text) adjustable to always display all the text introduced. 

We already have an issue for this: https://github.com/phetsims/rosetta/issues/349.

Thank you for testing, @DianaTavares!

**Comment by liammulh** [comment]
> The width of the columns are not the same, making alignment inconsistent. Consider increasing the size of the textbox for the translated string and setting a max-width for the sting key and English stings.

Since both @DianaTavares and @solaolateju mentioned this, I created https://github.com/phetsims/rosetta/issues/356.

> The default size of the translated sim string is small and a single line. Making it a text area when in focus would make the text easier to read and edit.

I think originally the translation utility was only supposed to be used to translate single strings, but now there are whole paragraphs. I think making inputs textareas (or making some of them textareas) makes sense. See https://github.com/phetsims/rosetta/issues/349.

> Aligning the Sim-Specific Strings columns with the Common Strings columns will improve the looks. The same suggestion applies for sims published and sims not yet published lists.

I added some notes to https://github.com/phetsims/rosetta/issues/356.

Thanks for testing, @solaolateju!

**Comment by liammulh** [comment]
| Issue | Blocks publication? | Actionable? | Done and ready for testing? |
| - | - | - | - |
| https://github.com/phetsims/rosetta/issues/353 | No | N/A | N/A |
| https://github.com/phetsims/rosetta/issues/354 | No | N/A | N/A |
| https://github.com/phetsims/rosetta/issues/355 | ? | ? | ? |
| https://github.com/phetsims/rosetta/issues/356 | No | N/A | N/A |

**Comment by Nancy-Salpepi** [comment]
>To do this, QA will have to look at the translated string file in
Babel. If they really want to be thorough, they can count the
total number of strings in the published sim. If they want to do
this, they should ask me for a copy of the strings file for the
published sim.

If you give me a copy of a strings file I can do the more thorough check.

**Comment by liammulh** [comment]
> If you give me a copy of a strings file I can do the more thorough check.

Will do. Let me get you a few string files.

**Comment by liammulh** [comment]
Whoops, closed the issue instead of clicking the comment button 😓.

**Comment by Nancy-Salpepi** [comment]
I tested phase I on mac + chrome. There is still https://github.com/phetsims/rosetta/issues/342 to verify. I didn't feel comfortable going into the live translation utility.

**Comment by Nancy-Salpepi** [comment]
@liammulh there seems to be a regression here in round 2, preventing further testing. I am having issues with saving, publishing and testing.

**Comment by liammulh** [comment]
Closing this issue, and opening a new one.
