### ISSUE TITLE
Rosetta 2.0 Test — Round 3

### ISSUE THREAD

**Issue by liammulh** [phetsims/qa#888]
This test is ready.

The second round of testing was stopped early due to the issues
described in these comments:

- https://github.com/phetsims/qa/issues/878#issuecomment-1400826265
- https://github.com/phetsims/qa/issues/878#issuecomment-1382174639

Link for testing: https://ox-dev.colorado.edu/translate

Below you'll find the strings file for three sims. You will need to use
these in some of the tests.

## Before Testing Starts

- [x] Liam will:
  - [x] Ensure the config on Ox-Dev is correct.
    -  `IS_ENABLED` is true.
    - `ENVIRONMENT` is "production".
  - [x] Write down Ox-Dev's SHA.
   - The commit under test is tagged `2.0.0-rc-3`.
  - [x] Do his own testing.
    - I did my own testing in https://github.com/phetsims/rosetta/issues/362. I did phase 1 and 2 and phase 3A. 

## Phase 1: Test New Features (Spot-Check)

Be aware that the publish button is not meant to be working during this
phase.

Don't spend too much time here, maybe a few minutes per checkbox.

- [x] I will configure Rosetta to *not* perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be master.
- [x] QA will:
  - [x] ensure the translation "report" i.e. the stats for each sim in a
    given locale load properly
  - [x] spot-check a handful of the stats to ensure they are accurate
    - To do this, QA will have to look at the translated string file in
      Babel. If they really want to be thorough, they can count the
      total number of strings in the published sim.
  - [x] ensure the translation reports are cached
  - [x] ensure the tables are sortable
    - [x] ensure the sorting is correct 
  - [x] ensure the translation "form" shows errors when placeholders
    don't match
  - [x] ensure the save, publish, and test buttons are disabled when
    there are form errors
  - [x] ensure the copy button copies the English string over

### Issues to Spot-Check (spend a few minutes per checkbox)

Please only spend a few minutes on these. They were verified in the last
round of QA.

- [x] https://github.com/phetsims/rosetta/issues/331
- [x] https://github.com/phetsims/rosetta/issues/332
- [x] https://github.com/phetsims/rosetta/issues/334
- [x] https://github.com/phetsims/rosetta/issues/340
- [x] https://github.com/phetsims/rosetta/issues/347
  - To verify this, click the little info icon next to the string stats
    for each sim. Sims with shared strings should have stats for shared
strings.
- [x] https://github.com/phetsims/rosetta/issues/348
- [x] https://github.com/phetsims/rosetta/issues/350
- [x] https://github.com/phetsims/rosetta/issues/355

### Issue to Verify (spend more than a few minutes)

Please let me know if you have any questions about how to verify this
issue.

- [x] https://github.com/phetsims/rosetta/issues/342
  - Note: It's okay for Under Pressure's shared strings to be in the
    common category. 
  - To verify this, please use the live translation utility (be careful
    not to submit anything while using it) and look for sims that have
    shared strings. (There will be a header in the translation utility that
    says something like "These are shared strings".) Verify that Rosetta 2.0
    also has these shared strings. Off the top of my head, Atomic
    Interactions, Concentration, Geometric Optics: Basics, and I think some
    of CCK sims have shared strings. I think there are others as well.

## Phase 2: Test Old Features (Regular Test)

Be aware that during this phase, the publish button should work, and it
will commit strings to the test branch of Babel.

- [x] I will configure Rosetta to perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be tests.
- [x] QA will:
   - [x] ensure they can publish a translation and see the results on
     Babel
    - Please take a look at the strings file to see what repos will be
  - [x] ensure the simulation you published has a "(pending update)"
    badge next to it
    - this should go away after `VALID_METADATA_DURATION` (set to 30
      minutes as of this writing) or 10 minutes, whichever is lesser
  - [x] ensure the save button saves their translation
  - [x] ensure that once they've published a translation, and then wait
    about ten minutes, they see the strings from Babel, not strings they
    saved
    - To test this, save a translation, modify the saved translation,
      publish it, and then wait ten minutes. When you come back, you
      should see the strings that are in Babel in the form rather than your
      saved strings. (The saved translation should be deleted from the
      database when you publish.)

### Issues to Verify

- [x] https://github.com/phetsims/rosetta/issues/344
- [x] https://github.com/phetsims/rosetta/issues/345
  - This was actually a bug that was preventing the sim from being
    published properly. That bug should be fixed now, and you should be
able to "publish" (i.e. save strings to phetsims/babel) now, and you
should be able to see the pending update "badge".
- [x] https://github.com/phetsims/rosetta/issues/351
  - To test, publish a sim, then go back to the sim list. You should see
    a note that says "(pending update)", and that note should go away
after 30 minutes.
- [x] https://github.com/phetsims/rosetta/issues/342
- [x] https://github.com/phetsims/rosetta/issues/359
- [x] https://github.com/phetsims/rosetta/issues/360
  - Please test this thoroughly. To do a rigorous test, first look at
    the string files of the sims below and see what repos are going to
    be affected by your translation. Check the relevant translation files
    before you make your translation. During your translation, be sure to
    include sim-specific, shared, and common strings in your translation.
    Once you've hit the publish button, check the translation files and make
    sure the changes you're seeing make sense.
- [x] https://github.com/phetsims/rosetta/issues/361

## Phase 3: Test Down for Maintenance / Sign-In / Permissions (Spot-Check)

No issues were found for this phase during the first round of testing,
so don't spend too much time during this phase.

### Phase 3 Part A

- [x] I will configure Rosetta to show its "Down for Maintenance" page.
- QA will:
  - [x] ensure they see a message about the translation utility being
    down for maintenance
  - [x] ensure they can't access /translate/{locale}
  - [x] ensure they can't access /translate/{locale}/{sim-name}
  - [x] ensure they can't access /translate/admin

### Phase 3 Part B

- [x] I will configure Rosetta to be enabled.
- [x] I will configure Rosetta to *not* perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be master.
- QA will:
  - [ ] ensure that someone who isn't a trusted translator or a team
    member can't access the translation utility
  - [ ] ensure that team members who aren't trusted translators can
    access the translation utility
  - [ ] ensure that trusted translators who aren't team members can
    access the translation utility

## String Files

<details>

<summary>Diffusion Strings</summary>

```
{
  "en": {
    "JOIST/termsPrivacyAndLicensing": "‪Terms, Privacy & Licensing‬",
    "JOIST/translation.credits.link": "‪Translation Credits‬",
    "JOIST/thirdParty.credits.link": "‪Third-party Credits‬",
    "SCENERY_PHET/key.enter": "‪Enter‬",
    "SCENERY_PHET/key.pageDown": "‪Pg Dn‬",
    "SCENERY_PHET/key.pageUp": "‪Pg Up‬",
    "SCENERY_PHET/key.shift": "‪Shift‬",
    "SCENERY_PHET/key.space": "‪Space‬",
    "SCENERY_PHET/keyboardHelpDialog.grabOrReleaseHeadingPattern": "‪Grab or Release {{thing}}‬",
    "SCENERY_PHET/keyboardHelpDialog.grabOrReleaseLabelPattern": "‪Grab or release {{thing}}‬",
    "SCENERY_PHET/keyboardHelpDialog.or": "‪or‬",
    "SCENERY_PHET/key.tab": "‪Tab‬",
    "JOIST/keyboardShortcuts.title": "‪Keyboard Shortcuts‬",
    "JOIST/keyboardShortcuts.toGetStarted": "‪to get started‬",
    "JOIST/credits.contributors": "‪Contributors: {0}‬",
    "JOIST/credits.graphicArts": "‪Graphic Arts: {0}‬",
    "JOIST/credits.leadDesign": "‪Lead Design: {0}‬",
    "JOIST/credits.qualityAssurance": "‪Quality Assurance: {0}‬",
    "JOIST/credits.softwareDevelopment": "‪Software Development: {0}‬",
    "JOIST/credits.soundDesign": "‪Sound Design: {0}‬",
    "JOIST/credits.team": "‪Team: {0}‬",
    "JOIST/credits.thanks": "‪Thanks‬",
    "JOIST/credits.title": "‪Credits‬",
    "JOIST/credits.translation": "‪Translation‬",
    "JOIST/updates.checking": "‪Checking for updates…‬",
    "JOIST/updates.getUpdate": "‪Get Update…‬",
    "JOIST/updates.newVersionAvailable": "‪There is a new version available: {0}.‬",
    "JOIST/updates.noThanks": "‪No Thanks‬",
    "JOIST/updates.offline": "‪Unable to check for updates.‬",
    "JOIST/updates.outOfDate": "‪New version available‬",
    "JOIST/updates.upToDate": "‪This simulation is up to date.‬",
    "JOIST/updates.yourCurrentVersion": "‪Your current version is: {0}.‬",
    "JOIST/versionPattern": "‪version {0}‬",
    "JOIST/options.title": "‪Options‬",
    "JOIST/menuItem.about": "‪About…‬",
    "JOIST/menuItem.enhancedSound": "‪Enhanced Sound‬",
    "JOIST/menuItem.fullscreen": "‪Full Screen‬",
    "JOIST/menuItem.getUpdate": "‪Check for Updates…‬",
    "JOIST/menuItem.mailInputEventsLog": "‪Mail Input Events Log‬",
    "JOIST/menuItem.options": "‪Options…‬",
    "JOIST/menuItem.outputInputEventsLog": "‪Output Input Events Log‬",
    "JOIST/menuItem.phetWebsite": "‪PhET Website…‬",
    "JOIST/menuItem.reportAProblem": "‪Report a Problem…‬",
    "JOIST/menuItem.screenshot": "‪Screenshot‬",
    "JOIST/menuItem.submitInputEventsLog": "‪Submit Input Events Log‬",
    "JOIST/simTitleWithScreenNamePattern": "‪{{simName}} — {{screenName}}‬",
    "SCENERY_PHET/speed.normal": "‪Normal‬",
    "SCENERY_PHET/speed.slow": "‪Slow‬",
    "SCENERY_PHET/symbol.ohms": "‪Ω‬",
    "SCENERY_PHET/symbol.resistivity": "‪ρ‬",
    "SCENERY_PHET/comboBoxDisplay.valueUnits": "‪{{value}} {{units}}‬",
    "GAS_PROPERTIES/atmospheres": "‪atm‬",
    "GAS_PROPERTIES/kilopascals": "‪kPa‬",
    "GAS_PROPERTIES/pressure": "‪Pressure‬",
    "GAS_PROPERTIES/tAvg": "‪T<sub>avg</sub> = {{value}}‬",
    "GAS_PROPERTIES/tAvgK": "‪T<sub>avg</sub> = {{value}} K‬",
    "GAS_PROPERTIES/data": "‪Data‬",
    "GAS_PROPERTIES/centerOfMass": "‪Center of Mass‬",
    "GAS_PROPERTIES/initialTemperatureK": "‪Initial Temperature (K)‬",
    "GAS_PROPERTIES/massAMU": "‪Mass (AMU)‬",
    "GAS_PROPERTIES/numberOfParticles": "‪Number of Particles‬",
    "GAS_PROPERTIES/radiusPm": "‪Radius (pm)‬",
    "GAS_PROPERTIES/removeDivider": "‪Remove Divider‬",
    "GAS_PROPERTIES/resetDivider": "‪Reset Divider‬",
    "GAS_PROPERTIES/particleFlowRate": "‪Particle Flow Rate‬",
    "GAS_PROPERTIES/scale": "‪Scale‬",
    "GAS_PROPERTIES/stopwatch": "‪Stopwatch‬",
    "GAS_PROPERTIES/nanometers": "‪nm‬",
    "GAS_PROPERTIES/valueUnits": "‪{{value}} {{units}}‬",
    "GAS_PROPERTIES/picoseconds": "‪ps‬",
    "GAS_PROPERTIES/screen.diffusion": "‪Diffusion‬",
    "JOIST/projectorMode": "‪Projector Mode‬",
    "GAS_PROPERTIES/pressureNoise": "‪Pressure Noise‬",
    "DIFFUSION/diffusion.title": "‪Diffusion‬"
  }
}
```

</details>

<details>

<summary>Concentration Strings</summary>

```
{
  "en": {
    "BEERS_LAW_LAB/drinkMix": "‪Drink mix‬",
    "BEERS_LAW_LAB/water": "‪water‬",
    "BEERS_LAW_LAB/cobaltChloride": "‪Cobalt(II) chloride‬",
    "BEERS_LAW_LAB/cobaltIINitrate": "‪Cobalt(II) nitrate‬",
    "BEERS_LAW_LAB/copperSulfate": "‪Copper(II) sulfate‬",
    "BEERS_LAW_LAB/nickelIIChloride": "‪Nickel(II) chloride‬",
    "BEERS_LAW_LAB/potassiumChromate": "‪Potassium chromate‬",
    "BEERS_LAW_LAB/potassiumDichromate": "‪Potassium dichromate‬",
    "BEERS_LAW_LAB/potassiumPermanganate": "‪Potassium permanganate‬",
    "BEERS_LAW_LAB/sodiumChloride": "‪Sodium chloride‬",
    "BEERS_LAW_LAB/pattern.0value.1units": "‪{0} {1}‬",
    "BEERS_LAW_LAB/units.liters": "‪L‬",
    "BEERS_LAW_LAB/units.milliliters": "‪mL‬",
    "JOIST/termsPrivacyAndLicensing": "‪Terms, Privacy & Licensing‬",
    "JOIST/translation.credits.link": "‪Translation Credits‬",
    "JOIST/thirdParty.credits.link": "‪Third-party Credits‬",
    "BEERS_LAW_LAB/concentration": "‪Concentration‬",
    "BEERS_LAW_LAB/pattern.0percent": "‪{0}%‬",
    "BEERS_LAW_LAB/units.molesPerLiter": "‪mol/L‬",
    "BEERS_LAW_LAB/evaporation": "‪Evaporation‬",
    "BEERS_LAW_LAB/lots": "‪lots‬",
    "BEERS_LAW_LAB/none": "‪none‬",
    "BEERS_LAW_LAB/pattern.0label": "‪{0}:‬",
    "BEERS_LAW_LAB/removeSolute": "‪Remove Solute‬",
    "SCENERY_PHET/ResetAllButton.name": "‪Reset All‬",
    "BEERS_LAW_LAB/saturated": "‪Saturated!‬",
    "BEERS_LAW_LAB/pattern.0soluteAmount": "‪Solute Amount: {0} g‬",
    "BEERS_LAW_LAB/solute": "‪Solute‬",
    "BEERS_LAW_LAB/solid": "‪Solid‬",
    "BEERS_LAW_LAB/solution": "‪Solution‬",
    "BEERS_LAW_LAB/screen.concentration": "‪Concentration‬",
    "JOIST/HomeButton.name": "‪Home‬",
    "JOIST/adaptedFrom": "‪adapted\nfrom‬",
    "JOIST/credits.title": "‪Credits‬",
    "JOIST/credits.leadDesign": "‪Lead Design: {0}‬",
    "JOIST/credits.softwareDevelopment": "‪Software Development: {0}‬",
    "JOIST/credits.team": "‪Team: {0}‬",
    "JOIST/credits.qualityAssurance": "‪Quality Assurance: {0}‬",
    "JOIST/credits.graphicArts": "‪Graphic Arts: {0}‬",
    "JOIST/credits.translation": "‪Translation‬",
    "JOIST/credits.thanks": "‪Thanks‬",
    "JOIST/updates.upToDate": "‪This simulation is up to date.‬",
    "JOIST/updates.outOfDate": "‪New version available‬",
    "JOIST/updates.checking": "‪Checking for updates…‬",
    "JOIST/updates.offline": "‪Unable to check for updates.‬",
    "JOIST/updates.newVersionAvailable": "‪There is a new version available: {0}.‬",
    "JOIST/updates.yourCurrentVersion": "‪Your current version is: {0}.‬",
    "JOIST/updates.getUpdate": "‪Get Update…‬",
    "JOIST/updates.noThanks": "‪No Thanks‬",
    "JOIST/versionPattern": "‪version {0}‬",
    "JOIST/options.title": "‪Options‬",
    "JOIST/showPointers": "‪Show Pointers‬",
    "JOIST/done": "‪Done‬",
    "JOIST/title.settings": "‪Settings‬",
    "JOIST/menuItem.options": "‪Options…‬",
    "JOIST/menuItem.about": "‪About…‬",
    "JOIST/menuItem.mailInputEventsLog": "‪Mail Input Events Log‬",
    "JOIST/menuItem.outputInputEventsLog": "‪Output Input Events Log‬",
    "JOIST/menuItem.phetWebsite": "‪PhET Website…‬",
    "JOIST/menuItem.reportAProblem": "‪Report a Problem…‬",
    "JOIST/menuItem.screenshot": "‪Screenshot‬",
    "JOIST/menuItem.fullscreen": "‪Full Screen‬",
    "JOIST/menuItem.settings": "‪Settings…‬",
    "JOIST/menuItem.getUpdate": "‪Check for Updates…‬",
    "JOIST/menuItem.submitInputEventsLog": "‪Submit Input Events Log‬",
    "JOIST/PhetButton.name": "‪PhET Menu Button‬",
    "JOIST/titlePattern": "‪{0} {1}‬",
    "CONCENTRATION/concentration.title": "‪Concentration‬"
  }
}
```

</details>

<details>

<summary>Atomic Interactions Strings</summary>

```
{
  "en": {
    "JOIST/ieErrorPage.platformError": "‪Platform Error‬",
    "JOIST/ieErrorPage.ieIsNotSupported": "‪Internet Explorer is not supported.‬",
    "JOIST/ieErrorPage.useDifferentBrowser": "‪Please use a different browser to run this simulation.‬",
    "JOIST/a11y.home": "‪Home‬",
    "JOIST/a11y.simScreens": "‪Sim Screens‬",
    "JOIST/a11y.homeScreenDescriptionPattern": "‪Come explore with {{name}}. It has {{screens}} screens.‬",
    "JOIST/simTitleWithScreenNamePattern": "‪{{simName}} — {{screenName}}‬",
    "JOIST/a11y.simResources": "‪Sim Resources‬",
    "JOIST/queryParametersWarningDialog.invalidQueryParameters": "‪Invalid Query Parameters‬",
    "JOIST/queryParametersWarningDialog.oneOrMoreQueryParameters": "‪One or more of these query parameters have<br>invalid values:‬",
    "JOIST/queryParametersWarningDialog.theSimulationWillStart": "‪The simulation will start with default values for<br>those query parameters.‬",
    "JOIST/a11y.screenNamePattern": "‪{{name}} Screen‬",
    "JOIST/a11y.screenSimPattern": "‪{{screenName}}, {{simName}}‬",
    "JOIST/a11y.simScreen": "‪Sim Screen‬",
    "JOIST/options.title": "‪Options‬",
    "JOIST/projectorMode": "‪Projector Mode‬",
    "JOIST/a11y.homeScreenDescription": "‪Go to Home Screen.‬",
    "JOIST/a11y.phetMenu": "‪PhET Menu‬",
    "JOIST/a11y.keyboardHelp.hotKeysAndHelp": "‪Keyboard Shortcuts‬",
    "JOIST/a11y.soundToggle.label": "‪Mute Sound‬",
    "JOIST/a11y.soundToggle.alert.simSoundOn": "‪Sim sound on.‬",
    "JOIST/a11y.soundToggle.alert.simSoundOff": "‪Sim sound off.‬",
    "JOIST/menuItem.about": "‪About…‬",
    "JOIST/menuItem.enhancedSound": "‪Enhanced Sound‬",
    "JOIST/menuItem.fullscreen": "‪Full Screen‬",
    "JOIST/menuItem.getUpdate": "‪Check for Updates…‬",
    "JOIST/menuItem.mailInputEventsLog": "‪Mail Input Events Log‬",
    "JOIST/menuItem.options": "‪Options…‬",
    "JOIST/menuItem.outputInputEventsLog": "‪Output Input Events Log‬",
    "JOIST/menuItem.phetWebsite": "‪PhET Website…‬",
    "JOIST/menuItem.reportAProblem": "‪Report a Problem…‬",
    "JOIST/menuItem.screenshot": "‪Screenshot‬",
    "JOIST/menuItem.submitInputEventsLog": "‪Submit Input Events Log‬",
    "JOIST/keyboardShortcuts.title": "‪Keyboard Shortcuts‬",
    "JOIST/keyboardShortcuts.toGetStarted": "‪to get started‬",
    "JOIST/a11y.keyboardHelp.tabToGetStarted": "‪Tab to get started.‬",
    "JOIST/versionPattern": "‪version {0}‬",
    "JOIST/termsPrivacyAndLicensing": "‪Terms, Privacy & Licensing‬",
    "JOIST/translation.credits.link": "‪Translation Credits‬",
    "JOIST/thirdParty.credits.link": "‪Third-party Credits‬",
    "JOIST/credits.contributors": "‪Contributors: {0}‬",
    "JOIST/credits.graphicArts": "‪Graphic Arts: {0}‬",
    "JOIST/credits.leadDesign": "‪Lead Design: {0}‬",
    "JOIST/credits.qualityAssurance": "‪Quality Assurance: {0}‬",
    "JOIST/credits.softwareDevelopment": "‪Software Development: {0}‬",
    "JOIST/credits.soundDesign": "‪Sound Design: {0}‬",
    "JOIST/credits.team": "‪Team: {0}‬",
    "JOIST/credits.thanks": "‪Thanks‬",
    "JOIST/credits.title": "‪Credits‬",
    "JOIST/credits.translation": "‪Translation‬",
    "JOIST/updates.checking": "‪Checking for updates…‬",
    "JOIST/updates.getUpdate": "‪Get Update…‬",
    "JOIST/updates.newVersionAvailable": "‪There is a new version available: {0}.‬",
    "JOIST/updates.noThanks": "‪No Thanks‬",
    "JOIST/updates.offline": "‪Unable to check for updates.‬",
    "JOIST/updates.outOfDate": "‪New version available‬",
    "JOIST/updates.upToDate": "‪This simulation is up to date.‬",
    "JOIST/updates.yourCurrentVersion": "‪Your current version is: {0}.‬",
    "STATES_OF_MATTER/returnAtom": "‪Return Atom‬",
    "STATES_OF_MATTER/adjustableAttraction": "‪Adjustable Attraction‬",
    "STATES_OF_MATTER/argon": "‪Argon‬",
    "STATES_OF_MATTER/atomDiameter": "‪Atom Diameter (σ)‬",
    "STATES_OF_MATTER/Atoms": "‪Atoms‬",
    "STATES_OF_MATTER/customAttraction": "‪Custom Attraction‬",
    "STATES_OF_MATTER/interactionStrength": "‪Interaction Strength (ε)‬",
    "STATES_OF_MATTER/large": "‪large‬",
    "STATES_OF_MATTER/moving": "‪Moving‬",
    "STATES_OF_MATTER/neon": "‪Neon‬",
    "STATES_OF_MATTER/oxygen": "‪Oxygen‬",
    "STATES_OF_MATTER/pinned": "‪Pinned‬",
    "STATES_OF_MATTER/small": "‪small‬",
    "STATES_OF_MATTER/strong": "‪strong‬",
    "STATES_OF_MATTER/weak": "‪weak‬",
    "STATES_OF_MATTER/attractive": "‪Attractive‬",
    "STATES_OF_MATTER/electronOverlap": "‪(electron overlap)‬",
    "STATES_OF_MATTER/forces": "‪Forces‬",
    "STATES_OF_MATTER/hideForces": "‪Hide Forces‬",
    "STATES_OF_MATTER/repulsive": "‪Repulsive‬",
    "STATES_OF_MATTER/totalForce": "‪Total Force‬",
    "STATES_OF_MATTER/vanderwaals": "‪(van der Waals)‬",
    "STATES_OF_MATTER/distanceBetweenAtoms": "‪Distance Between Atoms‬",
    "STATES_OF_MATTER/distanceBetweenMolecules": "‪Distance Between Molecules‬",
    "STATES_OF_MATTER/epsilon": "‪ε‬",
    "STATES_OF_MATTER/potentialEnergy": "‪Potential Energy‬",
    "STATES_OF_MATTER/sigma": "‪σ‬",
    "SCENERY_PHET/speed.normal": "‪Normal‬",
    "SCENERY_PHET/speed.slow": "‪Slow‬",
    "SCENERY_PHET/speed.fast": "‪Fast‬",
    "SCENERY_PHET/a11y.timeControlNode.simSpeedDescription": "‪For closer observations Play sim on slow speed.‬",
    "SCENERY_PHET/a11y.timeControlNode.label": "‪Timing Controls‬",
    "SCENERY_PHET/a11y.timeControlNode.simSpeeds": "‪Sim Speeds‬",
    "SCENERY_PHET/a11y.timeControlNode.playPauseStepButtons.playingDescription": "‪Pause sim to step forward little by little.‬",
    "SCENERY_PHET/a11y.timeControlNode.playPauseStepButtons.playingWithSpeedDescription": "‪Pause sim to step forward little by little, or keep playing sim at chosen sim speed.‬",
    "SCENERY_PHET/a11y.timeControlNode.playPauseStepButtons.pausedDescription": "‪Step forward little by little.‬",
    "SCENERY_PHET/a11y.timeControlNode.playPauseStepButtons.pausedWithSpeedDescription": "‪Step forward little by little, or play sim at chosen sim speed.‬",
    "SCENERY_PHET/a11y.resetAll.label": "‪Reset All‬",
    "SCENERY_PHET/a11y.resetAll.alert": "‪Sim screen restarted. Everything reset.‬",
    "SCENERY_PHET/a11y.simSection.controlArea": "‪Control Area‬",
    "SCENERY_PHET/a11y.simSection.playArea": "‪Play Area‬",
    "SCENERY_PHET/a11y.simSection.screenSummary.multiScreenIntro": "‪The interactive {{screen}} changes as you play with it. It has a Play Area and a Control Area.‬",
    "SCENERY_PHET/a11y.simSection.screenSummary.keyboardShortcutsHint": "‪If needed, check out keyboard shortcuts under Sim Resources.‬",
    "SCENERY_PHET/a11y.simSection.screenSummary.singleScreenIntroPattern": "‪{{sim}} is an interactive sim. It changes as you play with it. It has a Play Area and a Control Area.‬",
    "SCENERY_PHET/a11y.playPauseButton.play": "‪Play‬",
    "SCENERY_PHET/a11y.playPauseButton.pause": "‪Pause‬",
    "SCENERY_PHET/a11y.stepButton.stepForward": "‪Step Forward‬",
    "SCENERY_PHET/key.tab": "‪Tab‬",
    "SCENERY_PHET/keyboardHelpDialog.grabOrReleaseHeadingPattern": "‪Grab or Release {{thing}}‬",
    "SCENERY_PHET/keyboardHelpDialog.grabOrReleaseLabelPattern": "‪Grab or release {{thing}}‬",
    "SCENERY_PHET/keyboardHelpDialog.or": "‪or‬",
    "SCENERY_PHET/a11y.keyboardHelpDialog.grabOrReleaseDescriptionPattern": "‪Grab or release {{thing}} with Space or Enter keys.‬",
    "SCENERY_PHET/key.alt": "‪Alt‬",
    "SCENERY_PHET/key.enter": "‪Enter‬",
    "SCENERY_PHET/key.k": "‪K‬",
    "SCENERY_PHET/key.l": "‪L‬",
    "SCENERY_PHET/key.space": "‪Space‬",
    "SCENERY_PHET/key.esc": "‪Esc‬",
    "SCENERY_PHET/key.pageDown": "‪Pg Dn‬",
    "SCENERY_PHET/key.pageUp": "‪Pg Up‬",
    "SCENERY_PHET/key.shift": "‪Shift‬",
    "SUN/a11y.close": "‪Close‬",
    "ATOMIC_INTERACTIONS/atomic-interactions.title": "‪Atomic Interactions‬"
  }
}
```

</details>

**Comment by liammulh** [comment]
QA can't complete the verification of https://github.com/phetsims/rosetta/issues/342 until @mattpen gets a chance to fix the Ox-Dev sign-in.

**Comment by mattpen** [comment]
Sign in should be fixed again on ox-dev.

**Comment by liammulh** [comment]
As part of this round of testing, @jbphet and I did the following:

- configured Rosetta to use the master branch of babel, to perform string commits, and to send build requests
- made changes to the sim-specific strings of ab/chains
- verified the changes looked correct on GitHub
  - see https://github.com/phetsims/babel/commit/1a743c85594362b7ab1c24234868b6152cbb4038
- SSH'd to phet-server2
- checked the build server logs to make sure the build of ab/chains completed without error
  - `Feb 15 15:47:43 phet-server2.int.colorado.edu build-server[1548523]: info: build for chains finished successfully`
- checked the built version of the sim on the production PhET website
  - https://phet.colorado.edu/sims/html/chains/1.42.1/chains_ab.html

**Comment by liammulh** [comment]
QA can't really test 3B because their test logins aren't working. I am going to test locally, and then I think we will be close to ready for deploy.

**Comment by mattpen** [comment]
I'm around, just working off hours. I'm not aware of the problem with QA logins though.  It's unfortunate that we need to depend on ox dev for authentication for this cycle as it is not stable. Can Rosetta just use phet.colorado.edu for authentication instead?

**Comment by Nancy-Salpepi** [comment]
Let us know if you need anything else. We are more than happy to help!

**Comment by liammulh** [comment]
I redeployed with new changes. I tagged the latest commit as 2.0.0-rc.4. I will run through a spot-check for each checkbox in the test.

I will also do some E2E tests.

<details>

<summary><h1>2.0.0-rc.4 Regular Tests</h1></summary>

## Phase 1: Test New Features (Spot-Check)

Be aware that the publish button is not meant to be working during this
phase.

Don't spend too much time here, maybe a few minutes per checkbox.

- [x] I will configure Rosetta to *not* perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be master.
- [x] QA will:
  - [x] ensure the translation "report" i.e. the stats for each sim in a
    given locale load properly
  - [x] spot-check a handful of the stats to ensure they are accurate
    - To do this, QA will have to look at the translated string file in
      Babel. If they really want to be thorough, they can count the
      total number of strings in the published sim.
  - [x] ensure the translation reports are cached
  - [x] ensure the tables are sortable
    - [x] ensure the sorting is correct 
  - [x] ensure the translation "form" shows errors when placeholders
    don't match
  - [x] ensure the save, publish, and test buttons are disabled when
    there are form errors
  - [x] ensure the copy button copies the English string over

### Issues to Spot-Check (spend a few minutes per checkbox)

Please only spend a few minutes on these. They were verified in the last
round of QA.

- [x] https://github.com/phetsims/rosetta/issues/331
- [x] https://github.com/phetsims/rosetta/issues/332
- [x] https://github.com/phetsims/rosetta/issues/334
- [x] https://github.com/phetsims/rosetta/issues/340
- [x] https://github.com/phetsims/rosetta/issues/347
  - To verify this, click the little info icon next to the string stats
    for each sim. Sims with shared strings should have stats for shared
strings.
- [x] https://github.com/phetsims/rosetta/issues/348
- [x] https://github.com/phetsims/rosetta/issues/350
- [x] https://github.com/phetsims/rosetta/issues/355

### Issue to Verify (spend more than a few minutes)

Please let me know if you have any questions about how to verify this
issue.

- [x] https://github.com/phetsims/rosetta/issues/342
  - Note: It's okay for Under Pressure's shared strings to be in the
    common category. 
  - To verify this, please use the live translation utility (be careful
    not to submit anything while using it) and look for sims that have
    shared strings. (There will be a header in the translation utility that
    says something like "These are shared strings".) Verify that Rosetta 2.0
    also has these shared strings. Off the top of my head, Atomic
    Interactions, Concentration, Geometric Optics: Basics, and I think some
    of CCK sims have shared strings. I think there are others as well.

## Phase 2: Test Old Features (Regular Test)

Be aware that during this phase, the publish button should work, and it
will commit strings to the test branch of Babel.

- [x] I will configure Rosetta to perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be tests.
- [x] QA will:
   - [x] ensure they can publish a translation and see the results on
     Babel
    - Please take a look at the strings file to see what repos will be
  - [x] ensure the simulation you published has a "(pending update)"
    badge next to it
    - this should go away after `VALID_METADATA_DURATION` (set to 30
      minutes as of this writing) or 10 minutes, whichever is lesser
  - [x] ensure the save button saves their translation
  - [x] ensure that once they've published a translation, and then wait
    about ten minutes, they see the strings from Babel, not strings they
    saved
    - To test this, save a translation, modify the saved translation,
      publish it, and then wait ten minutes. When you come back, you
      should see the strings that are in Babel in the form rather than your
      saved strings. (The saved translation should be deleted from the
      database when you publish.)

### Issues to Verify

- [x] https://github.com/phetsims/rosetta/issues/344
- [x] https://github.com/phetsims/rosetta/issues/345
  - This was actually a bug that was preventing the sim from being
    published properly. That bug should be fixed now, and you should be
able to "publish" (i.e. save strings to phetsims/babel) now, and you
should be able to see the pending update "badge".
- [x] https://github.com/phetsims/rosetta/issues/351
  - To test, publish a sim, then go back to the sim list. You should see
    a note that says "(pending update)", and that note should go away
after 30 minutes.
- [x] https://github.com/phetsims/rosetta/issues/342
- [x] https://github.com/phetsims/rosetta/issues/359
- [x] https://github.com/phetsims/rosetta/issues/360
  - Please test this thoroughly. To do a rigorous test, first look at
    the string files of the sims below and see what repos are going to
    be affected by your translation. Check the relevant translation files
    before you make your translation. During your translation, be sure to
    include sim-specific, shared, and common strings in your translation.
    Once you've hit the publish button, check the translation files and make
    sure the changes you're seeing make sense.
- [x] https://github.com/phetsims/rosetta/issues/361

## Phase 3: Test Down for Maintenance / Sign-In / Permissions (Spot-Check)

No issues were found for this phase during the first round of testing,
so don't spend too much time during this phase.

### Phase 3 Part A

- [x] I will configure Rosetta to show its "Down for Maintenance" page.
- QA will:
  - [x] ensure they see a message about the translation utility being
    down for maintenance
  - [x] ensure they can't access /translate/{locale}
  - [x] ensure they can't access /translate/{locale}/{sim-name}
  - [x] ensure they can't access /translate/admin

### Phase 3 Part B

- [x] I will configure Rosetta to be enabled.
- [x] I will configure Rosetta to *not* perform string commits.
- [x] I will configure Rosetta to *not* send build requests.
- [x] I will configure Rosetta to have it's Babel branch be master.
- QA will:
  - [ ] ensure that someone who isn't a trusted translator or a team
    member can't access the translation utility
  - [ ] ensure that team members who aren't trusted translators can
    access the translation utility
  - [ ] ensure that trusted translators who aren't team members can
    access the translation utility

</details>


<details>

<summary>2.0.0-rc-4 E2E Tests</summary>

</details>

**Comment by liammulh** [comment]
Okay, I'm done testing 2.0.0-rc.4. We are ready to deploy.
