### ISSUE TITLE
confirm latest changes for website profile pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#91]
@phet-steele - Can QA please confirm that the most recent changes for the profile pages haven't introduced any new bugs?

The issues are:
- [x] phetsims/website-meteor#48
- [x] phetsims/website-meteor#49
- [x] phetsims/website-meteor#50
- [x] phetsims/website#669

The components affected are the admin page tables for schools/orgs, the Add Your School/Org dialog, the School/Org autosuggest input, and the translator's page for Users.

You can test the changes on ox-dev, they are running in a production state now.

**Comment by phet-steele** [comment]
@mattpen good to go.
